### ISSUE TITLE
Data Processing/Identifications/Reference Database - Create Tab doesn't work

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#101]
I haven't been able to get the "Create" tab to work in the Reference Database Module (was testing it while writing the help file). This is after making sure all the reference images are supplied (in the correct location: \ids_volume\data\reference_images\input\Leopard_African) so that IDS can complete the image check for reference images. 

![image](https://user-images.githubusercontent.com/48274721/81311423-a87c7400-9085-11ea-9a28-819d9150f797.png)

My log mentions this: Error in .f(.x[[i]], ...) : object 'DateTimeInput' not found

**Comment by Shannon-Dubay** [comment]
Note: the second green box should say "Reference images **checked**" not exported. The images are not exported... here IDS is simply checking that you have supplied all the images that the reference dtbs [that its creating in this tool] specifies as reference images. This is just a check to make sure you have all the reference images so that no individuals are left out of reco.

**Comment by Shannon-Dubay** [comment]
Becky is now experiencing the same issue, - she needs to create the reference database for jaguars. She has been stalled for 2 weeks due to Reco/Manual Identification bugs, so I don't want to stall her work much longer. 
I checked some screenshots she sent and its not user error. Details from her email:

"It is giving me an error saying ‘Failed to generate database’. I’ve attached a picture showing how I have the Jaguar reference images sorted (i.e. the pictures are within a folder called ‘Jaguar’ in the idsvolume/data/reference_images/input/ folder). Log file also attached."
[shiny-server-shiny-20200605-152216-37493.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/4737781/shiny-server-shiny-20200605-152216-37493.log)

**Comment by RossPitman** [comment]
Completed.
