### ISSUE TITLE
Allow users to see all species information

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#102]
Change user profiles' to allow them to see all the information we added to the species list (multiple common names, latin names, etc.)

**Comment by Shannon-Dubay** [comment]
The species list needs a bit of a clean (some data is missing, some duplicates, etc) before this happens.

Multiple users have been asking for scientific names as they find the species list confusing, especially when the users are used to a non-english name.

**Comment by RossPitman** [comment]
Is it only admins that can see the species list? I can't remember.

**Comment by RossPitman** [comment]
We can export the current species list, then work on it within a csv, then upload via IDS. Handing this one to you @Shannon-Dubay

**Comment by RossPitman** [comment]
Just lest me know when I I'll export the data from Redshift.

**Comment by Shannon-Dubay** [comment]
Ready for the list when you get a chance!

**Comment by RossPitman** [comment]
[spcs.xlsx](https://github.com/pantheracorp/PantheraIDS_Issues/files/5427736/spcs.xlsx)
ATTN: @Shannon-Dubay

**Comment by RossPitman** [comment]
Users will be able to see the Species management module on next update.

**Comment by Shannon-Dubay** [comment]
[spcs_SD_20201024_final.xlsx](https://github.com/pantheracorp/PantheraIDS_Issues/files/5434311/spcs_SD_20201024_final.xlsx)

ATTN: @RossPitman 

Finished with updating the species list, and adding some key middle east species to the list. Excited to have the users be able to see it soon!

**Comment by Shannon-Dubay** [comment]
[spcs_SD_20201116_final.xlsx](https://github.com/pantheracorp/PantheraIDS_Issues/files/5548053/spcs_SD_20201116_final.xlsx)

With Phil's arabian species list included
