### ISSUE TITLE
Data Processing/Bulk Data Exporter - Server data exports to two locations

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#103]
When exporting data from a server-based dtbs, there are two outputs:
- in the "exports" directory: 3 csvs and 1 .Rdata file
- in the "unload" directory: all csvs (6 total) and many BZ2 files

For what its worth, I think the outputs created in the "exports" folder are much clearer and straightforward. Also, when you are exporting data, it is not obvious to look in a folder called "unload".

Note: the server stuff used to only export to "unload", never to "exports". only local dtbs used to export to "export".

**Comment by RossPitman** [comment]
I cannot reproduce this. The server-side data exporter only exports to the Unload folder for me.

**Comment by RossPitman** [comment]
Keep in mind though that we are going to be changing how users retrieve anything from IDS. Currently, users retrieve from the ids_volume folder, but this will soon change, so that files are sent to the downloads folder of the user's computer.
