### ISSUE TITLE
Data Processing / Backup Images - "Select Survey" doesn't load

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#104]
When first coming to the Backup Images module, even if you are signed into the server already, it still says "Please login to the database first" (or something to that effect). If you remain on that page and login again, then the surveys become available. 
These need to be available immediately when opening the Backup Images module as long as the user is logged into the server correctly.

**Comment by RossPitman** [comment]
@PhilipFaure – is this linked to your recent "Request Data" button?

**Comment by PhilipFaure** [comment]
Fixed. Surveys loads automatically after user logs in. Closing Issue.
