### ISSUE TITLE
Data Processing / Backup Images - Browse to images not standardised

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#105]
In all other places in IDS (that I have come across at least) we have moved to browsing to the parent folder of the survey folder due to the limitations of the browser. This Backup Images module requires the user to browse to the survey folder- for standardisation this should be changed to the parent folder.

**Comment by RossPitman** [comment]
The browser limitations should now be gone given that we updated the browser code. But, even though it might be faster, do we think we should keep the workflow as is (i.e., browsing to the parent folder)?

**Comment by RossPitman** [comment]
For now I've changed this so that the user must select the parent folder (basically the folder that contains SXX_XXXXX_XXXXX).

**Comment by RossPitman** [comment]
It would be worth finding out if there are any other modules that have non-standardised browse buttons.

**Comment by Shannon-Dubay** [comment]
Yeah, @RossPitman  I had the same thought. I think it is still best to keep it as browsing to the parent folder though, just in case we do need to change how the browser works in the future, and also because I think people are used to it now.... most current users have spent considerable time in classify, browsing to the parent folder. Although it is not the most straightforward way to browse, I think it is best for now

**Comment by Shannon-Dubay** [comment]
I have used most (if not all) of the modules while I was revamping the help files and all that I came across were browsing to the parent folder. This was the only one I saw that was not standardized
