### ISSUE TITLE
Data Explorer/Descriptive Statistics - Tidy Up

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#107]
Some issues that need some attention in Descriptive stats (in order of importance; generally small things):

1. spelling error: "varrying" should be "varying" in the last option from the drop down list (under SCR Pre-Analyses) - needs a fix in the drop down list as well as the plot 'title' on its page
2. the export button has been removed from all these plots- was that intended? There used to be a "Export Figure" button on the right of the plot that downloaded an HTML. These were useful!
3. renyi diversity plot axis labels are cut off  
4. can the "x" and "y" be changed to appropriate axes labels for plots? If not, can they be removed? They're admittedly subtle but now that I have seen them I can't un-see them. They can be seen in both "Daily photographic detection" plots.
5. Is it possible to put the "total number of species captured" as a proper axis label under the X axis, instead of within the plot?  This can be seen in: 
-total number of species captured
-relative abundance indices
-same idea in all 3 "activity patterns" with "kernel density" and "time" axes labels 
-same idea in "trap effort by occasion" with "effort" and "occasion" axes labels

**Comment by Shannon-Dubay** [comment]
From Jo via the forum:

Previous version of IDS allowed users to select multiple species within activity pattern section, current one only allows users to select 2 species only (within "Activity patterns - degree of overlap") or multiple species (within "Activity patterns - top 10 species detections) but then it's not user defined, would it be possible to add back that option of multiple species defined by user ?

**Comment by RossPitman** [comment]
@PhilipFaure – do you know what happened to the Export Figure buttons that used to be there for some of these plots? Did we decide to remove them? I cannot remember.

**Comment by RossPitman** [comment]
There shouldn't be X and Y labels on these plots, they should be the acutal titles. @PhilipFaure / @kacoster is this something that can be changed?

**Comment by RossPitman** [comment]
For point 5 – nope, this is the style of the plots.

**Comment by RossPitman** [comment]
Spelling error fixed.

**Comment by PhilipFaure** [comment]
I will have a look at the export buttons soon, I didn't remove them, so they might be clashing with something. Not sure about the x and y labels, will have a look at this as well.

**Comment by PhilipFaure** [comment]
Regarding the last comment by @Shannon-Dubay (i.e. "From Jo via the forum..."), this has been closed and ended up not being problem.

**Comment by Shannon-Dubay** [comment]
Hey @kacoster any updates on number 3 and 4 above? I believe those were the only outstanding issues  on this post.

**Comment by kacoster** [comment]
@Shannon-Dubay yes 3 and 4 are all good now.
