### ISSUE TITLE
Data Analyses / SCR / Capture Orientation - "Collection" button doesn't work

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#109]
Not sure what this button is supposed to do, but it doesn't work

**Comment by RossPitman** [comment]
Can you please send me a screenshot? I don't recall this button.

**Comment by Shannon-Dubay** [comment]
![image](https://user-images.githubusercontent.com/48274721/82881457-0511d700-9f40-11ea-87a1-ddbc8f7c4369.png)

It doesn't do anything when clicked, no dropdown appears or anything. As far as I'm concerned, it can be deleted

**Comment by RossPitman** [comment]
Completed.
