### ISSUE TITLE
Data Processing/Camera Trapping/Classifications/Classify: problem with loading/accesing data

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#11]
I was working on a database classifying images yesterday. Today I tried to open the database and it is not loading properly. The list of species and stations does not load. The R Console shows this:

Error : Duplicate identifiers for rows (6361, 6362), (6364, 6365), (6367, 6368), (6376, 6377), (6379, 6380), (6382, 6383)
Warning in eval(expr, env) :
  Failed to join trigger table and species observation table

This does not happen with other databases.

**Comment by rsalom** [comment]
Ross this is the same issue I mentioned over e-mail. Not sure if you´ve seen it here. Cheers.

**Comment by RossPitman** [comment]
A bug was identified in the img_clssfctn_ud_apply_edts function within img_clssfctn_ud_funs.R 

It has been fixed by applying:

`dplyr::distinct()`

to the spas_obsrvtn_tbl object

**Comment by RossPitman** [comment]
PantheraIDS v1.722 now contains the bug fix. Please update to this version to avoid this issue going forwards. I'm closing the issue, but please re-open it if the problem persists. Thanks Roberto!

**Comment by rsalom** [comment]
Hi Ross, I´ve updated to IDS v.1.723. I keep getting the same error message and, now I can´t access my other data sets either

Error : Duplicate identifiers for rows (6361, 6362), (6364, 6365), (6367, 6368), (6376, 6377), (6379, 6380), (6382, 6383)
Warning in eval(expr, env) :

And the other data set says something similar:

Error : Duplicate identifiers for rows (866, 867), (870, 871), (872, 873), (874, 875), (876, 877), (4021, 4022), (4024, 4025), (4027, 4028), (861, 862), (864, 865), (868, 869)
Warning in eval(expr, env) :
  Failed to join trigger table and species observation table

**Comment by RossPitman** [comment]
Hi Roberto, can you remember exactly what you were doing to your data sets that resulted in this issue? I'm trying to isolate where the additional bug might be. Confirm that these two other data sets started causing issues after you updated to 1.7.23, but didn't have issues before that. Or did they have issues when you were using 1.7.22 (i.e., were they edited using 1.722)? We know that 1.722 had a bug that added duplicate identifier rows, but that was though to be fixed. Please send through your two databases via email so I can evaluate and fix them. Thanks

**Comment by rsalom** [comment]
Hi Ross, I was classifying images. First one data set failed the next time I tried to load it. That was when I created this issue. But I was able to work with the other data set. Today I updated to 1.723 and I cannot load any of those two data sets I was working on. I´ll send them over e-mail. Thanks.

**Comment by RossPitman** [comment]
Hey Roberto, I'm seeing some discrepancies in your species classifications, which is causes the issues. For instance, for SBBD, TriggerID S203_20131001_20140511__Station15__CAM43147__186 was classified on 2018-11-13 01:19:28 by yourself comprising Human and Horse_Domestic (2 species), but the "Number of Species" was left at 1 (it should be changed to 2, given the two species specified). When ever you want to classify more than one species in an image, you've got to specify the number of species in the image.
<img width="357" alt="screenshot 2018-11-20 at 09 44 30" src="https://user-images.githubusercontent.com/15226110/48758512-f393a300-eca8-11e8-8c50-85b742d42363.png">
I suspect this is what is causing the problem. I'll need to think of a way to avoid this issue going forwards. I'm still looking at the other database, will let you know.

**Comment by RossPitman** [comment]
Right, I've added a catch in the next version of IDS that checks if the user has specified the correct number of species in the image (when compared to the 'Species' and 'Number' input fields provided by the user). This was we should avoid the issues you've been experiencing. Still trying to fix CVC

**Comment by rsalom** [comment]
Hi Ross, SUCCESS! the databases you sent are working correctly in the IDS 1.724! Thanks!

**Comment by RossPitman** [comment]
OK great, please can you classify some images on both data sets, then let me know if you run into trouble. I'm closing this issue for now.
