### ISSUE TITLE
Data Analyses / SCR / Identifications - "Export Identifications" section doesn't work

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#110]
I see from my log that IDS is trying to create an "Individuals" folder within Docker/ids_volume/data/database/SurveyFolder. It appears to be trying to create a folder per individual, which each has a "right" and a "left" folder within it. This is a redundant feature of IDS since this is now contained within the export modules. I personally think it can be taken out. 

If we are keeping it, it needs to be repaired. I currently do not have a survey folder that that survey in the "database" directory, so perhaps this is the problem.
UPDATE: when manually creating the surveyfolder within the "database" directory the export does work. However, it doesn't actually work because there are no images written- only folders!

**Comment by RossPitman** [comment]
@PhilipFaure  – did you work on the Export Identifications module recently? Did you come across this?

**Comment by PhilipFaure** [comment]
I only worked on the individual exporter in the main export module and haven't looked at the SCR individuals exporter yet. I am guessing it is writing empty folders when there are no images locally for a specific survey, while not checking if the folder is there before writing. Will have a look soon

**Comment by PhilipFaure** [comment]
Resolved. Closing issue
- exports from server and local if images are available.
- creates folder if no folder present
