### ISSUE TITLE
Missing Position data for survey: S6_20190411_20190602

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#111]
S6_2019 on the server is missing data in the "Position" column. 
(which makes me wonder- how was this survey processed?)
This was discovered by attempting to use it as an example for analyses, and when loading it into the first step in SCR analyses, the green boxes reported 0 database records loaded and 0 records filtered. When looking at the dtbs in Tables, I saw that the position column is empty.

**Comment by RossPitman** [comment]
Up to survey teams to fix their data.
