### ISSUE TITLE
Data Analyses / SCR / Identifications - Identifications csv still needed

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#112]
Just wanted to bring attention to the fact that the Identifications csv is still required for the analysis if working from a local dtbs. This file needs to be created manually (Southern Africa hub has been using a R script originally created by Jo for this purpose). From what I understand there was a module within IDS that created this csv, however it was removed. 
I believe that asking the user to create this csv manually is clunky and prone to user-error. Perhaps there is a solution that doesn't require this csv? If not, is there a way to automate this (I guess put the old module back into IDS somewhere).

I can provide the R script that we have been using to manually create this csv, if that will help.

**Comment by Shannon-Dubay** [comment]
Upon thinking further about this, I believe the old module probably converted the hotspotter ID output into the csv, which is why when Reco was born we did away with this old module. Our script works with the grouped dtbs in order to create the identifications csv.

**Comment by RossPitman** [comment]
We'll have to remove the identifications csv altogether. But, this analysis module isn't great as it stands, and needs a revamp.

**Comment by RossPitman** [comment]
UI re-developed. CSV no longer required. Completed.
