### ISSUE TITLE
Data Processing / Recognition - Outstanding Reco Revamp Issues/Fixes

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#113]
1) When re-assimilating comparisons: red thumbs down box with “Error failed to spread pattern recognition database” and “error Unknown column ‘Keypoints’ in my log. Works fine when loading a newly created reco dtbs, but when loading a reco dtbs that has already been worked on it gives that error. 

2) Might not be as fancy, but I think the checkmark toolbox (where you confirm, reject, select) should just be on the page like it was, above the images section. It will add one line, and will minimise the amount of clicking needed. 
-Shortcuts will also help to minimise the clicking, if possible. 

3) Ability to view the clean comparison image (without any lines) as discussed.

4) Bring back colourful lines in the comparison images: the different colours of the lines on the comparison images actually helped when there were many different lines- your eye could track each line better. I found it difficult to tell whether the lines were straight and parallel, or if they crossed each other. 

5) If no comparison images are selected and you chose “confirm selected” or “reject selected” you should get a popup that says “no images selected”, or nothing should happen. Currently, you still get the usual “successfully rejected/confirmed matches” message.

6) When viewing the comparison table from the information toolbox, cant see all columns when clicking on “column visibility” - it gets cut off at the bottom and you can’t scroll down to see your other options. 

7) Within the grouping section: if an image gets put into a group based on a place/time match and not a pattern match, it appears as though that image shouldn’t be in that group because all the rows for that image say “Rejected” in the “Match” column and they are highlighted red. Technically this isn’t wrong- all the pattern comparisons may have been rejected, but there was a time/place match instead. It would be good to find a way to convey this to the user.. it was discussed to maybe change the entries in the "Match" column to "Confirm- by pattern", "Confirm- by time/place" (but fancies words), and "Reject". That way the user can understand why certain images made it into that group.
![image](https://user-images.githubusercontent.com/48274721/82234196-637ff980-9931-11ea-9fa4-7955410629f5.png)

8) Within the grouping section, WITH reference images included: some images contained within groups that shouldn’t be- they have no pattern match and no time/place match with any other images within the group. Example given to Ross (Seen in Group 1, with image 3)

9) Within the grouping section: cant “Match to reference individual”  because there are multiple reference individuals in Ref_Individual column. These are there because every group has some rows that say “Reference” or “Rejected” in the “Match” column. This step needs to specify that only the rows in which "Match" column has "Confirm- by pattern" or "Confirm- by time/place" (fancier words needed) need to be checked for consistent Reference Individual names.

10) When assigning new name: Still have the issue of the name of the individual not changing when assigning a name- the number only updates if the sex is changed. See Issue #32 

11) For consistency, it would be great if we could get the colour blocks in the “Group ID” dropdown list of groups, so you can easily tell which group is completed (exactly as you can in the “Primary Image” dropdown of the “Validate” tab). These are great!

**Comment by Shannon-Dubay** [comment]
Initial discoveries after pushing beta IDS 2.20.872 with fixes for the above (minus no. 3, 4, 6, 11 above):

5. When using the "unselect all" button to deselect images, the "confirm" or "reject" buttons still show the successful popup message, when it should have no action. 
Note: if you select all, then "invert selection" (to select no images), then click the "confirm" or "reject" buttons, no message shows- good!
<br/>

12. (NEW- potentially similar to no. 1 above):
 I loaded in the rcgntn_dtbs_matched_20200521.Rdata you sent me, made a few edits so that my IDS wrote a new rcgntn_dtbs, then tried to load this back in to see if it would assimilate properly. When I go to load the newly created rcgntn_dtbs the upload is way too fast, and when I go to "assimilate" it is also too fast, then I see that nothing has populated in the "primary image" dropdown. The following is written in the log:
`Note: Pattern Recognition Database already contains independence data, aborting join...`
`Error in eval_tidy(pair$rhs, env = default_env) : 
  object 'Match' not found`
`Error in pttrn_rcgntn$jnd_pttrn_rcgntn_tbl$Primary_Image : 
  $ operator is invalid for atomic vectors`
`Error in UseMethod("select_") : 
  no applicable method for 'select_' applied to an object of class "try-error"`
`Warning: Error in [.data.frame: undefined columns selected
  [No stack trace available]`

**Comment by Shannon-Dubay** [comment]
13. Can still highlight rows in the grouping section tables- this doesn't need to happen anymore because the images load automatically (also gets confusing because the rows are already highlighted colors, one of which is blue)

14. In order to use the "Split Group" button, you need to have the rows you want to split highlighted, then within the split group popup, you have to "Mark" images to push to a new group. However, you only have the images you highlighted as options to chose to "mark"... this is redundant. Either it needs to be that you highlight each row you want to split, then click "Split Group" and those images are automatically pushed to a new group without needing a pop up (which I recommend against, see point above), OR the split group button automatically loads all images from that group into the popup window.

15. The "Proceed" button within the "Split Group" popup doesn't work- no additional group is created with the images you marked. This is written in the log: 
`Warning in renderWidget(instance) :
  Ignoring explicitly provided widget ID "htmlwidget-0b979d63276fadcc35b8"; Shiny doesn't use them`
`Warning in renderWidget(instance) :
  Ignoring prepended content; prependContent can't be used in a Shiny render call`
`Warning in doTryCatch(return(expr), name, parentenv, handler) :
  NAs introduced by coercion`
`Warning in max(as.numeric(pttrn_rcgntn$grps_nn_nrmlsd$GroupID), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf`
`Error : Column `GroupID` can't be converted from character to numeric`

16. The file name which gets produced under the image doesn't auto-update when selecting a new group (and therefore automatically rendering new images). It only updates when the user clicks on the new image, which is confusing. This has been an "issue" for a while; not sure if there is a simple fix for this?

17. When an image ends up in its own group (in other words, a group with only 1 image), its "Match" column still says "Confirmed" and the "Match_class" column says "Spatial_Temporal_Match". If theres an EASY way to change this (because technically it didn't match with any other image), that would be good. Otherwise, its fine to leave as is I think because it should be clear enough

18. Can we please hide columns from the grouping tables again? Recommended columns to hide: Primary Key, User Input, DateTime Input, SiteID, and Species. Also, can we put the Match_History columns next to each other, by moving Position to the left of PI_Match_Primary? 
<img width="703" alt="Screenshot 2020-05-21 at 16 12 13" src="https://user-images.githubusercontent.com/48274721/82567646-f01ef780-9b7d-11ea-9952-a234c7fd7b01.png">

19. Within groups, the order of the images doesn't match the order of the table rows- in this example you can see the reference image is in the first row (which seems to be consistent throughout all groups), but it is the third image that you flip through. Can the image order be changed to match the row order? 
<img width="1407" alt="Screenshot 2020-05-21 at 16 24 08" src="https://user-images.githubusercontent.com/48274721/82573017-84408d00-9b85-11ea-8fec-fa75fc1ffb57.png">

20. In the spirit of decluttering, the "Copy", "Print", and "Download" buttons could be removed- I don't foresee anyone needing to do this for the grouping table. But also not crucial to take these buttons out, just a suggestion.

**Comment by Shannon-Dubay** [comment]
<img width="1407" alt="Screenshot 2020-05-21 at 16 24 08" src="https://user-images.githubusercontent.com/48274721/82573293-e26d7000-9b85-11ea-8472-c54116b197ac.png">

**Comment by RossPitman** [comment]
Ouch! :confounded:

**Comment by RossPitman** [comment]
1, 2, 3, 4 completed.

**Comment by RossPitman** [comment]
7, 8, 9 completed.

**Comment by RossPitman** [comment]
10 completed.

**Comment by RossPitman** [comment]
11 skipped.

**Comment by RossPitman** [comment]
@Shannon-Dubay – can you please send me the database used to reproduce the error for point 12? Thanks

**Comment by RossPitman** [comment]
13, 14, 15 , 16 completed.

**Comment by RossPitman** [comment]
18 completed.

**Comment by RossPitman** [comment]
20 completed.

**Comment by RossPitman** [comment]
17 completed.

**Comment by RossPitman** [comment]
19 – we are changing the viewer in one of the next few updates, so will fix the order issue then. For now t'll stay as is.

**Comment by Shannon-Dubay** [comment]
Wow- @RossPitman !
 I have emailed you the database for point 12.

**Comment by RossPitman** [comment]
12 completed. Thanks for detecting this! I applied a fix for this previously, but it seems it wasn't comprehensive enough. Should be good in the next release.

**Comment by RossPitman** [comment]
Only 5 and 6 remain.

**Comment by Shannon-Dubay** [comment]
After reviewing the latest Reco (v.2.21.874):

Only 3 more things- one very important, the other ones less so. Also, as stated in earlier posts no. 5 and 6 remain (as well as 19, which will change with the new image viewer at a later stage)-
*no. 5 is most important

21.  ! Within grouping stage, Deselect all button doesn’t work properly: If I “select all”, then immediately “deselect all” and click “Confirm selected”, I can see in the table view that all the comparisons have still been confirmed (INCORRECT- nothing should have been confirmed).  
    

> A. If I manually select only one image by clicking on it and “Confirm Selected”, then “Deselect All” and “Reject Selected”, I get the INCORRECT output (everything is rejected).   

> B. If I manually select only one image by clicking on it and “Confirm Selected”, then “Inverse Selection” and “Reject Selected”, then “Deselect All” and “Reject Selected”, I get the CORRECT output (my first image is confirmed and the rest are rejected).  

22. Within grouping stage, after splitting group the rows in the new group are too dark to read: just needs a color change
<img width="1181" alt="Screenshot 2020-05-31 at 15 37 44" src="https://user-images.githubusercontent.com/48274721/83355204-3c2c2200-a35e-11ea-9103-768161a31fe2.png">

23. Within pattern matching stage, when hovering over the original image and table button, no pop up shows to label the buttons. This will be helpful to the user if they don't immediately understand what these buttons do
<img width="597" alt="Screenshot 2020-05-31 at 16 46 59" src="https://user-images.githubusercontent.com/48274721/83355234-6ed61a80-a35e-11ea-8cb9-bffee20645c0.png">

**Comment by Shannon-Dubay** [comment]
24. In the group table when looking at a group, the Position column contains no information
<img width="1402" alt="Screenshot 2020-06-01 at 01 20 04" src="https://user-images.githubusercontent.com/48274721/83365109-1c205100-a3a6-11ea-957b-dfac0cb61ad8.png">

**Comment by RossPitman** [comment]
Deselect button will be looked into by Valentine soon. Point 22 and 23 are complete.

**Comment by RossPitman** [comment]
For 24 – the position column will only have data in it if the data were available in the earlier steps. Is this the case with the above example? My example attached.
<img width="1680" alt="Screenshot 2020-06-01 at 06 00 21" src="https://user-images.githubusercontent.com/15226110/83374906-56e9af80-a3cd-11ea-94a0-80a656bb27f5.png">

**Comment by Shannon-Dubay** [comment]
Sorry, but not sure what you mean by "available in the earlier steps"? I reco'ed this example from the very beginning yesterday.

**Comment by RossPitman** [comment]
So was there data in the position column in the dtbs you used right in the beginning?

**Comment by Shannon-Dubay** [comment]
Still not exactly sure what you mean.
If you mean the regular dtbs used when running reco, no, because nothing had been done with the individuals yet. The position information only gets filled within the naming process
If you mean the recognition dtbs, anything that was a reference image or was confirmed to matched to a reference image had position information assigned to it, but nothing else did. I was under the assumption that the Position information was assigned to each image in the "Run Reco" stage, and that this information was recorded based on the "Left" or "Right" folder that it was contained in?

**Comment by Shannon-Dubay** [comment]
Also, please let me know what the buttons are called for no. 23 (the exact words so the help files can be accurate). Thanks!

**Comment by RossPitman** [comment]
Ahh sorry Shannon. I'm getting mixed up with how we used to assign position data. It used to happen in the earlier step (Classification), and was then carried through, which it was in my old test data set. I'll work to carry the data through from the Run Reco step instead.

**Comment by RossPitman** [comment]
1. View Original Images
2. Select All
3. Deselect All
4. Invert Selection
5. View Table

**Comment by RossPitman** [comment]
So I've gone down a rabbit hole trying to debug the Position column in Reco. I can confirn that the Position data IS taken from the folder names (Left, Right, Front, Back) and should carry through into the grouping table. I'm not sure why you are getting scenarios where Position is NA (empty). I just processed a dataset that didn't have any position data available from the beginning.

**Comment by Shannon-Dubay** [comment]
Directly after running reco, I have no position information in the recognition dtbs - I can send you the images in their orientation folders as well as the dtbs used to create my recognition dtbs if that would help? 
Another thought: Could this have anything to do with the new image browser not showing the folders on the "Content" side of the browser?

**Comment by Shannon-Dubay** [comment]
Also, by loading the dtbss into R I see the new recognition dtbss appear to have less attributes (only "Position" to do with the position information), while the older versions from last week have many more ("Ref_Position", "Position_PIR", "Original_Position", "Position_SIR"). Could this somehow be involved?

**Comment by Shannon-Dubay** [comment]
@RossPitman problem reported by Lauren when reco-ing from the server (not tested by me)
From Lauren:

"IDS crashes as soon as I click "Assimilate Matches" in the second tab of Recognition. I am working from the server (S4_2020) and on IDS_Beta v2.21.876." 
If you would like to re-create, shes using S4_2020 dtbs from the server, I will email reco dtbs, and the ind ref dtbs from the server (S4 all years)

**Comment by RossPitman** [comment]
Assimilate matches issue fixed. This issue has become too big. Anything not addressed in this long list should be moved to it's own issue. Thanks
