### ISSUE TITLE
Data Analyses / SCR / Geographical Reference - State Space doesn't map properly

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#114]
Correct me if I am wrong (the analyses section is my weakest area of IDS), but I thought the "State Space" tab in the "Geographical Reference" section of SCR was supposed to take into consideration the habitat zone shapefile we load into the "Generate SCR Files" section? 
When looking at Eastern Shores (S5), I get the following map, which shows that the activity centers/potential home range centers are being mapped in the ocean. Surely the state space should be cropped based on the area of the habitat zone shapefile?
![StateSpaceMap](https://user-images.githubusercontent.com/48274721/82355277-4b2bdf80-9a02-11ea-954e-d020d87ba87d.PNG)

**Comment by RossPitman** [comment]
@PhilipFaure last worked on this. The state-space should be red over inhabitable zones. Perhaps this is simply a colour rendering issue? Philip, over to you.

**Comment by PhilipFaure** [comment]
Thanks for pointing out @Shannon-Dubay - will look into it soon.

**Comment by PhilipFaure** [comment]
Resolved. Closing Issue
