### ISSUE TITLE
Data Analyses / SCR / Capture Orientations - Wrong Individual Removed!!

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#115]
When removing individuals, it appears that the wrong individuals are being removed.

For example, I highlighted Leopard_African_Unknown_5_123 (which was the only individual highlighted), and clicked "Remove Individuals" and the green box says "The following individuals were removed: Leopard_African_Male_5_27". I thought maybe the box was just reporting the incorrect individual name. But:
What is super concerning is that when the table reloads after I clicked "Remove Individuals", Leopard_African_Unknown_5_123 is still in the table and Leopard_African_Male_5_27 is not. Upon seeing this, I highlighted Leopard_African_Unknown_5_123 within the table again and clicked "Remove Individuals". The green box said individual Leopard_African_Male_5_118 was successfully removed. When the table reloaded, Leopard_African_Male_5_118 wasn't in the table but Leopard_African_Unknown_5_123 still was. 

-How long as this been removing the incorrect individuals? I am sure most users don't double check these things, and there have been a lot of analyses done lately on Southern Africa sites at least.

**Comment by Shannon-Dubay** [comment]
UPDATE: the above was from when I was using alpha on my windows computer. When using beta on my mac, I don't seen to encounter the same issue...

**Comment by RossPitman** [comment]
I don't encounter this issue.

**Comment by RossPitman** [comment]
Should we close this?

**Comment by Shannon-Dubay** [comment]
I do not encounter the first time I remove an individual, but I experience it every time after the first time I click "Remove Individuals"

**Comment by RossPitman** [comment]
Ahh, well that's interesting. I can work with that.

**Comment by PhilipFaure** [comment]
There was an indexing problem in DT::datatable() which caused the individuals to shift in the table, but on the server side this change in indexing (due to removed individuals) would not reflect (hence why this problem only occurred when it was done a second time).

Resolved. Closing Issue.

**Comment by PhilipFaure** [comment]
This fix got lost somewhere, resolved here: [d601c1f5](https://github.com/pantheracorp/PantheraIDS/commit/d601c1f5981d5064d438dfc6b56740b9a96c23f8) 
@RossPitman

**Comment by Shannon-Dubay** [comment]
2 Sept: Phil implements fix, according to above link. (but not pushed to any update yet)
14 Sept: Marike posted on the [forum](https://pantheraids.org/forum.html?p=post%2Fremove-individuals-not-removing-selected-individuals-but-different-ones-10919425%3Fpid%3D1316687264%26highlight%3Dmarike) about it . Phil replied a day later saying a fix had been created but waiting to be pushed with the next update. 
29 Sept: Ross pushed all edits to Beta

However Marike just updated her Beta yesterday and shes still experiencing the same issue with removing individuals (she contacted me via email).

**Comment by Shannon-Dubay** [comment]
Lies! I had Marike check and her update didn't finish yesterday. She will update properly and test again but I'm closing the issue now
