### ISSUE TITLE
Data Analyses / SCR / ML - Wording changes, easy

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#116]
(these are all as I understand them, from reading through the literature on the secr package)

1. The dropdown labeled "Effect on detection" should be "Effect on capture". Reasoning: at least in the package literature, "detection" is used to describe the combination of g0 (measure of capture probability), sigma (measure of distance individuals are moving), and z (shape parameter). This setting only refers to g0, which is the parameter that represents the probability of capture at a detector.

2. Within the dropdown "Effect on detection", there is an option for "Bk - animal x site transient response". I believe this should be "BK" (with a capital K), because "k" refers to "site learned response". The "site transient response" option below is "K".

**Comment by RossPitman** [comment]
These setting follow the secr package.
<img width="780" alt="Screenshot 2020-06-11 at 10 28 34" src="https://user-images.githubusercontent.com/15226110/84363304-d8f88600-abce-11ea-945c-8821df4491ec.png">

**Comment by Shannon-Dubay** [comment]
either they made a mistake or I'm not understanding correctly (most likely the latter). I suppose this can be closed then !
