### ISSUE TITLE
Difficulties reading linked HD within IDS

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#118]
From Jo on the forum (http://www.pantheraids.org/forum.html?p=post%2Funable-to-read-hdaposs-image-folders-10535278%3Fpid%3D1311619952):

I have encountered difficulties directing IDS to my image folder within linked HD. When browsing to image folder it takes a while for the window to show drop down menu under "external volume", sometimes not at all (left it for >50min, which then I kill it). 
After a chat with Ross, it seems it's an indexing process that is freezing that option. Though I would like to specify that the HD linked is a new 6TB HD, which means for now it only has little data (<300GB). I know we have used 4-6TB HD (pretty full) in the past (leopard program HDs) so was curious. 
(FYI as per Ross suggestion, I have even moved the image folder required to HD's root directory).
It was able to show image folder a couple days ago, after 20mins, though haven't been able since. (FYI I also cleared my cached images/files from my web browser, no success).

Note: Lauren has been experiencing the same when trying to read Master6 external harddrive, but has no issues with Master4 or Master7. From Lauren: "I can link M6 and run IDS with it linked correctly, but as soon as I try browse on IDS, IDS freezes and nothing happens no matter how long I wait."

**Comment by RossPitman** [comment]
This is related to old, over-loaded hard drives, and an inefficient browsing function within IDS from the package shinyFiles. @PhilipFaure is investigating.

**Comment by RossPitman** [comment]
Completed.

**Comment by Shannon-Dubay** [comment]
Hey @RossPitman, @PhilipFaure, @kacoster  -
I see the right side of the Browse screen has been made non-operational to allow for better browsing. This will impact how the user uses many modules within IDS.

Please going forward, could you let me know of any changes to the user interface such as this one? Just a comment on the GitHub issue or a message within Teams, whatever you prefer. 

This is important for me to know since I am not using IDS to manage data daily anymore, but am responsible for keeping Help Files up to date and fielding user inquiries. It will help efficiency too, as I won't be bothering you with "bugs" that aren't really bugs. 

Much, much, much appreciated! Thanks for all the hard work
