### ISSUE TITLE
Multiple sites with identical locations within IDS

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#119]
From Jo via the forum (http://www.pantheraids.org/forum.html?p=post%2Fsite-management-suggestion-10423688%3Fpid%3D1311620035):

I have came across multiple sites with the same locations :
Ulley == Ulley_Top
Thayok_Pa == Thayokpa_Ridgeline
Saspotsey_Above_Tarche == Saspotsey_Phu == Thayokpa_Valley == Yangthang

**Comment by RossPitman** [comment]
These were requested by hubs. Closing for now.

**Comment by Shannon-Dubay** [comment]
@RossPitman sorry, what do you mean requested by hubs? That the researchers asked for them to have the same coordinates?

**Comment by RossPitman** [comment]
Yep. They sent us a site list to add to IDS.
