### ISSUE TITLE
MAIN-36 ⁃ Data Processing / Identifications - Position Information Problem

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#121]
From Lauren via the forum (http://www.pantheraids.org/forum.html?p=post%2Fposition-information-problem-10539043%3Fpid%3D1311650178):

I am working on the northern Kafue 2019 survey (S3042). This survey was processed right up until the grouping stage of Reco using a local database. IDs were saved, and any additional ID edits were made on the local dtbs. The complete/final dtbs was pushed to the server thereafter 

When going to remove individuals in the analysis module, I noticed that many individuals showed 0 captures for Left and Right flanks (table on the top right where individuals are listed). It was pointed out to me that the position information of the images of each of those individuals captured was not available (ie: position= 'NA' when looking at the images in Manual Identification). 

A few key things to note are as follows:
[1] Position information was saved correctly for the images that were named during the Reco/Grouping stage (local database)
[2] The edits that I made to the IDs were also done using the same local database. These edits included matching an 'Unidentified' image to an existing ID and giving it a name, identifying an entirely new individual in the 'Unidentified' category, changing the sex of some Unknown individuals to Male or Female and then matching some 'Unidentified' images to these IDs. These edits were where the position information did not save during the manual naming process. 
[3] Examples of what I noticed--> Unknown_9 was batch renamed to Female_9 and an 'Unidentified' image was matched and named Female_9. This image DID have position information saved. Unknown_11 was batch renamed to Male_11 and an 'Unidentified' image was matched and named to Male_11. This image DID NOT have position information saved.
Another example is that three new individuals were identified (as in, they were not matched/named during Reco and were put into 'Unidentified'). These images received names during the same Manual Identification stage at the same time the other images received names, and they DID have position information saved. 
Last example is that simply matching an image to an existing ID where no changes were made to the sex etc produced two outcomes, some images had their position information saved and others didn't. So I basically cannot seem to find a clear pattern.. 

I went back into Manual Identification and was able to manually save this position information for each image for each individual, so this did not prevent me from continuing with the analyses. But this could create some issues for other surveys if these numbers in the analysis module are incorrect due to the missing position information. 

I am working on IDS v2.20.865 on PantheraIDS_latest (leopard PC). My internet connection is good and haven't had any problems with this on the last 11 SA surveys that I have been working on since March. 

Would appreciate someone taking a look at this and if I need to send any files or additional info please let me know. Thanks!

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-36) by [Unito](https://www.unito.io/learn-more)
┆Attachments: <a href="https://pantheradatascience.atlassian.net/secure/attachment/10005/dtbs.Rdata">dtbs.Rdata</a>

**Comment by PhilipFaure** [comment]
I've inserted a shinyAlert to tell the user if any of the individuals have no left and right flank data. The alert only pops up when there is no data for both positions. The figure below show an example with a dummy database where all the position data from all the individuals were set to NA.

<img width="1435" alt="Screenshot 2020-09-18 at 09 11 22" src="https://user-images.githubusercontent.com/24668143/93568024-dd7fc800-f98f-11ea-9e62-8c321b2e6d5c.png">

**Comment by Shannon-Dubay** [comment]
Thanks for this Phil, that popup will he really helpful.

However, I suspect the bug leading to the missing position information still exists? I am going to reopen the issue for now.
Lauren said she made edits to the local database (before it was pushed to the server) within Manual Identification that seem to have erased/not saved the position information for these images. Here are the specific examples of the changes she made, all of which she says resulted in the position of these images to be NA:

- naming an 'Unidentified' image an existing name 
- naming an 'Unidentified' image an entirely new name 
- changing the sex of some Unknown individuals to Male or Female



Here are the specific notes from her trials:

- Unknown_9 was batch renamed to Female_9 and an 'Unidentified' image was matched and named Female_9. This image DID have position information saved. 
- Unknown_11 was batch renamed to Male_11 and an 'Unidentified' image was matched and named to Male_11. This image DID NOT have position information saved.

    Other examples:

- Three new individuals were identified (as in, they were not matched/named during Reco and were put into 'Unidentified'). These images DID have position information saved.

- Last example is that simply matching an image to an existing ID where no changes were made to the sex etc produced two outcomes, some images DID have their position information saved and others DID NOT.

**Comment by RossPitman** [comment]
Waiting for Ross to re-jig this module first.
