### ISSUE TITLE
Data Analyses / Occupancy_SS - Unable to create grid

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#122]
When working from a server-based database, I am unable to create a grid. This is what my screen looks like:
![image](https://user-images.githubusercontent.com/48274721/83051639-940d1500-a04e-11ea-97f8-88d8cc72bee6.png)

And this was written into my log:
Error in is.character(dsn) : invalid 'pattern' argument
Error in as(sp_grd, "SpatialPolygonsDataFrame") : 
  no method or default for coercing "try-error" to "SpatialPolygonsDataFrame"

**Comment by PhilipFaure** [comment]
Can't recreate this problem on my machine running v.2.21.876. I double checked with multi-season and single season to be safe (even though the screen shot is from single season). @Shannon-Dubay could you please confirm that it is still happening on your system with the latest alpha version?

**Comment by Shannon-Dubay** [comment]
You are right- it seems to be working..... not sure what that was about, but I'll close the issue. Thanks for looking into it Phil
