### ISSUE TITLE
Data Processing / Manual Identification - Incorrect images being re-named and tagged

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#123]
From Becky Wooldridge in an email:

"I’m running version 2.20.871-
So the issue we are having is trying to tag and save the correct images as the reference images in the manual identification tab. When I filtered the reference images for each individual in the manual identification tab, it was not the images I had selected for the reference images. E.g. for some individuals there was two left images, when I definitely tagged and saved a left and right image. Not sure what may have happened?!
We are also having issues with renaming individuals in the manual identification tab. For example, we have 1 individual which is misnamed. When I try to rename the individual, everything appears to work ok, but when I reload the database the wrong image has been renamed."

Pretty concerning- can this somehow be prioritised @RossPitman ?
I also was able to recreate the tagging issue on my end- I tagged 2 images as reference images for one individual (tagged and saved). When I reload the dtbs (local dtbs; Becky is also on a local dtbs) and filter to the individual, I only had 1 image tagged as reference, and it was not an image I had chosen. Note: this did not occur every time assigning ref tags, it worked correctly when I tagged one tag for another individual.

**Comment by RossPitman** [comment]
I just tested on my end and tagged three images, saved it, then re-loaded. All worked as expected.

**Comment by Shannon-Dubay** [comment]
I have just recreated the tagging reference images issue again. I will send you the images and the dtbs needed to recreate it via Wetransfer-

- I load in the dtbs (S6_20180923_20181115) from my computer
- filter to "Leopard_African_Female_6_100" using the "Filter" button. She has 5 total images in this dtbs. 
    - I chose 2 images to tag as reference images: (1) the third image where it is extremely bright and you can't see her at all, and (2) the fifth image where she is clear in front of a "no entry" roadsign. 
        - (I just found these to be the most unique, so I could identify them later. Note: the Metadata panel doesn't work, so this can't be used to identify the images, sorry)
- After clicking "save tag/s", I reload the dtbs and refilter to Female 100 using the "Filter References" button. It says she only has 1 reference image, and it is neither of the ones I chose- it shows a very clear image of her on a game path.

**Comment by Shannon-Dubay** [comment]
I have just tested the above situation on the new release of v.2.21.876 - it appears that this is working again. I will inform Becky, who was having the issue, and ask her to use it and let me know if there any further problems. Standby for an update.

**Comment by RossPitman** [comment]
Any update on this?

**Comment by Shannon-Dubay** [comment]
No feedback from Becky, but appears to be fine on my devices. Closing.
