### ISSUE TITLE
Data Processing/Identification/Reference_Database - Needs a "Download" tab

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#125]
Moving forward, the idea will be to keep the individual reference database on the server unless absolutely necessary to work offline; in these instances, the user will be able to download a copy of the server-based individual reference database into a local copy and use Reco offline. When the user is finished and has connectivity again, it is crucial that they upload their updated individual reference database to the server once more using the "Upload" tab. 

However- the tool to download the server-based individual reference database isn't created yet. This should be developed as an additional tab.

With many teams around the globe beginning to make their own species-specific individual reference databases, this is an important feature to have, therefore I am labeling it as high priority".

**Comment by Shannon-Dubay** [comment]
Also- I see within the "Upload" tab there is no place to specify which species the individual reference database is for- is this done automatically within the server, or something we need to add to IDS?

**Comment by RossPitman** [comment]
The reference database provided to IDS contains the species label, so we don't need to provide it.

**Comment by RossPitman** [comment]
Completed.
