### ISSUE TITLE
Changes to Sites and/or Species

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#126]
Site Quineles (S3108) needs to be country = Guatemala (not Honduras). This site is _right_ against the country border, hence the mishap. Shannon to inform Barbara when complete.

Species "Common Raccoon" needs "Northern Raccoon" added to its list of common names. Shannon to inform Stephanny when complete, if species details are available to users by that time.

**Comment by RossPitman** [comment]
The country data is calculated from the X Y coordinates provided. Barbara will need to provide us with corrected X Y values, then we will change those. Species name updated.

**Comment by Shannon-Dubay** [comment]
New coordinates, should be in Guatemala:
-88.276380 15.693732
The site is RIGHT on the border with Honduras, so please let me know if it is still placed in Honduras and I will update them again.

**Comment by RossPitman** [comment]
Done.
