### ISSUE TITLE
Data Processing / Classify - Species list from server includes species with no images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#127]
This is a low priority issue, as I don't _think_ it has any negative impacts.

When looking at species lists within the Classify module for server-based dtbss, the species drop down list populates with species that have no images under that classification. I believe (although I could be wrong) that these are species classifications that once used to have images, but had been re-classified to another category, therefore leaving no images under it. I believe this mostly happens when the machine classifier incorrectly classifies an image or two, then the user realizes that species is not found in that area and re-classifies these images. 

Example: S105_20190126_20190707 from the server- species in the list and that are not in the survey (no images for them) are Bird_Other, Giraffe, Monkey_Vervet, Rhino_White, Subthreshold and Wildebeest_Blue.

Interesting note: the other S105_2019 survey (S105_20190124_20190708), which went through the exact same processing as the former survey, doesn't appear to have this happening. You would assume it would at least have an empty "Subthreshold" category, since it was put through the machine classifier as well.

**Comment by PhilipFaure** [comment]
I have edited the SQL code to pull the species and remove duplicate triggerID's and keeping only the record with the latest datetimeinput value. Previously, IDS was returning all the species in the database, including the ones that have been changed by the user.

Closing Issue.
