### ISSUE TITLE
Data Processing / Manual Identification - Image Viewer not working for mult. server-based sites

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#128]
When pulling multiple server-based dtbss, I some of the images don't load, even though I know the images are available in the location that I have 'externally browsed' to.

Example: I pulled S6_2018 and S6_2019. Individual Unknown_6_254 has 3 images across those 2 years. However, only 1 image loads; the rest have the question mark image. When looking one year at a time, all images load as they should- 1 image from 2018, 2 images from 2019. 
Another example: same sites, but individual Female_6_253. She has 21 images between both years, with only about half loading (of the ones that load, 1 is from 2019 and the others all from 2018). 

Another example: Pulled S17_2018 and S17_2019. Individual Unknown_17_620 has 6 images across those 2 years. However, again, only 1 image loads.

Nothing written in the log file.

Can supply images if you would like to test out these exact scenarios

**Comment by RossPitman** [comment]
Thanks, @Shannon-Dubay. Can you please send the example images to myself and @kacoster via WeTransfer so we can look into this? Thanks

**Comment by Shannon-Dubay** [comment]
Sent! Thanks for having a look guys

**Comment by RossPitman** [comment]
Hey Valentine (@kacoster), can you please have a look at this?

- I've loaded two surveys (**S6_20180923_20181115** and **S6_20190411_20190602**).

- I then filter to individual **Leopard_African_Unknown_6_254**.

As Shannon explains, I also only get one image rendered, even though IDS is correctly writing the csv needed to pull the images.
<img width="914" alt="Screenshot 2020-06-12 at 12 30 51" src="https://user-images.githubusercontent.com/15226110/84493973-f8fc7800-aca8-11ea-88b0-2647fe227059.png">

Screenshot of my browser below:
<img width="1680" alt="Screenshot 2020-06-12 at 12 30 25" src="https://user-images.githubusercontent.com/15226110/84494001-04e83a00-aca9-11ea-9f75-5ff50999d531.png">

**Comment by kacoster** [comment]
Fix applied to the following packages 

- **PantheraWidgets** Version: 1.6
- **PantheraIDSImageViewer** Version: 1.3.8
