### ISSUE TITLE
Data Processing/Process Images - Incremental Processing

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#129]
Can potentially be implemented with #98 , as both have to do with the images/dtbss created during incremental processing.

Currently, when processing images incrementally, the first increment of the data is processed normally. There is no difference between this, and processing a full survey. When processing the second, third, etc. increment, a folder called "merged" gets created in Docker/ids_volume/data/database and Docker/ids_volume/data/images for the dtbss and images. But I can see this causing confusion (if fact, I get tripped up once on it) because you may forget or not be aware that this particular survey was processed incrementally, and not think to look in the "merged" folder when looking for data; you will use the dtbs/images in the regular location and not have any idea of knowing that A) its only the first increment of the data and B) that there is another, fuller, database in another location. This leads to the user accidentally working on only the first increment of the data instead of the completed database.

It would be ideal if the dtbs and images could be placed in the usual locations... but this is not as straight forward because as you add data, the survey name changes (because the dates change with additional increments). 

I think it would be great to have a quick chat about this, if possible, to discuss the best way forward, as there are a few options.

**Comment by RossPitman** [comment]
Placing the merged database into a "merged" folder was only used as a precaution during early testing. So as not to destroy the original database. We should easily be able to place the merge database within the existing database directory.

**Comment by RossPitman** [comment]
Merged directory deprecated.
