### ISSUE TITLE
Data Processing/Identification/Batch Rename - Tidy up

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#130]
1. Why do we have to click "Load dtbs" after uploading our local dtbs file? This is the only module in which this is necessary for local dtbss (most of the server-based ones are like this, but no local)

2. Is it possible to remove the "All" option from being populated in the "Individuals" dropdown? This way the user won't accidentally rename all their individuals to one name..... (I can just see it happening)

3. Is it possible to automatically assign the site number based on the individuals old name (which they specify in the "Individual" dropdown? I was just able to rename an individual to the wrong site, which could very easily happen if the user forgets which number the site is or something... At the very least, if we need the user to specify the site, we need a catch to make sure the site is correct.

4. Is it possible to have it be bit more clear that the "Individual" dropdown refers to its current (soon to be old) name, while the other options after that refer to its new name?

@RossPitman

**Comment by RossPitman** [comment]
Point 2 is done.

**Comment by RossPitman** [comment]
Point 4. Is this ok?
<img width="1431" alt="Screenshot 2020-06-18 at 21 31 33" src="https://user-images.githubusercontent.com/15226110/85063944-2cf50300-b1ab-11ea-92aa-d5e79fd4dfec.png">

**Comment by Shannon-Dubay** [comment]
Yeah thanks that looks good. I'm not sure why (maybe not everything is synced?) but I can't find the new module in my local github repository. please can you add the following help file to this module? apologies if I'm just being dumb...
idntfctn_btch_rnm_help.html
it is included in my latest github push (newly created, although adapted from a file we already had)

**Comment by RossPitman** [comment]
OK it's added.

**Comment by RossPitman** [comment]
All done.
