### ISSUE TITLE
Data Processing / Recognition - Outstanding Reco Revamp Issues/Fixes

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#131]
A continuation of closed Issue #113 
1. In 'Validate' tab: When viewing the comparison table from the information toolbox, cant see all columns when clicking on “column visibility” - it gets cut off at the bottom and you can’t scroll down to see your other options. (number 6 in closed issue)
2. In grouping tab, the order of the images doesn't match the order of the table rows- for example, the reference image is listed first in the table (which seems to be consistent throughout all groups?), but it is the third image that you flip through. Can the image order be changed to match the row order? (number 19 in closed issue) 
*To be changed when image viewer is updated in later versions.

3. In 'Validate' tab: the "View Originals" button doesn't work (see temporary fix on forum post with Valentine, Marike, and Stephanny [here] (http://www.pantheraids.org/forum.html?p=post%2Frecognition-see-original-photo-10575966%3Fpid%3D1311864856))
4. In the 'Validate' tab: the information toolbox doesn't show any information

Please just confirm when number is done, thanks!

**Comment by kacoster** [comment]
Completed
