### ISSUE TITLE
Data Processing/Reco - View Original Images requires "Originals" folder in the wrong place

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#133]
In the grouping stage in Reco, the "Originals" folder is required within the pattern_recognition/SurveyFolder directory so that you can see the images within the groups.
However in the new "View Originals" button (that allows you to see each image in the comparison without lines), it requires the "Originals" folder to be located within the pattern_recognition/output/SurveyFolder location. 
It makes more sense to have them require the same thing, and the pattern_recognition/SurveyFolder is more straightforward for the user for many reasons, which for lack of space and time I won't get into here haha pretty please can we change where the "View Originals" button requires the images to be?

**Comment by PhilipFaure** [comment]
Done.
