### ISSUE TITLE
Data Processing/Recognition - Add date/time or species into name of rcgntn and grpd dtbss

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#134]
Users in Belize (Emma and team) have been struggling when using Reco because they identify multiple species per dataset (namely jaguar and ocelots for now), and they found that their rcgntn and grpd dtbss for jaguars were written over when they IDed ocelots. Now, they are realizing they made a mistake but can't go back because those databases have been overwritten.

**Comment by RossPitman** [comment]
Date-time has been added to the saved file in the next version of IDS.

**Comment by Shannon-Dubay** [comment]
@RossPitman , this only occurred to me now- does this mean that if a user works on the recognition or grouped databases over many days, that, a new file will be created with a new date/time for each save?

**Comment by Shannon-Dubay** [comment]
@RossPitman , this issue has been re-opened due to Lauren's recent experience (see forum post [here](https://pantheraids.org/forum.html?p=post%2Frcgntndtbs-rdata-created-in-incorrect-folder-10679126%3Fpid%3D1312863945))
She updated to IDS beta V2.23.890, and now the rcgntn_dtbs.Rdata saves within the ids_vol/data/database folder and not within the actual survey folder. ![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/48274721/92488067-5e033380-f1ee-11ea-9a12-d720d478f321.png)
Most importantly, each time she saves her work, a new file is created with the new date/time. See screenshot. Please can we change the naming format so that instead of the date/time, the species name is recorded instead. This is clearer from a user standpoint as they may not remember what they were working on each day, and also the time isn't accurate to the user's location (is it Greenwich time? it appears to be 2 hours off from South Africa for Lauren), which only adds to confusion. This will also ensure that a new file isn't created each time the user clicks "save" within Reco.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/48274721/92488053-59d71600-f1ee-11ea-9581-c8e9e79e30d3.png)
Lastly, the file naming structure is missing an underscore between the survey ID and the "rcgntn_dtbs" section- quick little detail!

**Comment by Shannon-Dubay** [comment]
In order to try to avoid confusion, I have labeled this as high priority so that we do not cause too much confusion- I know we have a lot of users using Reco at the moment, but I'm not sure how many have updated and are experiencing this. Lauren was the first to report it

**Comment by PhilipFaure** [comment]
Done. IDS will save the rcgntn_dtbs in the survey folder with the species name appended to it, for example: 

"./data/database/S3036_20190628_20190906/**rcgntn_dtbs_Leopard_African**.Rdata"

Closing Issue.
