### ISSUE TITLE
Viewing Images from Server not working - Classify Module 

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#135]
In classify module I was trying to view the images for S202_2017, the dtbs is on redshift and the images are all on S3. I am using beta version 2.21.883. I tried the centralamericahub schema and the admin schema (not sure which is correct?). I get the same message written into my log regardless of the schema used (this message is repeated per image that it should be loading):

Error in parse_aws_s3_response(r, Sig, verbose = verbose) :
  Not Found (HTTP 404).

**Comment by Shannon-Dubay** [comment]
Appears to be working for export and manual identification modules, however

**Comment by RossPitman** [comment]
Was this issue related to older database? The 404 error message implies that the data isn't online.

**Comment by RossPitman** [comment]
It this issue isolated to only this survey, or any survey you try?

**Comment by Shannon-Dubay** [comment]
Good news- looks like this can be closed- it was sorted over Teams coms (see below)

[20/07 10:53] Shannon Dubay
    It appears to work for southern Africa sites (I have successfully used S18_2018), but none of the Central America sites are working (tried S201_2016, S202_2017, S203_2015)
​[20/07 10:56] Shannon Dubay
    also just tried S39_2017 (south east asia) and also not working
[20/07 15:27] Ross Pitman
    Think I've fixed the Central America data sets. There was a hub naming issue. We used to call this hub Northern_Central_America_Hub. Which caused the issue on the server.
​[20/07 15:32] Ross Pitman
    Fixed South East Asia Hub too, similar issue. Used to be called Southeast_Asia_Hub
