### ISSUE TITLE
Data Processing/Identification/Reference Database - Modify database not working for western Africa server-based data

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#136]
From Marine:

When trying to Modify the server-based leopard Individual Reference Database with server-based west africa data, she gets a red thumbs down error. She is working on the latest IDs version (2.21.883) alpha version. She has tried many times even on different wifis, so she is confident it is not an issue of connectivity. She is on the west africa hub.
She gets the following written into her log file:

Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  :
  Unable to retrieve JDBC result set for SELECT DISTINCT siteid from .cmr_trggr_tbl ([Amazon](500310) Invalid operation: syntax error at or near "."
Position: 29;)
Error in st_id$siteid : $ operator is invalid for atomic vectors
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  :
  Unable to retrieve JDBC result set for SELECT DISTINCT value from admin.spcs where attribute='Species' ([Amazon](500310) Invalid operation: permission denied for schema admin;)
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  :
  Unable to retrieve JDBC result set for SELECT DISTINCT siteid from .cmr_trggr_tbl ([Amazon](500310) Invalid operation: syntax error at or near "."
Position: 29;)

I see "Invalid operation: permission denied for schema admin" but she is specifying the westafricahub when logging into the server.

Interestingly, it appears Lauren has no problems doing this with southern Africa server-based data.

**Comment by RossPitman** [comment]
Can she please send me the entire log file? I suspect the above error may not be linked to the issue she is having, so wonder if there is another error or warning lurking in the log file.

**Comment by RossPitman** [comment]
Can we also find out which survey(s) she was trying to modify the leopard reference database with?

**Comment by Shannon-Dubay** [comment]
These are the two she gave me- she tried twice.

[shiny-server-shiny-20200712-062015-37899 (2).log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5073985/shiny-server-shiny-20200712-062015-37899.2.log)
[shiny-server-shiny-20200716-071425-43597 (1).log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5073986/shiny-server-shiny-20200716-071425-43597.1.log)

**Comment by Shannon-Dubay** [comment]
She was using S105_20190126_20190707

**Comment by RossPitman** [comment]
Ahh I can't reproduce the error as I don't have all the images. Will Marine be able to send them to us?

**Comment by Shannon-Dubay** [comment]
S105_20190126_20190707 has all its images on S3- leopard images can be exported from this, then placed into the location IDS requires

**Comment by Shannon-Dubay** [comment]
Just following up on this- is there anything else you need? Sorry to hassle, but Marine has been waiting over a month on this

**Comment by RossPitman** [comment]
I think that's it. We just don't have time right now to work on this.

**Comment by RossPitman** [comment]
@Shannon-Dubay – I'm not able to export any images from the server for S105. All images come out empty or corrupted.

**Comment by RossPitman** [comment]
If we worked on feature request 69 would this solve the current issue above?

**Comment by RossPitman** [comment]
Reference database now sourced from the server.
