### ISSUE TITLE
Database not uploading correctly to Redshift

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#138]
I have been given a newly processed database from Emma in Belize to be pushed to redshift. When looking at the database in the Tables module, I can see that it contains information in the trigger table, CA table, and TS table. 
<img width="1440" alt="Screenshot 2020-08-12 at 11 11 11" src="https://user-images.githubusercontent.com/48274721/90001466-c3b4dc00-dc91-11ea-97fa-2203bdfe9a5d.png">

When attempting to upload the database to Redshift using the Backup Metadata module, I see the following result, which leads me to believe everything went smoothly:
<img width="1440" alt="Screenshot 2020-08-12 at 11 10 09" src="https://user-images.githubusercontent.com/48274721/90001325-96682e00-dc91-11ea-8b0c-a4b8d2c12b5e.png">

However, when looking in the log file, I see the following issue. The highlighted part is the section to look at, all else comes from previous actions within IDS.
<img width="1440" alt="Screenshot 2020-08-12 at 11 10 48" src="https://user-images.githubusercontent.com/48274721/90001617-efd05d00-dc91-11ea-9113-b71a2dd00746.png">

When looking at the "successfully" uploaded server-based database in the Tables module, I see the following (no trigger table information was pushed to the server!)
<img width="1440" alt="Screenshot 2020-08-12 at 11 11 55" src="https://user-images.githubusercontent.com/48274721/90001166-5bfe9100-dc91-11ea-8446-eec5980e93ee.png">

To try to rectify this, I try to upload the database again after re-logging into S3 and Redshift. I get the following highlighted section written into my log, but still no change with the trigger table information.
<img width="1440" alt="Screenshot 2020-08-12 at 11 29 13" src="https://user-images.githubusercontent.com/48274721/90002143-8f8deb00-dc92-11ea-9e76-2887658e70af.png">

**Comment by RossPitman** [comment]
Can you please send me the dataset via Teams. Thanks!

**Comment by Shannon-Dubay** [comment]
sent!

**Comment by RossPitman** [comment]
Thanks

**Comment by RossPitman** [comment]
OK so when looking at Redshift, I can see the data has been loaded. But I'm not sure why it's not sure in the Data Explorer (Tables) module. Something is up...

**Comment by RossPitman** [comment]
Ahh, I'm an idiot. The trigger table includes the merged data from the spsc_obsrvtn_tbl and indvdl_obsrvtn_tbl. But, given those tables don't have any data, the resulting table for "Trigger Table" is empty. So actually there isn't any issue with how IDS is rendering the data. The moment we get species data, or individual data, the trigger table will render with the full table.

**Comment by RossPitman** [comment]
Right now we'll leave as is, but we could consider changing this.
