### ISSUE TITLE
Data Explorer/Descriptive Stats/Activity Patterns - Showing the wrong time for certain databases

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#139]
It appears that the databases that I modified in R (using code from Ross- where I had to switch the X and Y coords), are now not displaying correctly in the activity patterns section (user defined, but potentially the others as well?) Post on forum can be found [here](https://pantheraids.org/forum.html?p=post%2Factivity-pattern-choice-of-colour-in-plots-10442112%3Fpid%3D1312474388)
The databases that had their X and Y modified include:
S3078_2019 (on server)
S3080_2019 (on server)
S202_2016 (not on server at the time of posting this post- has shared keys so waiting on Ross to fix)
S202_2019 (on server)

This was the code used to switch the X and Y:

> library(tidyverse)
load("original/location/dtbs.Rdata")
trggr_tbl -> trggr_tbl %>%
    dplyr::mutate(
    X_Old = X,
    Y_Old = Y,
    X = Y_Old,
    Y = X_Old
  ) %>%
    dplyr::select(
    -X_Old,
    -Y_Old
  )
save(
  trggr_tbl,
  spcs_obsrvtn_tbl,
  indvdl_obsrvtn_tbl,
  camact,
  tmshft,
  file = "original/location/dtbs_modified.Rdata"
)

As mentioned to Ross, I got the following warnings in my R console after switching the X and Y, but ignored them on Ross' advice. Checked that there were no NAs in either the X and/or Y column

> Warning messages:
> 1: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 2: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 3: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 4: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 5: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 6: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 7: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 8: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 9: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'
> 10: In as.POSIXlt.POSIXct(x, tz) : unknown timezone 'uninhabited'

After modification, I checked that each database could be loaded successfully into the Tables and Map modules- all went well!

**Comment by Shannon-Dubay** [comment]
I do have copies of the databases before manipulation, if that will help. They have been passed on to Phil

**Comment by PhilipFaure** [comment]
Closing Issue. Calculation of sun time has been removed and plotting of activity patterns are normal again.
