### ISSUE TITLE
Independent logic used to group camera trapping captures

### ISSUE THREAD

**Issue by RossPitman** [pantheracorp/PantheraIDS_Issues#14]
PantheraIDS recently implemented an independent pairing logic that grouped camera trapping captures by timestamp (and an associated independent threshold limit) together with a pairing logic that assessed gender. This means that on occasions when >1 animal is encountered by a camera station, the logic is such that these animals are grouped into a single animal providing the events where within the independent threshold limit and were either (1) of the same gender, or (2) one animal is of unknown gender (such that this animal is morphed into the known gender of the corresponding animal). Although this logic makes sense and this theoretically correct, we are finding scenarios where high human error on assigning gender to animals is interfering with this logic. For now, this logic has been stripped back to ignore gender and only account for the independent threshold limit.

**Comment by RossPitman** [comment]
Does everyone think this is a good step? (i.e., ignoring gender during independent pairing). I'm of the opinion that it's a bad idea.

**Comment by rsalom** [comment]
I think that gender should be considered. Nonetheless the number of cases where two individuals of different gender appear together or within the threshold limit I suspect is low, so perhaps it´s not a big issue.

**Comment by RossPitman** [comment]
This function has been amended to allow users to choose which approach they want to take.
