### ISSUE TITLE
Data Analyses/Occupancy - unable to manually load in grid shapefiles

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#140]
Unsure on the details, but according to Phil on [this](https://pantheraids.org/forum.html?p=post%2Foccupancy-help-files-10622912%3Fpid%3D1312417826) forum post, "there is a problem with manually loading in grid shapefiles from a user's computer."

**Comment by PhilipFaure** [comment]
I've fixed this for single-season occupancy models, still an issue persists with the multi-season model though - getting lost in loops...

**Comment by Shannon-Dubay** [comment]
When you get around to fixing the multi season one, could you please switch the order of the following buttons for single season and multi season please?
![image](https://user-images.githubusercontent.com/48274721/90773969-07918c00-e2f7-11ea-9860-d901fe52f34a.png)

**Comment by PhilipFaure** [comment]
Swapped them around.

![Screenshot 2020-08-26 at 16 39 21 (2)](https://user-images.githubusercontent.com/24668143/91319834-21cade80-e7bd-11ea-96fa-729b177052d8.png)

**Comment by PhilipFaure** [comment]
done. closing issue.

**Comment by PhilipFaure** [comment]
Above changes not in v2.23.891 - [cad68b8f](https://github.com/pantheracorp/PantheraIDS/commit/cad68b8f0ba65344261bd76c058e40c21a7b248c) has these fixes in.
