### ISSUE TITLE
Data Explorer/Descriptive Stats - Activity pattern plot needs quick change

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#141]
As you can see in the screenshot, the times need to have a bit more width across the X axis so that the last digit of the time can fit in the space. At the moment it is being kicked down to the next line/row, which looks a bit unprofessional.
The following plot was generated using the server-based S115_2017, and is the "Activity Patterns - Top 10 species" plot option.
<img width="1073" alt="Screenshot 2020-08-17 at 19 38 20" src="https://user-images.githubusercontent.com/48274721/90426560-8c936000-e0c1-11ea-8af7-66d11c8f95a6.png">

**Comment by PhilipFaure** [comment]
Thanks Shannon. User is now able to adjust the width and height of plot downloads to fit in all times should it not fit nicely. 
Closing Issue.

![Screenshot 2020-08-25 at 12 10 24 (2)](https://user-images.githubusercontent.com/24668143/91162335-3d09f100-e6cc-11ea-9a10-ad35669cd406.png)
