### ISSUE TITLE
Data Explorer/Descriptive Stats - Activity Pattern plots have 2 export buttons, one doesn't work

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#142]
Within the 3 Activity Pattern plot options, there is (what I assume is an old) export button, which is white and doesn't appear to work. The blue export button does work, therefore I believe the white one just needs to be removed.
<img width="1189" alt="Screenshot 2020-08-17 at 19 49 41" src="https://user-images.githubusercontent.com/48274721/90427460-d9c40180-e0c2-11ea-98b3-d23cf899d53e.png">

**Comment by PhilipFaure** [comment]
Thanks Shannon, I've removed these buttons. 
Closing Issue.
