### ISSUE TITLE
Data Analyses/Occupancy - downloaded PDF of detection & effort table is cut off

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#143]
I noticed this within single season- have not tried multi season.
When in the Generate Detection & Effort Records section of Occupancy module, there is the option to download either table. When downloading the table in PDF form, the table gets cut off (see screenshot). I can see from the table loaded in IDS as well as the CSV download that there are over 50 observations, only the first 27 are shown here.
If this isn't able to be avoided easily, I think its best to just eliminate the option to download in PDF format. They can figure that out themselves from a CSV if need be.
![image](https://user-images.githubusercontent.com/48274721/90779039-aae59f80-e2fd-11ea-9142-ef47e0108264.png)

**** ALSO- the download (no matter which format) has the file name of the IDS version (example: PantheraIDS 20v.2.21.886 20.pdf). I believe this should be changed to include either "Detection Table" or "Effort Table" as well as the survey ID.

**Comment by PhilipFaure** [comment]
I've removed pdf from the formats. Users can convert to PDF in MS Office if they really need a PDF version.
Closing Issue.
