### ISSUE TITLE
Adjust name of leopard individuals for S27_2019 (server-based)

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#145]
Site 27 has individuals with NA in their name where the site number should be in the following survey: S27_2019 (server-based). This issue was encountered before for a few sites (see closed GitHub Issue #85 ) but the issue can not be replicated. Still unsure as to what causes this, and if the issue has already inadvertently been fixed previously.

**Comment by RossPitman** [comment]
Done.
