### ISSUE TITLE
Data Processing/Recognition - Within Validate tab, ShinyAlert for mismatched surveys incorrect

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#146]
Appears that re-loading in a previously worked on recognition database produces an error saying the regular database and the recognition database are from different surveys, when they are not. Please see forum post for screenshot of error message and log files.

From Emma via the [forum](https://pantheraids.org/forum.html?p=post%2Fsurvey-not-the-same-error-message-10666826%3Fpid%3D1312753144):

I am working from the server and I am getting an error message (screenshot attached). I had not logged off for a few days but I was away from my laptop and it ran out of battery, therefore I was logged off from IDS. Now that I want to go back to continue with the validation I am getting the error again. I am certain the database and recognition database are from the same survey because these are the only ones I have on my laptop.
This happened before when I logged off but I was really early into validating the matches therefore decided to re-run. At this point I am nearly done with all matches and definitely don't want to re-run.

**Comment by Shannon-Dubay** [comment]
I have asked Emma to let us know which server-based survey she is working with and to email me the local recognition database so that we can recreate on our side, if needed.

**Comment by Shannon-Dubay** [comment]
She is working with S3078_2020 from the server, I will email the recognition database (to avoid uploading it here). Therefore, she is also working with the individual reference database from the server and is IDing jaguars. 

When I try to load everything on my side, I get the error after clicking "Assimilate Comparisons", and weirdly, I get the following written into my log:
```
Note: Pattern Recognition Database already contains independence data, aborting join...
S202
ERROR: Load Databases and Tabulate Results
```
even though I am not working with S202 at all.... cause for concern?

**Comment by PhilipFaure** [comment]
IDS was looking for the first survey in the individual reference database, in the case of S3078_20190410_20200124___Jaguar, there are three different sites' jaguar info in (i.e. S202, S3078, and S3080). Consequently, when it was checking whether the survey id matches that of the other databases it would take the first survey id (S202). IDS now check whether any of the survey ids match with that of the other databases.

Closing Issue.
