### ISSUE TITLE
Data Processing / Recognition - In grouping database, two dots in file name extension causing errors for Marike

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#147]
This is the first I am hearing of an issue like this. From Marike on the forum, see original post [here](https://pantheraids.org/forum.html?p=post%2Fassignmentgrouping-stage-error-cannot-open-the-connection-for-some-groups-10667736%3Fpid%3D1312779535).

Marike is working completely locally, and is at the Reco step of grouping/naming for S25_20200116_20200305. I have all local databases (regular, recognition, grouped) which I will email in order to recreate this issue. She does not have strong enough connectivity to send her images, although I suspect they aren't necessary. 

When in the grouping stage, 4 groups give the red "Error: connection can not be made" message and no image is shown. Upon looking further into this, it was discovered that within the "Filename" column of the grouping table, some images had two dots in their extension (..JPG). See screenshot below. Groups with issue are Group 10, 13, 25, 4. All instances of the double dot occurring are when its a pattern match (blue row) without information in the "Ref_Individual" column. 

![image](https://user-images.githubusercontent.com/48274721/91811081-354bce80-ec2f-11ea-9bf6-b1c378b2da8f.png)

The following is written into the log file (see forum post for full log file):

> cannot open file '/ids_volume/data/pattern_recognition/S25_20200116_20200305/Originals/S25__Station11__Camera1__CAM51929__2018-03-11__00-50-38..JPG': No such file or directoryWarning: Error in file: cannot open the connection

**Comment by PhilipFaure** [comment]
@Shannon-Dubay are the actual image files also named with a double dot? Or only a single dot? The error: "No such file or directory...." implies that the names aren't the same. These would have to be changed so they match with each other, but what's concerning is that somewhere it was named incorrectly, and only for some.. Could this have happened outside of IDS, for example in the software they use for batch renaming?

**Comment by Shannon-Dubay** [comment]
@PhilipFaure no, the actual images do not have a double dot. So somewhere within IDS making the database double dots got added for some reason I think?

**Comment by RossPitman** [comment]
Hi @Shannon-Dubay, have you sent these data to me yet via email?

**Comment by Shannon-Dubay** [comment]
yes, sent again now

**Comment by RossPitman** [comment]
Fixed.

**Comment by Shannon-Dubay** [comment]
@RossPitman - was the fix for Marike's database specifically or within IDS? 
Do we need to send Marike an update version of her database?

**Comment by RossPitman** [comment]
It was an issue with IDS.

**Comment by Shannon-Dubay** [comment]
it seemed like her database was created with the double dots in it though, do we need to fix her database and send it back to her?
