### ISSUE TITLE
MAIN-37 ⁃ Fix Historic Camera Active Error on Redshift- S105_20190126_20190707 and S105_20190124_20190708

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#148]
From Marine via email (sent 3 August to Ross, myself, and Philipp H)-

"While working on some SCR models in R, I realized that the camera active files for the two surveys conducted in Pendjari in 2019 included some mistakes. The people in charge of the surveys seemed to not have understood the meaning of a "0" in the matrix in the camera active file. I got in touch with them and we managed to correct the errors. However, as a result of the misunderstanding, the two camera active files for surveys S105_20190126_20190707 and S105_20190124_20190708 within IDS contain mistakes. That is a problem to run the Bayesian analyses within IDS.
When you have some time and if it is not overly complicated, could you please replace within IDS the current camera active files for surveys S105_20190126_20190707 and S105_20190124_20190708 by the ones I am attaching here?" [attached to the email referenced above]

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-37) by [Unito](https://www.unito.io)

**Comment by RossPitman** [comment]
Marine needs to export the data via IDS. Then work on the camact csv to make her necessary changes. Once done, she can provide them back to us to upload.

**Comment by RossPitman** [comment]
I will email Marine to tell her this. Will Cc you.

**Comment by RossPitman** [comment]
OK sent. Waiting on Marine...
