### ISSUE TITLE
Data Explorer / Tables - Unable to view species or individual tables for server-based surveys

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#149]
When checking that the upload updated the server database correctly in Tables module, I am not able to load the Species and Individual tables for server-based surveys (tried S3034 and S7_2019 from southernafricahub and S3078_2019 from centralamericahub). This is happening to both alpha and beta versions, but only on the latest released version (v.2.22.889)- the previous version (v2.21.886) works fine.

When clicking on these tables, I get the following message where the table should be: 
"Error" 'data' must be 2-dimensional (e.g. data frame or matrix)"

In my log file the following is written:

> Error : Strings must match column names. Unknown columns: Attribute
> Error in DT::datatable(., style = "bootstrap", escape = T, autoHideNavigation = TRUE,  : 
>   'data' must be 2-dimensional (e.g. data frame or matrix)
> Warning: Error in datatable: 'data' must be 2-dimensional (e.g. data frame or matrix)
>   100: stop
>    99: datatable
>    98: widgetFunc
>    97: func
>    84: origRenderFunc
>    83: renderFunc
>    82: origRenderFunc
>    81: output$dt_explrr_indvdl_obsrvtn_dt
>     1: runApp

**Comment by RossPitman** [comment]
I get this is more than just those surveys. It relates to the new spreading on data from long to wide format.

**Comment by RossPitman** [comment]
Fixed.
