### ISSUE TITLE
Connectivity Icon doesn't refresh

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#150]
The connectivity icon in the upper right corner doesn't show when connectivity is lost.
From Joleen on the [forum](https://pantheraids.org/forum.html?p=post%2Flogin-info-doesnt-refresh-10673139%3Fpid%3D1312808367):
"I'm using 2.22.889 version on good connectivity (30mb/s), it seems the new notification tab regarding servers connectivity (top right plug) doesn't refresh when connection is lost (time out for example), the tab still show green cloud and stats "Connected to..." while it is no longer connected."

**Comment by RossPitman** [comment]
@kacoster  – is this an issue? I recall we tested this and it was working originally.

**Comment by kacoster** [comment]
@RossPitman I think this case is for when redshift/s3 connection drops despite having an active internet connection.

**Comment by Shannon-Dubay** [comment]
If it helps, in cases like when I shut my mac (and the internet connection is obviously ended), when I open the mac again the icon still shows green and says I'm connected, however if I try anything with the server I get errors because it's not connected. Upon re-logging in, everything is back to normal. And through this entire time the icon doesn't change at all

**Comment by kacoster** [comment]
Fix added. Reopen if the issue persists.

**Comment by Shannon-Dubay** [comment]
Reopening this due to Emma's post on the forum [here](https://pantheraids.org/forum.html?p=post%2Fserver-disconnection-11268320%3Fpid%3D1321616448), saying that her connectivity icon still shows green even if the connectivity appears to be broken. 

HOWEVER, I have asked for more information, since she says she is getting disconnected from the server quite often. Feel free to also post on her thread if you need more information.

**Comment by kacoster** [comment]
Fix applied. Reopen if the issue persists.
