### ISSUE TITLE
Data Processing / Classify - Changes in "Batch Image Size" and "Image Column Size" don't reflect in image viewer

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#151]
No changes occur in the image viewer when changing the batch image size and column size settings. It is always at the default of 50 images and 5 columns. 
This was experienced on v2.22.889 beta when working with images in IDSVolume, and also on v2.21.886 beta when working with images on the server.

**Comment by kacoster** [comment]
Fix applied

**Comment by kacoster** [comment]
Fix applied to both local and server images
