### ISSUE TITLE
Two databases unable to be loaded in Tables Module

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#153]
I have 2 databases (S3036_2019 and S3037_2019) that need to be pushed to the server, however when trying to view them in Tables before uploading (to check that they have classifications and identifications), I get the following red thumbs down error message immediately after clicking "Load Database": 
ERROR: Failed to join trigger table with individual obsevation table

(SIDE NOTE: **Observation** is spelled wrong in the error message - missing an r !)

I have not yet tried to push these databases to the server because they don't seem to be in the right format and I don't want to potentially mess anything up! 
The names of the databases are both "dtbs_test_indntfctns_mrg.Rdata"

**Comment by Shannon-Dubay** [comment]
Let me know when to email the databases though- I'm worried if I send them now they will get lost in an email blackhole and they'll just have to be re-sent when the time comes.

**Comment by RossPitman** [comment]
Please send the databases to me via email. Thanks!

**Comment by Shannon-Dubay** [comment]
sent

**Comment by RossPitman** [comment]
Spelling mistake fixed. Thanks!

**Comment by RossPitman** [comment]
Done.
