### ISSUE TITLE
Data Processing / Manual Identification - number of images rendered not correct

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#154]
I was alerted to this issue by Jo via the [forum](https://pantheraids.org/forum.html?p=post%2Fincorrect-count-of-images-10673195%3Fpid%3D1312808811) (she is working with the SEAsia sites again that have had database-specific issues before due to wrong tables format, etc), but upon further inspection I realized it is happening with southern African sites too.

From Jo:
_"Running 2.22.889, busy with S32_2015 from the server in "Manual Identification", when I query "Cat_Leopard" data, IDS renders 78 images while it should actually be 99 images. When I query same species same survey in the "Classify" module, it renders the correct amount of images, 99 images, likewise when query dtbs through "Tables", same output, 99 entries. Not sure if this (Attribute issue) is linked to some work done on those dtbs I believe by Ross in March, see forum thread https://pantheraids.org/forum.html?p=post%2Fmodule-not-reading-the-dtbs-10441396%3Fpid%3D1310985180"_

When looking in Tables for S32_2015, I see there are 78 leopard cats that have been given names (even if that name is just Cat_Leopard_Unknown_XX_NA). However, how is she supposed to assign a name to the remaining leopard cat images that do not yet have a name, if she can't load them into the Manual Identifications module?

I also checked S15_2018 (picked randomly) and the same is happening- in species table there are 166 leopards, in individual table there are 153, in classify there are 166, and in manual identification when specifying the leopard species and all individuals, only 153. When looking at S15_2019 (IDed through reco), the same problem exists. S4_2020, however, is fine.

Seems to me that there is just a discrepancy in which table the information is pulled from, but in Manual Identification you should be able to see every image that is a leopard according to the species table.... not just leopards that have been given names according to the individual table. You need to be able to assign a name to an unnamed individual in Manual Identification.

**Comment by Shannon-Dubay** [comment]
Yet another forum post by Jo regarding this issue (see post [here](https://pantheraids.org/forum.html?p=post%2Fids-crashes-10469260%3F%26trail%3D45)). She wants to emphasise that she is completely stuck on all her IDS tasks due to bugs within IDS. She is frustrated because she has been stuck at this point with this database since March.
It appears that she's having the same issues with server-based S25_2016: within Manual Identification when attempting to load Servals, she gets 0 images rendered, even though in Tables she can see there are 39 serval images. None of the images have names already assigned to them.

**Comment by RossPitman** [comment]
This is still linked to a data issue, rather than IDS. So I have to apply another hack/fix to prevent this from happening. There are blank individual names in the database, which means IDS doesn't see them.

**Comment by RossPitman** [comment]
Fixed. For now...

**Comment by Shannon-Dubay** [comment]
Have created a separate issue (#158 ) for adding the "Unidentifieds" to the dropdown list, as mentioned in a previous comment on this page.
