### ISSUE TITLE
Data Processing / Machine Classifier - Central America classifier uses wrong format for some domestic species names

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#155]
Central America machine classifier classifies as "Dog_Domestic" and "Cattle_Domestic", when our IDS species list has all domestic animals starting with "Domestic_". This means that when users manually ID something as a dog, they have two "separate" species in their database: Dog_Domestic from the machine classifier and Domestic_Dog from their manual corrections in Classify Module.

Can the machine classifier be changed to be compatible with IDS? I am not sure how difficult this is.... I know we fixed it for the Southern Africa classifier previously. Might be worth having a look at the other classifiers (central africa and SE asia), but I'm not sure how to do this myself and no other users have mentioned it to me.

Also this is just something to keep in mind for any future machine classifiers that will be created, @PhilipFaure and @RossPitman . Thanks!

Additionally, Central America machine classifier classifies red brockets as "Deer_Red_Brocket"- this name should be changed to "Brocket_Central_American_Red" to reflect the accurate brocket species found in Central America, which we have recently added to the Central America species list

**Comment by RossPitman** [comment]
Done.
