### ISSUE TITLE
Move dtbs within Redshift (under incorrect Hub)

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#156]
S302_20120704_20120930 (Site Murghab, in Tajikistan) can be seen in the list of available surveys on the server when under the centralamericahub.
I know previously this site was also showing as centralamericahub in the Site Management IDS module, but this has been fixed to centralasiahub.
It seems that this database on the server just needs to be moved to the central asia hub section please.

**Comment by RossPitman** [comment]
Done.
