### ISSUE TITLE
Data Processing / Manual Identification - Need "Unidentified" option in "Individual" dropdown list

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#158]
Posted in a few places on the forum (see [here](https://pantheraids.org/forum.html?p=post%2Fchallenging-information-display-format-navigation-short-cuts-class-unidentified-10672925%3Fpid%3D1312807241%26highlight%3Dunidentified) and [here](https://pantheraids.org/forum.html?p=post%2F10469260%3Fpid%3D1314121632)) by Jo:

_"It seems the class "Unidentified" disappeared from the drop down menu, is that a bug on my side? Would it be possible to include this class again? As it stands, when users are manually identifying a dtbs, they can't select only images that are unidentified, and have to go through "All" to work on them (by only being able to pinpoint the images that still require identification through the convoluted way of hovering above the green icon/gray out section to figure out if that image is identified or not)."_

I thought it might be linked to GitHub Issue #154 ("Data Processing / Manual Identification - number of images rendered not correct"), although it seems to be different.

**Comment by RossPitman** [comment]
Completed.
