### ISSUE TITLE
Data Processing / Processing - Test that incremental processing 

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#159]
During our meeting with Alex and the rest of the Thailand team (30 June), he asked about long term monitoring which required incremental processing. We told him we would test incremental processing to ensure that new data increments can include new station locations (which have been confirmed to have unique names) and flexible checks. 

Although this is not an "issue", I have recorded it here, as it might be able to be tackled with GitHub Issue #98 .

**Comment by RossPitman** [comment]
Completed.

**Comment by Shannon-Dubay** [comment]
Hi @RossPitman , is there a sample dataset you could possibly send me that you used to test the flexible checks?
It will be very helpful, as I need to update the literature around this and to be perfectly honest I'm not sure I understand how the camera active and timeshift sheets need to be in order to have flexible checks.
