### ISSUE TITLE
Update Package : unmarked

### ISSUE THREAD

**Issue by PhilipFaure** [pantheracorp/PantheraIDS_Issues#160]
Old version of "unmarked" in IDS v2.23.891 - needs to be updated to v.1.x or above for Rota et al. species models.

Error : 'unmarkedFrameOccuMulti' is not an exported object from 'namespace:unmarked'

**Comment by RossPitman** [comment]
Remember to add new issues/requests to TG please. I've added this one

**Comment by RossPitman** [comment]
Done.
