### ISSUE TITLE
Data Processing / Classify - Images shuffle order upon reloading

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#163]
Issue from Chantae via teams/email through Phil:

"The images seem to be shuffling around every time I refresh the page" (meaning every time the user reloads (Clicks "Filter"))
"My other coworkers have reported the same issue after checking on their devices"

It is my understanding that they were on the latest version of IDS, using a server-based database (S202_20170322_20171212) but local images.

@PhilipFaure jump in here with any additional information if you have it. Thanks!

**Comment by PhilipFaure** [comment]
Done. The images were not arranged according to station, camera, date, and time on the server side. They are now arranged both on server and local side according to the FileName_New attribute.

**Comment by RossPitman** [comment]
Didn't we sort these by station, camera, date already? Are you saying this wasn't coded, or that it wasn't working?

**Comment by PhilipFaure** [comment]
Correct, these changes were implemented for both local and server - I am unable to say whether something was changed afterwards and the sorting of images was overlooked, whether it was never coded, or whether it broke.

**Comment by RossPitman** [comment]
I don't think arranging by FileName_New will work, as folks want to see images related to a specific event. Arranging by FileName_New will sort to site code, then station, then camera. So it'll show all Camera1's for instance, when actually the user wants to see all images from site code, then station then date--regardless of camera number. Make sense?

**Comment by PhilipFaure** [comment]
Okay cool, I've changed it to filter for SiteID, Station, and then DateTimeOriginal.

**Comment by Shannon-Dubay** [comment]
The same fix needs to be applied to the Manual Identification module when working with server-side databases, please.

**Comment by PhilipFaure** [comment]
Thanks Shannon, these fixes have already been implemented for both local and server side data (https://github.com/pantheracorp/PantheraIDS_v1/commit/59c8d55ba6da9f449fe09a8db7393b58b2e80868). The current version of IDS does not reflect these changes, but I think it should be available in the next version of IDS, @RossPitman ?

**Comment by Shannon-Dubay** [comment]
@PhilipFaure But even within the Manual Identification module? This post, and your linked fix, were originally for the Classify module.

**Comment by PhilipFaure** [comment]
@Shannon-Dubay, my apologies, I missed the manual identification part and thought this is to do with classification. I have implemented changes for manual identification both on server and local side. I will test tomorrow with better internet and commit.

**Comment by Shannon-Dubay** [comment]
Thank you thank you!!

**Comment by PhilipFaure** [comment]
Done. 
https://github.com/pantheracorp/PantheraIDS_v2/commit/6015cf6a84e725c169560272012ef011d41a2163
