### ISSUE TITLE
Data Processing/Reference Database - "Select Site" dropdown list should only include site numbers, not full Survey IDs

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#165]
In the new Reference Database module, in order for a user to "Explore" a reference database, they have to specify the Site and the Species in which they are interested in- then the reference database should pull all years of the site they specify, for the species they specify.
However, in the "Select Site" list, Survey IDs are listed instead of just site numbers. This leaves room for the user to accidentally skip one of the years for a particular site. It would be more fool-proof for the user to specify simply the site number and IDS automatically pulls all years available for that site.

**Comment by RossPitman** [comment]
But what if they want to view data from only one survey?

**Comment by RossPitman** [comment]
The explore function isn't a critical module (i.e., it's not used for any further analysis, etc), but rather visual investigation only.

**Comment by Shannon-Dubay** [comment]
True, but in what scenario can you see users only wanting information from one survey?
In my experience looking at all the years of a site is important because an individual may be seen multiple years, so if you only look at one year you may be concerned that it doesn't have reference images, but in fact its reference images are simply from a different year. If for some reason they wanted to only see one year, they could always filter for it in the table using the "SiteID" column.
But yes, depending on how fast the table loads, it may be inconvenient to wait for it to pull all years when you are only interested in one of them. Its a trade off

**Comment by RossPitman** [comment]
I'd rather the user is specific to the survey or surveys they request. Pulling everything down takes time and also costs more.
