### ISSUE TITLE
Data Processing/Recognition - inactivate the option to select a local database

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#166]
Since we have moved to a system which requires users to work from the server within Reco, the "Pattern Match", "Validate", and "Merge" tabs all need to be changed so that only server-based databases are options for the dtbs.

**Comment by RossPitman** [comment]
I'm not sure about this. We might have moved the reference database to the server, but I don't think we should limit folks to having to work entirely from the server. Pattern-match can still be done entirely offline. Validating and merging offline may be needed if the user's new database isn't yet loaded to the server.

**Comment by Shannon-Dubay** [comment]
I understand that in theory Pattern-match can be done offline, but Validating requires the user to generate the reference database from the server, and Assign requires the historical databases from the server when consolidating. 
Could we schedule a call for this sometime soon?
