### ISSUE TITLE
MAIN-39 ⁃ S3: Unable to view images from server

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#167]
Beta v.2.26.894, but also experienced on alpha latest version
Within the Classify module, I am unable to view the images for S3044 (database and images from the server), even though I know all the images are on S3. 
For instance, I tried to load all Aardvark images- I get the green thumbs up message saying 5 images were filtered from the server- however no images appear (I see a blank image viewer- just nothing changes). In my log I get the following message, one per image that it was supposed to load:
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Not Found (HTTP 404).

To check that the images on S3 are not corrupt or anything, I used the S3 browser to locate one of the aardvark images and download it- all worked perfectly. (I used the Tables module first to see what the aardvark image names were)

When attempting to load leopard images for this survey in Manual Identification, I can't get images to load either.

However, this is not for all surveys. I could not find a clear pattern of surveys that worked vs didn't work (looked at whether they were uploaded recently or not, looked at the country Bucket they are in on S3, looked at the year the survey was conducted in, etc.)
Tested surveys that work include: S112_2017, S113_2017, S2_2018, S5_2019
Surveys that do NOT work include: S3045_2018, S112_2018, S113_2018, S3034_2019, S15_2019

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-39) by [Unito](https://www.unito.io/learn-more)

**Comment by Shannon-Dubay** [comment]
See Jo's new forum post about this issue [here](https://pantheraids.org/forum.html?p=post%2Fimages-partially-loading-or-not-populating-11114195%3Fpid%3D1319576016).

(She mentions that S403_2017 also has some images that load, and some that don't)

**Comment by RossPitman** [comment]
This seems to be a image corruption issue. We're not sure on a fix.

**Comment by Shannon-Dubay** [comment]
Testing done using v.4.32.1026, and the Classify module. 
The following is a list of surveys whose images would not render previously:
S3044_2018: working
S3045_2018: working
S112_2018: working
**S113_2018: NOT working**
S3034_2019: working
S15_2019: working
**S3040_2019: NOT working**
S3041_2019: (not on the server- perhaps Jo was mistaken about this survey)
S403_2017: working

I cleared by browser cache of images and files from all time, and attempted the problem surveys again... no success.
I the log file does not show the error that is written when the regional hub is incorrect (it specifies the specific path its looking for when the regional hub is incorrect). The regional hub and country cannot be seen in the Tables module for server-based databases, so I cannot check there.

The error written into the log is the following, once per image that should render:
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Not Found (HTTP 404).
