### ISSUE TITLE
Data Explorer/Maps

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#17]
The query to see the stations where Species X was photographed is not working. It only shows All Stations

**Comment by RossPitman** [comment]
Not sure I'm following? Can you not filter the Species dropdown list to view other species?
<img width="1429" alt="screenshot 2018-12-14 at 06 33 56" src="https://user-images.githubusercontent.com/15226110/49983247-41c75980-ff6a-11e8-816b-00a0d32783f6.png">

**Comment by rsalom** [comment]
Yes, when I filter the species, it doesn´t do anything (is the same map with all Stations). Is there a filter button? Or should it work only by selecting the species I want to see?

**Comment by rsalom** [comment]
It is working in the new version. Thanks
