### ISSUE TITLE
MAIN-40 ⁃ Data Processing/Process Images - minor changes/questions

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#170]
1. Is the "Assess capture events" supposed to have a "Confirm" button?
1. Within the "Submit" survey details popup, how disruptive would it be for us to change the "IdentifiedBy" attribute to "ClassifiedBy" ? Because the options given there are all for species classifications. Not sure if you would then want to give an additional attribute "IdentifiedBy" that had the options of 'Manual' or "Reco'? To be honest, it would be best if this attribute could be assigned once the species were actually classified (when the user merges the predictions csvs from the machine classifier into the dtbs file the database could be updated then? Or perhaps during the "Validation" module, is this ever gets up and running? Just a thought.
1. Within the "Archive Data" tab, the Browse button can disappear if the user selects "No" for "External Images"

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-40) by [Unito](https://www.unito.io/learn-more)

**Comment by RossPitman** [comment]
Point 1: assessing capture events isn't a condition for users to meet. We can actually remove it. Not sure how useful it is TBH.
