### ISSUE TITLE
Data Processing / Reco - unable to use rcgntn.dtbs from previous version AND unable to create new rcgntn.dtbs

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#172]
Email from Lauren, using latest release (v.2.27.89) on beta.

_Trying out this new Reco_ ["new" meaning the Reco that doesn't use the Individual Reference Databases anymore] _on beta and I got the attached error message when attempting the first one using a rcgntn.dtbs that was produced using the old Reco last week._
![thumbnail_New_Reco_Error](https://user-images.githubusercontent.com/48274721/95846588-e6c04280-0d4b-11eb-9cbe-62c241c6f3dc.png)
_I then tried from scratch again and there is no rcgntn.dtbs that is produced. Instead, as soon as the comparison images were done IDS crashed. I already had the survey folder created in "database" in ids_vol but didn't have an old rcgntn.dtbs in there so there wouldn't have been any clashes._

Lauren has also emailed me a log file from when she tried to load in the "old" rcgntn.dtbs, as well as the "old" rcgntn.dtbs she would like to use within Reco for us to recreate the issue. I will email these documents with the subject being "For GitHub Issue 172"

**Comment by RossPitman** [comment]
Which survey is Lauren trying to load here? It's cut off in the image.

**Comment by RossPitman** [comment]
OK I think it's S5_2020

**Comment by Shannon-Dubay** [comment]
Correct

**Comment by RossPitman** [comment]
I loaded that server, and the recogntion database and it worked. Could it be that she had internet troubles whilst fetching from Redshift?
<img width="2559" alt="Screenshot 2020-10-13 at 15 00 16" src="https://user-images.githubusercontent.com/15226110/95863853-f8621400-0d64-11eb-8816-ec0edcc8efb1.png">

**Comment by RossPitman** [comment]
Can you please try on your version of IDS please @Shannon-Dubay. Generating the reference database can take some time FYI.

**Comment by RossPitman** [comment]
FYI the red infoBox to the right there is supposed to be green. I've changed it now. It was incorrectly coded to red.

**Comment by RossPitman** [comment]
The fact that it returns zero metdata records explains why the shinyAlert pops up.

**Comment by Shannon-Dubay** [comment]
I have successfully loaded her recognition database in, and asked her to try again. She also had success. Seems as though her internet had problems and didn't pull the S5_2020 regular dtbs information properly? 

We are both waiting for the "Generate Reference Database" to complete.

**Comment by RossPitman** [comment]
Ahh jeez, last time I tested this it worked.

**Comment by Shannon-Dubay** [comment]
just as a follow up to this, Lauren (who was able to load in her regular dtbs and rcgntn.dtbs successfully this time), got the following popup a few minutes after clicking "Generate Reference Database".
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/48274721/95948301-9a7b0e00-0df0-11eb-96fd-51764de51a15.png)

She did admit her internet has been acting badly, so it could be due to a drop in her connection, but I'm not sure.
Here is her log file from the session:
[shiny-server-shiny-20201013-133625-39323 (1).log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5375854/shiny-server-shiny-20201013-133625-39323.1.log)

**Comment by RossPitman** [comment]
Lauren's log file suggests it select "NA" for species. When I'm assuming it should be specifying "Leopard_African". AWS then returns a disk full error message, presumably because she's asking to return to much data.

**Comment by RossPitman** [comment]
So the NA species can be explained by the fact that I incorrectly thought that the rcgntn_dtbs has species information. Not sure how I missed that during testing?

**Comment by RossPitman** [comment]
Fixed the site inclusion issue...spelling mistake

**Comment by RossPitman** [comment]
OK fixed.
