### ISSUE TITLE
Data Processing - Bulk Image Exporter - images (from server) not being exported

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#173]
The following is a [post](https://pantheraids.org/forum.html?p=post%2Fnew-export-module-cant-export-images-11115000%3Fpid%3D1319582730) from Jo:

_I'm using the new version 2.27.895, and am now unable to export images (all images populating correctly when working on "Classify" module), site : S3025, dtbs and images from server.
I have tried both : A) Selecting "Download Directory", and click "Export Images", the progress bar shows "Locating Images" though the output is an orange error message: "WARNING Failed to export some/all image data"; and B) Selecting "Custom Directory", and clicking "Export Images" after selecting IDS Volume as directory, nothing happen, no progress bar._

See the forum post for her log file.

I have also tested this and experience the same on v.2.27.895 BETA, using images that I successfully exported from the server a few weeks ago. This is 3_2019 Spotted Hyaena images (221 images in total)

**Comment by Shannon-Dubay** [comment]
Here is the log file from when I tried:
[shiny-server-shiny-20201013-141258-43609.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5375953/shiny-server-shiny-20201013-141258-43609.log)

**Comment by RossPitman** [comment]
OK this is just a missing package. Should be an easy fix.

**Comment by RossPitman** [comment]
Which survey did you try download, and which species?

**Comment by Shannon-Dubay** [comment]
3_2019 Spotted Hyaena images (221 images in total)

**Comment by RossPitman** [comment]
OK this is fixed.
