### ISSUE TITLE
Data Processing/Reco - Toolbox (and map) not working in Validate tab

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#174]
The toolbox in the top right of the Validate tab, which contains the options to Declutter and Hide the map, doesn't seem to be working.
The declutter checkbox has no effect.
Also, the map seems to be trying to show, regardless of what setting the toolbox is set to. However, the map shows as "Error: $ operator is invalid for atomic vectors" in red. Please let me know if I need to make the map error its own issue.

I used a local dtbs and rcgntn.dtbs for S27_2018 (the small data set I used to test reco), using 80km radius.
On the release that occurred today (v.2.27.897) alpha.

**Comment by Shannon-Dubay** [comment]
@kacoster does your fix include the map too, or just the toolbox inactivity?

@RossPitman - before fixing the map we might want to think about GutHub Feature Request 65 ([here](https://github.com/pantheracorp/PantheraIDS_Features/issues/65)) where its suggested we move the map to another module.

**Comment by RossPitman** [comment]
Noted. I'll look into this tomorrow.
