### ISSUE TITLE
Data Processing/Manual Identification - image metadata not showing correctly

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#175]
See Jo's post on the forum [here](https://pantheraids.org/forum.html?p=post%2Fidentifications-missing-in-manual-identification-11116301%3Fpid%3D1319613344) for more details.

Urgency : High (I [Joleen] need to proceed with IDs of other sites and unsure if I can do so while we have this issue ?)
Version used : 2.27.897
Dtbs origin : Server
Images origin : Server
Dtbs : S25_2016 
Species : Serval

Only the file name is showing in the metadata information toolbox.

<img width="596" alt="Screenshot 2020-10-16 at 19 55 47" src="https://user-images.githubusercontent.com/48274721/96292511-a5e55980-0fe9-11eb-86a9-f0581fa6e179.png">

**Comment by Shannon-Dubay** [comment]
Could this possibly be from the changes done on GitHub Feature Request 83 ([here](https://github.com/pantheracorp/PantheraIDS_Features/issues/83)) @kacoster ?

**Comment by RossPitman** [comment]
@kacoster – not sure if this is linked, but please take a look when you get a chance. Thanks!

**Comment by kacoster** [comment]
Completed.
