### ISSUE TITLE
Data Processing/Manual Identification - Individuals' images render under their name and also under Unidentified

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#176]
According to Jo's post on the [forum](https://pantheraids.org/forum.html?p=post%2Fidentifications-missing-in-manual-identification-11116301%3Fpid%3D1319613344):

_it looks like all the images are doubled up under the ID entered and as "Unidentified"
When I select the "Unidentified" it populates 39 images, which equals the total number of serval (while all were identified, and when ID's entered are selected it does populate images)_

Urgency : High (I [Joleen] need to proceed with IDs of other sites and unsure if I can do so while we have this issue ?)
Version used : 2.27.897
Dtbs origin : Server
Images origin : Server
Dtbs : S25_2016 
Species : Serval

So, we just need to fix it so that any individual with a name doesn't render under the newly added "Unidentified" category (the adding of the "Unidentified" category was recent GitHub Issue #158 )

**Comment by RossPitman** [comment]
Fixed.

**Comment by Shannon-Dubay** [comment]
Hi @RossPitman I've got another forum post by Jo - do you think this fix will also solve the problem she mentioned yesterday [here](https://pantheraids.org/forum.html?p=post%2Fnot-finding-species-images-11120359%3Fpid%3D1319628224) ?

**Comment by RossPitman** [comment]
It's not related, but I'm looking into it now.
