### ISSUE TITLE
Data Processing/Manual Identification - Edits are not saving

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#177]
From Jo on the [forum](https://pantheraids.org/forum.html?p=post%2Fnot-able-to-save-identification-11120386%3Fpid%3D1319628364):

_I'm trying to ID species from Manual Identification, though when clicking "Apply" and "Save", no progress bar appears. When I reload the survey in the module, the identification didn't indeed save._
Urgency : High 
Version used : 2.27.897
Dtbs origin : Server
Images origin : Server
Dtbs : S112_2017 
Species : Serval

**Comment by RossPitman** [comment]
Fixed. Coming in new update.
