### ISSUE TITLE
Data Processing/Classify - not able to save local dtbs unless a survey folder already exists for it

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#179]
I stumbled across this while testing something else.

If you are working locally, IDS can't save the dtbs if you don't already have a survey folder (i.e. S4_2019xxxx_2019xxxx) for it within Docker/ids_volume/data/database. 

The code should say something like "look for this folder, if it's not there, create it".  I know we have applied fixes for this in other places, like when running Reco pattern matching when the comparison images and recognition dtbs are produced.

My log file says the following when encountering this issue:

Warning in gzfile(file, "wb") :
  cannot open compressed file '/ids_volume/data/database/S4_20170724_20170914/dtbs.Rdata', probable reason 'No such file or directory'
Error in gzfile(file, "wb") : cannot open the connection

**Comment by Shannon-Dubay** [comment]
another example of the code to follow would be for the "Save" button in the "Edit Primary Image" panel in the Manual Identification Module- it is correct here.

**Comment by RossPitman** [comment]
Done.
