### ISSUE TITLE
Data Processing/Classify - download button when using local dtbs results in text dtbs being downloaded

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#180]
In the Classify module, when working with a local database, upon making changes and clicking the "Download" button a zip file is downloaded to the computers Download folder. 
A TextEdit file is unzipped:
<img width="1433" alt="Screenshot 2020-10-21 at 21 41 24" src="https://user-images.githubusercontent.com/48274721/96774375-31922800-13e6-11eb-952f-c511c0ddb4cc.png">

Note, this was on a mac, not tested on windows.

**Comment by RossPitman** [comment]
I can't reproduce this. I load a local dtbs.Rdata file, makes edits, apply and save, then download. The download results in zip file, which I unzip to produce a working dtbs.Rdata file.

**Comment by RossPitman** [comment]
In your example it also looks like you don't have an extension related to that file. It's just dtbs 2 when it should be dtbs.Rdata. Your pc may not know how to open the file, hence the scrambled text data.

**Comment by Shannon-Dubay** [comment]
yes, good point. when I simply double click to unzip and my mac uses the default "Archive Utility" to unzip, I get the text file. However, when I choose "The Unarchiver", a third party app that I think I downloaded myself, it works.
So it seems this issue can be closed, unless there are any other red flags you see.
