### ISSUE TITLE
Data Processing/Bulk Image Export - Download popup overtakes error/warning popup

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#181]
Bulk Image Export: S203_2015 (database and images from server); Species=Armadillo; Station=All; Camera=Camera1; downloading to Downloads folder.

I could see the warning/error popup that Phil created for GitHub Issue #152 (to let the user know that there were duplicate images), but it was immediately overtaken by the popup to download the images. We will need to find some way to keep the first popup up until the user clicks, then have the download popup come up afterwards.

**Comment by RossPitman** [comment]
The first modal seems to only be there to inform the user, so we can likely remove the modal in favour of an infoBox or valueBox. Keeping the first modal would only be necessary if the modal was deterministic. Unless we want the first modal to be deterministic? i.e., if the modal triggers, should we be stopping the process? Or allow the user to chance to stop the process? @Shannon-Dubay @PhilipFaure

**Comment by RossPitman** [comment]
@PhilipFaure – fyi, the added code for bulk image export, where duplicate images are detected, doesn't contain any redundancy. Please add this to your list of redundancy checks. I'm going to add redundancy to this section of IDS because I'm in here already, but I'm not looking at all the other code. Thanks!

**Comment by Shannon-Dubay** [comment]
No, the first model doesn't need to be deterministic- the export can still continue. But it is good to inform the user and because there is quite a lot of information on the popup they will need time to read and digest the information.

**Comment by RossPitman** [comment]
Oh I see, valueBoxes won't work here. Although we may not need it, it's cleaner to make the modal deterministic. Doing that now and testing.

**Comment by RossPitman** [comment]
@Shannon-Dubay / @PhilipFaure – is there a reason why we didn't include the duplicate image check for individual bulk image exports? Is it not needed?

**Comment by Shannon-Dubay** [comment]
I'm not sure why- I feel it should be there.

**Comment by RossPitman** [comment]
OK probably best to create a Github FR for that then. Closing out this issue
