### ISSUE TITLE
Survey in wrong hub?

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#182]
When trying to view S302_2012 (Tajikistan) from the server in Classify Module (both dtbs and images are from server- central asia hub), I get the green thumbs up, but no images appear. This site has a history of being in the wrong place, see: Github Issue #156 

My log has the following lines in it (each error shown once for each image that should have loaded):

S302_20120704_20120930/images/S302__Station11__Camera1__CAM41956__2012-09-14__14-53-31.JPGs3://pantheraids-central-america-hub/Tajikistan/

Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Not Found (HTTP 404).

**Comment by RossPitman** [comment]
All working now:
<img width="2559" alt="Screenshot 2020-10-27 at 06 35 48" src="https://user-images.githubusercontent.com/15226110/97257475-b6ce7000-181e-11eb-84e2-5ef96fb13815.png">
