### ISSUE TITLE
Data Processing/Reco/Validate Tab - Site radius error due to shared keys

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#183]
Marikes post on the [forum](https://pantheraids.org/forum.html?p=post%2Ffailed-to-generate-site-inclusion-statistics-in-validate-tab-11247338%3Fpid%3D1321430977).

She gets a red thumbs down error saying “Failed to generate Site Inclusion statistics” when attempting to reco with a local dtbs. She has tried a variety of radiuses. 

I believe she is working with limited wifi connectivity, so this could be the culprit, however her log file seems suspicious to me. It appears her second log file is the relevant one.

**Comment by Shannon-Dubay** [comment]
Upon further inspection and with additional information provided by Marike via the forum, it appears that this issue is database-specific. **The issue is shared keys.**

She sent me the database and recognition database via email, which I will send to you now with the email subject line "GitHub Issue #183". 

Upon loading both databases into the "Validate" tab of Reco, immediately after pressing "Generate Reference Database" I see the red thumbs down message saying "Failed to generate site inclusion statistics". This is regardless of what my "Site Inclusion Radius" is set to (I tried 10, 20, 30, 40, 50, and 100kms). I tried this twice. 
The first attempt my log said this:

> Error : Each row of output must be identified by a unique combination of keys.
Keys are shared for 4 rows:
92, 103
17, 22
Error : Column `value` can't be converted from character to list


The second attempt my log said this:

> Error : Each row of output must be identified by a unique combination of keys.
Keys are shared for 4 rows:
186, 200
7, 98
Error : Column `value` can't be converted from character to list

This is labeled urgent because of the urgency in which these data need to be analysed for a report deadline, which is next Monday, 9 Nov.

**Comment by RossPitman** [comment]
Hey Shannon. I don't seem to have an email with the above subject line. Was this issue sorted?

**Comment by Shannon-Dubay** [comment]
Re-sent, please let me know if you still don't get it.

**Comment by RossPitman** [comment]
Fixed. We had to update a function since station data for this dataset contain duplicate stations with slightly different coordinates.

**Comment by Shannon-Dubay** [comment]
Thanks Ross, thats good to know
