### ISSUE TITLE
Data Processing/Reco/Pattern-Match - IDS crashes after reco runs for about 15 minutes

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#185]
Hannah (CB masters student working with spotties data) is using v2.27.898 alpha and her IDS crashes at the end of running the pattern comparisons (Pattern-match tab). She is working with 220 images (she has successfully completed reco on 2 different sites on previous IDS versions with many more image than this), and about 22,000 comparison images are created before IDS crashes. No rcgntn.dtbs file is created.
Survey: S3_2019 from the server. I can get the images if needed.

Her log file (which includes many lines of an error I haven't seen before):
[shiny-server-shiny-20201029-141504-36791.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5459462/shiny-server-shiny-20201029-141504-36791.log)
The last warning/error is produced just as it crashes.

**Comment by Shannon-Dubay** [comment]
Lauren is also now experiencing the same issue, on the same version, but beta.
She is working with roughly 500 leopard images to compare, but this is within the range that her computer has completed in the past. 
Survey: S3_2020 from the server

**Comment by Shannon-Dubay** [comment]
Laurens most recent post on the forum regarding this: [here](https://pantheraids.org/forum.html?p=post%2Fids-crashing-11260597%3Fpid%3D1321547810)

_"I have attempted to run two different surveys and the same thing happens to both. When clicking "Run", my comparison images start to generate within the ids_vol/data/Pattern_recognition/outputs folder, however at some point IDS crashes (screen goes grey and disconnects from server) without generating a rcgntn.dtbs. For S3_2020, this ran for about two hours before it crashed and I tried this three times, each time a different number of comparison images were generated before it crashed. For S3039_2020, it crashed almost instantly._ 

_This happens when working from IDS beta V2.28.899, V2.27.897 and V2.27.898 as well as alpha V2.28.899."_

**Comment by RossPitman** [comment]
Do we have some log files for this?

**Comment by Shannon-Dubay** [comment]
Just the one from Hannah, which is attached above in the original github post. This log file was created while I was teamviewering, and is from a fresh IDS session (meaning we started a new IDS session and tried running reco and thats it- so all the error messages contained in the log file pertain to reco.... nothing else was done in that IDS session)

**Comment by RossPitman** [comment]
Please can you provide me with Hannah's images, thanks.

**Comment by Shannon-Dubay** [comment]
I have asked for them now

**Comment by Shannon-Dubay** [comment]
I have received a link to Hannah's images, which I will forward to you now, with the subject "GitHub Issue 185"

**Comment by RossPitman** [comment]
I'm running Hannah's data at the moment. So far no crash yet, but I suspect it'll come soon. I actually think this is an image corruption issue, or something in the image/s that's causing the pattern recognition algo to fail. Not sure if we can fix this...

**Comment by RossPitman** [comment]
OK crashed now...

**Comment by RossPitman** [comment]
Fixed.
