### ISSUE TITLE
Data Processing/Bulk Data Exporter - S33_2016 not exporting to downloads folder, but IS exporting to Unload directory

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#186]
Within the Bulk Data Export module, I am able to export S33_2016 (all species, all stations, all cameras) successfully to the Docker/ids_volume/data/unload directory, but when clicking the "Download" button in the popup to export to my mac's downloads folder, I get the message "Failed - server problem" from the bottom downloads bar within my browser. (see screenshot)
<img width="1440" alt="Screenshot 2020-11-02 at 22 20 10" src="https://user-images.githubusercontent.com/48274721/97915128-9ee47800-1d59-11eb-9bfb-b10e00efd58e.png">

This was using alpha v.2.27.898 AND alpha v.2.28.889 versions. 
I also tried from the South East Asia hub and the admin hub.

The following was written into my log:

Garbage collection 162 = 83
+27+52 (level 2) ... 
371.1 Mbytes of cons cells used (61%)
256.0 Mbytes of vectors used (14%)
Warning: Error in zip_internal: Some files do not exist
  [No stack trace available]

**Comment by RossPitman** [comment]
Fixed.
