### ISSUE TITLE
Data Processing/Reco/Validate Tab - confirm/reject of comparison images not being saved

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#187]
See Marikes forum post [here](https://pantheraids.org/forum.html?p=post%2Fvalidate-failed-to-save-pattern-matching-database-11253017%3Fpid%3D1321482690) - she's pretty desperate to get this work done before a deadline.

When viewing all the comparison images and attempting to confirm or reject a comparison, a popup appears saying "Successfully rejected/confirmed match". However, at the top of the page there is a red thumbs down error message saying "Failed to save pattern matching database" and nothing is updated within the database file. 
![image](https://user-images.githubusercontent.com/48274721/98169636-4f3ab380-1ef5-11eb-8c6b-f1f3761f08aa.png)

Her internet connectivity is good. Using beta v2.28.899. Local dtbs file (S26_2020).

I have asked her for her dtbs and images, and ran reco myself. Interestingly, I was able to complete the reco process and a recognition database was created without IDS crashing (see where this is an ongoing issue for some users (in contrast to me, they are using server-based databases) in Github Issue #185). However, I get the same error message when trying to confirm or reject comparisons. I have tried this on beta v2.28.899 and also alpha v2.27.898.

**Comment by RossPitman** [comment]
Can you please send me the data so I can reproduce the errors. Thanks!

**Comment by RossPitman** [comment]
FYI – I just asked for the images on the forum.

**Comment by Shannon-Dubay** [comment]
Apologies for only getting to this now. I have forwarded you an email with the database, recognition database, and left/right/original images in order to run reco, which will produce the comparison images needed to reproduce the error.

**Comment by Shannon-Dubay** [comment]
(she tried to send me the comparison images via dropbox, but due to the large number of them, ran into issues)

**Comment by RossPitman** [comment]
Thanks, that Dropbox link has expired, so will need to get an updated one.

**Comment by RossPitman** [comment]
OK got the images

**Comment by RossPitman** [comment]
Fixed.
