### ISSUE TITLE
Data Uploader/Server - User not able to upload unstructured data

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#188]
Stephanny Arroyo (Costa Rica) has tried to upload her data for back-up purposes to the server twice now, but no success. She is trying to upload everything from the OSA project- including csvs, original photos, processed photos, rdata files.

She was recently given server credentials (along with the rest of her team). Using the latest IDS version (2.28.899)

Her log files have the following:

> Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
>  Unable to retrieve JDBC result set for SELECT DISTINCT siteid from .cmr_trggr_tbl ([Amazon](500310) Invalid operation: syntax error at or near "." 
> Position: 29;)
> Error in st_id$siteid : $ operator is invalid for atomic vectors
> Error in st_id$siteid : $ operator is invalid for atomic vectors

> fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
> Warning in system(sys.cll, intern = TRUE) :
  running command '/anaconda3/envs/awscli/bin/aws s3 sync //ids_volume/data/images/S3061_20180219_20180613 s3://pantheraids-unstrctrd-dt/sarroyo@panthera.org/processed_images/S3061_20180219_20180613/' had status 1
> Error in names(out) <- c("id", "attribute", "value", "userinput", "datetimeinput") : 
  'names' attribute [5] must be the same length as the vector [3]
> Error in UseMethod("drop_na_") : 
  no applicable method for 'drop_na_' applied to an object of class "try-error"

See her [forum post](https://pantheraids.org/forum.html?p=post%2Fuploading-data-to-server-11256361%3Fpid%3D1321540359) for full log file.

IDS gives her a green thumbs up for all uploads, so she had no idea that her uploads weren't working. She just happened to mention to me that she uploaded files, and I thought I would check on them. I know it is difficult for IDS to report on server-side issues, but is there any way we could somehow improve this? Other than a few suspicious lines in her log file (which most users never check), its impossible to see that the uploads didn't in fact go through.

**Comment by Shannon-Dubay** [comment]
UPDATE:
This same user (Stephanny) is also experiencing issues in the "Validate" tab of Reco- when pressing "Assimilate Matches", nothing happens. I believe this is linked because no one else is having this problem within Reco (although there are plenty of other reco problems (see #187), but these users are able to pass this step with no problem.

She posted about the inactivity problem [here](https://pantheraids.org/forum.html?p=post%2Fit-doesnt-validate-11255200%3Fpid%3D1321541367). See post for log file- there are similar errors written in it as the above post.

This is again using the latest IDS version, and I have confirmed that she is following all the correct steps to log into the server, and IDS is showing her all the indications that she is indeed connected to the server.

**Comment by RossPitman** [comment]
Can we please ask her to try upload something small? Perhaps a folder with about 10 images, just so we can determine whether there is some file format issue we've not detected before.

**Comment by Shannon-Dubay** [comment]
I have asked via email now.

**Comment by Shannon-Dubay** [comment]
She has just uploaded 6 images (S3110_20130307_20130822), and everything looks fine within IDS, but you can see lots of errors in her log file, and her upload isn't seen on S3.

![20201118_104714](https://user-images.githubusercontent.com/48274721/99564986-cd0dbd00-29d3-11eb-8127-2256751b9fd3.jpg)

[shiny-server-shiny-20201118-163705-44467.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5561665/shiny-server-shiny-20201118-163705-44467.log)

**Comment by Shannon-Dubay** [comment]
She has also sent the files for recreating her problem with Generating a Reference Database within Reco, which was mentioned in a comment above. I tried to recreate the problem and also get an error.
I am creating a new github issue for this: GitHub Issue #195

**Comment by RossPitman** [comment]
I forgot to add the requisite permissions to her profile. My bad. It's done now. Waiting to hear if she is able to upload now.

**Comment by Shannon-Dubay** [comment]
User was able to upload successfully- thanks!
this can be closed now and marked completed on TG
