### ISSUE TITLE
Data Processing/Machine Classifier - not able to run using external location

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#189]
When attempting to machine classify using "external images", the machine classifier immediately gives the popup: "Warning: A problem was encountered when trying to run the machine classifier." and a red thumbs down saying "Error: Classifier failed to run". version 2.28.899 latest.

For the last year or so, this module was set up so that the user should highlight the parent folder of the survey folder where their images are stored (as should be standard throughout IDS now). However, just to check, I tested it by highlighting the survey folder, and my highlighting the parent folder to the survey folder- neither worked.

I tested using a local database, and I believe all users that have experienced this problem were also using local databases.
I experienced this while TeamViewering into Chantae Guy's computer, and Emma mentioned it separately via email. Her words: _"I discovered that although there is the option to run machine classifier with images on an external volume, MC kept failing. I had to place a copy of the images in the C drive [ids_volume directory] for it to work."_

When trying on my mac, the log writes the following when I click "Run":

> Error in paste0(mchn_clssfr_dir_choice$img_dir, "/", tbl$SiteID[1], "/images/") : 
  object 'mchn_clssfr_dir_choice' not found
> sh: 1: Syntax error: "(" unexpected
> Warning in system2(command = py_lctn, args = args, stdout = TRUE) : 
> running command ''/anaconda3/envs/tensorflow1.12.0/bin/python' '/srv/shiny-server/custom/machine_classifier/main_prediction/predict.py' -image_dir Error in paste0(mchn_clssfr_dir_choice$img_dir, "/", > tbl$SiteID[1], "/images/") : 
  object 'mchn_clssfr_dir_choice' not found
> -results_file '/ids_volume/data/predictions/S16_20181009_20181018_empty_vehicle_species_2020.11.09_17.23.csv' -model_path '/srv/shiny-server/data/models/southern_africa/empty_vehicle_species/model.hdf5' -pre_processing_json '/srv/shiny-server/data/models/southern_africa/empty_vehicle_species/image_processing.json' -class_mapping_json '/srv/shiny-server/data/models/southern_africa/empty_vehicle_species/label_mappings.json'' had status 2

**Comment by RossPitman** [comment]
Can you please send me the local database that you tested on, and the images as well. I'd like to try reproduce this. Thanks!

**Comment by RossPitman** [comment]
There was an error in a small function. Fixed it now.

**Comment by RossPitman** [comment]
Found the bug with the above issue, but discovered another (classifier not working at all). Probably due to the new way to use git.

**Comment by RossPitman** [comment]
Fixed. It was a false error.
