### ISSUE TITLE
Data Processing/Manual Identification - Secondary panel image metadata not showing for server-based databases

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#190]
Image metadata isn't showing in the Secondary panel (see screenshot) when dealing with server-based databases. Latest IDS version - 2.28.899 alpha. Forum post [here](https://pantheraids.org/forum.html?p=post%2Fmanual-identification-match-secondary-to-primary-button-10273617%3Fpid%3D1321542796).

![Screenshot 2020-11-10 at 12 14 59](https://user-images.githubusercontent.com/48274721/98662080-f08b9480-234f-11eb-836b-bd461f782fc3.png)

It is not a case of missing information- it is a case of the information not being displayed properly. The Primary panel is working fine and showing all metadata. Also, all metadata in question shown when looking at the database in Tables Module. 

When testing, I found that some databases worked and some didn't- and it even varied between images within databases. All images tested from the server. Databases from the server had the issue; local databases appear fine.

S27_2019 and S3034_2019 (both from server) didn't work for any images. 

S4_2017 (from server) had only some images work.

> Individual = Female 123 (S4_2017), some of her images' metadata showed (i.e. S4__Station3__Camera2__CAM44136__2017-08-31__19-08-12.JPG), while others didn't (S4__Station3__Camera1__CAM40849__2017-08-31__19-08-25.JPG & S4__Station4__Camera1__CAM40658__2017-07-28__23-12-52.JPG)

**Comment by Shannon-Dubay** [comment]
Note to self: Lauren also posted about this problem [here](https://pantheraids.org/forum.html?p=post%2Fsecondary-image-metadata-missing-11270966%3Fpid%3D1321639021)

**Comment by kacoster** [comment]
Fix Applied
