### ISSUE TITLE
Data Processing/Identified Individuals Bulk Image Exporter - only exporting reference images, not all images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#191]
Even with the "Reference Images Only" setting set to "No", the export only exports reference images (exactly the same output as when I put "Yes" for that setting). v2.28.899 alpha.

Appears to only effect server-based databases.

Problem with: 
S27_2019 (database=server, images=server)
S1_2017 (database=server, images=local)
S4_2017 (database=server, images=local)
S4_2017 (database=server, images=server)

No problem with:
S4_2017 (database=local, images=server)
S4_2017 (database=local, images=local)

*Also*- while in the code, please can the default/pre-loaded setting for "Reference Images Only" be changed to "No". Thanks!

**Comment by Shannon-Dubay** [comment]
Lauren also discovered this issue today- Shannon to inform her when the fix is available.

**Comment by RossPitman** [comment]
Fixed.
