### ISSUE TITLE
Data Analyses/Occupancy (single season) - Manually provided grid files not working

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#193]
Hugh posted on the [forum](https://pantheraids.org/forum.html?p=post%2Fgenerate-occupancy-grid-error-disconnected-from-server-11263256%3Fpid%3D1321571142) about troubles running single season occupancy with providing his own grid files.

Phil: "Seems the UTM grid files are not working for costa rica, the only way I could get it to work is to project the user's input grid to WGS 84 - EPSG:4326."

Help file will need to be updated- Shannon and Phil to schedule a call to quickly go over the information that needs to be added to the help file, OR Phil to send Shannon a few sentences to add in... whichever is easiest.

Also- High mentions [here](https://pantheraids.org/forum.html?p=post%2Foccupancy-help-files-10622912%3Fpid%3D1321571232) about a popup that doesn't disappear- making it almost impossible to click the button beneath it. The settings for this popup just need to be changed so that it behaves like all the others :)

**Comment by RossPitman** [comment]
UTM grids aren't supported.
