### ISSUE TITLE
Data Analyses/SCR from database - Bayes output files not created

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#194]
In order to update Help Files, I ran bayes SCR (took about 8 hours), and it looks like it finished successfully... it shows the output in the bottom panel on the page... but I can't find the actual file outputs.

According to the previously written help files, they are supposed to be written to ids_volume/data/database/SurveyFolder, but I'm not seeing them there. **However**- I don't have a SurveyFolder in that location, so perhaps that is the problem (IDS was looking for the survey folder, which doesn't exist, so it just didn't write any files?)

I have checked all possible folders, including the Downloads folder, and I can't find the output files. There was no popup to download (not sure if there should have been?)

This was running S5_2019 from the server, without removing any individuals, and keeping all default settings. Version 2.28.899 alpha. Nothing written into log file.

**Comment by Shannon-Dubay** [comment]
Suggestion: GitHub Feature request [92](https://github.com/pantheracorp/PantheraIDS_Features/issues/92) might be able to be accomplished at the same time as fixing the above.

**Comment by RossPitman** [comment]
Was the log file completely empty, or just nothing relating to this error?

**Comment by RossPitman** [comment]
For some reason, shiny now only writes to the log file if it's open. So during testing, please start IDS then open the log file immediately. That way data will be written to the log file and we could hopefully figure out this issue.

**Comment by RossPitman** [comment]
@PhilipFaure – not urgent, but when you get a chance, do you think to might be able to check to see if IDS writes the database directory it doesn't exists? If not just let me know and I'll try get to it. Thanks

**Comment by Shannon-Dubay** [comment]
"For some reason, shiny now only writes to the log file if it's open. So during testing, please start IDS then open the log file immediately. That way data will be written to the log file and we could hopefully figure out this issue."

-Gosh, thats pretty bad.... it means I can never request a log file from a user posting on the forum about an issue!

**Comment by RossPitman** [comment]
Bayes exports are generated and the download option is provided to the user.
