### ISSUE TITLE
Data Processing/Reco/Validate Tab - Unable to Generate Reference Database

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#195]
Stephanny, in addition to having issues uploading data to the server (see GitHub Issue #188 ), is unable to generate reference database in validate tab of Reco. 

She has recently posted her regular database and recognition database to the [forum](https://pantheraids.org/forum.html?p=post%2Fit-doesnt-validate-11255200%3Fpid%3D1321541367) (against my recommendation) so that we can recreate the issue. She is working in central america (so centralamericahub was used), IDing Jaguars.

When recreating this issue, I see the same red thumbs down error that she does, which says "Failed to generate site inclusion statistics". Attached is my log file.
[shiny-server-shiny-20201118-174306-33165.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/5562007/shiny-server-shiny-20201118-174306-33165.log)

**Comment by RossPitman** [comment]
I get this error in my log when using her data:
`Error in .f(.x[[i]], ...) : object 'X' not found
Error : Column `value` can't be converted from character to list`

**Comment by RossPitman** [comment]
We have noted that the potential cause of this error is the lack of data (for this particular SiteID) on the server. Since Reco now generates an individual reference database on the fly from the server, IDS must know where the stations are located for this particular SiteID. Hence, the data for this SiteID must be uploaded first.

**Comment by Shannon-Dubay** [comment]
Error is most likely due to the fact that the data for "S3110_20130307_20130822" is not yet on the server. 

I have uploaded her data to the server. 
Upon my first attempt, I got the following warnings/errors: 
<img width="1163" alt="Screenshot 2020-11-20 at 18 39 38" src="https://user-images.githubusercontent.com/48274721/99825716-11c65f00-2b60-11eb-8c8f-c25ef883f7b7.png">
<img width="1028" alt="Screenshot 2020-11-20 at 18 42 25" src="https://user-images.githubusercontent.com/48274721/99825777-26a2f280-2b60-11eb-8bd5-b470803b1a61.png">

But my second attempt appeared successful. I can load the database into the Tables Module from the server (which is typically my check to ensure upload was successful). 

It is ready for the second attempt at step-by-step (line-by-line?) testing.

**Comment by Shannon-Dubay** [comment]
> We have noted that the potential cause of this error is the lack of data (for this particular SiteID) on the server. Since Reco now generates an individual reference database on the fly from the server, IDS must know where the stations are located for this particular SiteID. Hence, the data for this SiteID must be uploaded first.

Just reminder: from our phone call we also determined that IDS searches for the site ID within the server in order to compile Station information, however IDS should look for **survey ID** so that the dataset from that site AND that year are required to be on the server.

**Comment by RossPitman** [comment]
Thanks, can we add the above as a new GH feature please. When you get a chance. Thanks!

**Comment by RossPitman** [comment]
Hmm, her data are plotting in Antarctica...
![Screenshot 2020-11-20 at 19 06 49](https://user-images.githubusercontent.com/15226110/99828443-9ebee780-2b63-11eb-97ad-1a9649f50775.png)

**Comment by RossPitman** [comment]
Seems her X and Y columns are switched in the original local databases. How do folks still get this wrong?

**Comment by RossPitman** [comment]
I suggest we switch the X and Y columns in the trggr_tbl and camact, then re-upload. Will also need to delete the data just uploaded to Redshift.

**Comment by RossPitman** [comment]
Hey @Shannon-Dubay – just following up on this? Will you be able to update the database and re-upload to Redshift, or do you want me to do it?

**Comment by RossPitman** [comment]
FYI I'm going to fix the database on my end and push to Redshift.

**Comment by RossPitman** [comment]
X and Y fixed.
![Screenshot 2020-11-23 at 11 33 51](https://user-images.githubusercontent.com/15226110/99946891-cbe7e180-2d7f-11eb-98e8-58af9b97146f.png)

**Comment by RossPitman** [comment]
Original issue is now fixed once data were uploaded to the server.
