### ISSUE TITLE
Data Processing/Manual Identification - Tag/Untag/Save Reference Images buttons are unresponsive

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#196]
From Lauren via the [forum](https://pantheraids.org/forum.html?p=post%2Ftag-buttons-not-working-11269178%3Fpid%3D1321623109):

"_Just wanted to let you know that the tag/untag/save tag buttons aren't working in the new IDS V2.28.899. They appear within the little metadata component, however when clicking to tag a reference image, nothing happens. This is when working from server-based databases and server-based OR local images._"

Most likely linked to previous GitHub Issue #175 and GitHub Feature [83](https://github.com/pantheracorp/PantheraIDS_Features/issues/83).

**Comment by kacoster** [comment]
Fix Applied
