### ISSUE TITLE
Data Processing/Process Images - nothing happens when applying timeshift (data specific)

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#198]
Users report that restructuring images occurs successfully, the camera active loads in and all graphics load correctly, but when loading in timeshift and trying to apply, IDS remains inactive (nothing happens). Phil and I both experienced this back in Feb 2020 when training Marike and Marine, but due to time constraints, we used a work around. We interrogated the timeshift sheet and could see nothing that would cause the problem. 

This is an issue that has been experienced a few times over the last year- and each time I am unable to determine the issue. The issue typically gets worked around by the user using a different file or a different computer or even just restarting their computer.

Sara recently posted this to the [forum](https://pantheraids.org/forum.html?p=post%2Fproblem-applying-timeshift-10423631%3Fpid%3D1321618732), following up from Marike's unexplained experience with this problem back in late March. 

"_Images have been loaded, but when I go to apply the timeshift, nothing happens. I updated IDS this morning_ [v.2.28.899] _, and tried restarting my computer, to no avail._"
Her log file is attached: [shiny-server-shiny-20201117-234855-35523.log.txt](https://github.com/pantheracorp/PantheraIDS_Issues/files/5572004/shiny-server-shiny-20201117-234855-35523.log.txt)

I have looked at her CA and TS sheet and do not see any mistakes; attached below. She has also provided her images so we can attempt to recreate the problem- found on S3 (uploaded through the Data Uploader module) under Unstructured/Sara/Raw_Images. User reports there should be 917 images. 

[Olympic_CA_and_TS_csvs.zip](https://github.com/pantheracorp/PantheraIDS_Issues/files/5572030/Olympic_CA_and_TS_csvs.zip)
(VERY ANNOYING THAT YOU CAN'T ATTACH CSVS HERE)

Additional information via the forum:
"_It appears that I'm unable to archive even if I don't apply a timeshift. The only action button that will work is "process", beyond that, I can't do anything. I've tried updating IDS and restarting docker, but can't make any progress._"

**Comment by RossPitman** [comment]
How did you inspect the CSV files? In Excel?

**Comment by Shannon-Dubay** [comment]
In excel and a text editor

**Comment by RossPitman** [comment]
In the text editor have you also seen this? The whitespace within the "Sign" column. This might be prevent IDS from proceeding since it's looking for "Sign" but finding "Sign ". Excel would normally miss this.
<img width="1529" alt="Screenshot 2020-11-20 at 10 40 43" src="https://user-images.githubusercontent.com/15226110/99782878-66e38000-2b22-11eb-9a3b-b1685cc7f524.png">

**Comment by Shannon-Dubay** [comment]
Jeez... no, I missed that. I was looking for extra rows or columns, and that it was comma separated. I will tell her to remove the space and try again

**Comment by RossPitman** [comment]
Do we have an update on the status of this issue?

**Comment by Shannon-Dubay** [comment]
I have asked the user to try again, but have heard nothing back. I will follow up.

**Comment by Shannon-Dubay** [comment]
Update: She has removed the space and it still doesn't work.

**Comment by RossPitman** [comment]
Very difficult to assess what the issue is here without having her raw data. Not sure what to do? Should we request her data, or ask to TV into her computer whilst she tries (not ideal)?

**Comment by RossPitman** [comment]
Her X and Y coordinates were switched. IDS didn't report this error, but now it does.

**Comment by Shannon-Dubay** [comment]
Thank you Ross, I didn't realize that switching the X and Y coordinates could result in an actual error with IDS, so I have never checked for that. Thanks for spotting that and letting me know!
