### ISSUE TITLE
Data_Processing/Timeshift Calculator

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#2]
The "Earlier Date-Time" only go to Year 2000 to the earliest (in cases of cameras resetting timeshift prior to 2000)

**Comment by RossPitman** [comment]
What earliest date do you suggest?

**Comment by JoleenBroadfield** [comment]
Had 1992 on one of the sites, not sure if other date earlier than that have been encountered, maybe let's settle on 1990 for now ?

**Comment by RossPitman** [comment]
OK, updated to 1990 for now.
