### ISSUE TITLE
Data Explorer/Descriptive Statistics

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#20]
Hi,

 When trying to use Descriptive Statistics. I get the following error on the console and the program freezes:
Source: "C:\Users\Roberto\Documents\PANTHERA_R\PantheraIDS\app\data\maps", layer: "time_zones"
with 418 features
It has 1 fields
Error in mutate_impl(.data, dots) :
  Evaluation error: el argumento "tz" est<e1> ausente, sin valor por omisi<f3>n.
Warning: Error in UseMethod: no applicable method for 'select_' applied to an object of class "try-error"
  89: select_
  88: select.default
  86: function_list[[i]]
  85: freduce
  84: _fseq
  83: eval
  82: eval
  80: %>%
  79: func
  78: origRenderFunc
  77: output$dt_explrr_lineBar_4_clss
   1: shiny::runApp
Warning: Error in mutate_impl: Evaluation error: el argumento "tz" est<e1> ausente, sin valor por omisi<f3>n.
  93: <Anonymous>
Warning: Error in mutate_impl: Evaluation error: el argumento "tz" est<e1> ausente, sin valor por omisi<f3>n.
  93: <Anonymous>

**Comment by RossPitman** [comment]
@rsalom – is this problem still persisting? If so, can you please send me a database so I can try reproduce the issue. Thanks!

**Comment by rsalom** [comment]
@RossPitman I don´t think so. Thanks.
