### ISSUE TITLE
Check all scripts for text not added to translate.json...for the 4th time.

### ISSUE THREAD

**Issue by PhilipFaure** [pantheracorp/PantheraIDS_Issues#200]
Despair.

**Comment by RossPitman** [comment]
We need to have a rule that whenever we add or modify any text strings, that person must also add it to the translation file. I’m the culprit in most cases at the moment, so sorry about that, I’ll do better!

**Comment by RossPitman** [comment]
That is the translation file called and where is it stored?

**Comment by RossPitman** [comment]
Please also divide some of the modules and give them to me, so I can help. I’ll spend time on it Monday, just tell me the module to work on. Thanks

**Comment by RossPitman** [comment]
@kacoster - would you be able to assist if possible? Just for a day? We need to get this translation file updated, and I think it’s a lot of work for 1 person.

**Comment by RossPitman** [comment]
@PhilipFaure - we want to be using the new git workflow. Let me know if you’ve started on this yet and whether you need some guidance?

**Comment by kacoster** [comment]
@RossPitman No worries at all. I will get in touch with @PhilipFaure and get started.

**Comment by PhilipFaure** [comment]
Hi @RossPitman and @kacoster - Thank you for your response and assistance! I really really appreciate it. I have started a hotfix for this issue entitled: 'pf_issue_200'. I will work throughout tonight and then update everyone as to how far I have gotten by Monday. Thank you for your help on this!

**Comment by PhilipFaure** [comment]
translations.json is found in ./helpers/translations.json - Currently it does not have a slot for Arabic, but this is not an issue, I have some code which will pull the json into a csv and then I can just manually add a column in and format it back to a json file.

**Comment by PhilipFaure** [comment]
Completed scripts from: ./body/server/. for the following modules:
blk_dt_exprt_*
blk_img_exprt_*
ct_body_srvr_*
ct_vldt_*
ctfm_*
dcmnttm_body_*
dt_explrr_*
dt_upld_*
gnrt_mnfst_*
img_clssfctn_*
img_crpr_*
indpndnt_cptrs_*
mchn_clssfr_*
rdshft_*
rfrnc_indvdls_*
s3_*
sie_mngmnt_*
spcs_idntfctn_*
spcs_mngmnt_*
tmshft_*

Need to still look into scripts:
ct_occpncy_*
ct_secr_*

**Comment by PhilipFaure** [comment]
Surely there must be a more efficient way. Though I can't seem to get this regex code correct:

```
# Read test R files
r_scripts <- list.files(
  path = "/Users/DataScience/Development/test",
  pattern = ".R",
  recursive = TRUE,
  full.names = TRUE
)

# Turn R files into text files so they can be read into R easily.
# Make new file names
new_r_scripts <- sub(pattern="\\.R$", replacement=".txt", x=r_scripts)

# rename files
file.rename(from = r_scripts, to = new_r_scripts)

# Read all the text files into R.
scripts <- lapply(new_r_scripts, function(x)readChar(x, file.info(x)$size))

# turn the list given from the above function into a vector
script_vector <- unlist(scripts)

# look for 'translate$t(' at start and ')' at the end
stringr::str_extract_all(
  string = script_vector, 
  # pattern = 'translate\\(\\)\\$t\\([[:alpha:]]+\\)'
  pattern = '(?<=(translate\\(\\)\\$t\\()[[:alpha:]]+(?=\\)'
  # pattern =  '(?<=(translate\(\)\\$t\()[[:alpha:]]+(?=\)'
  # pattern =  '(?<=(translate\\(\\)\\$t\\()[[:alpha:]]+(?=\))'
  # pattern =  '(?<=(translate\\(\\)\\$t\\()[[:alpha:]]+(?=\\)')
  # pattern = '(?<=(translate\\(\\)\\$t\\([[:alpha:]]+(?=\\)'
)

```

**Comment by RossPitman** [comment]
What rules/logic are you trying to identify? Just scanning over this I think you’re looking for translate...

**Comment by RossPitman** [comment]
But that may not be what you want. Since some scripts won’t even have translate. So what do we know? For instance, can we always expect to have translate every where where paste() occurs? Or is that logic flawed?

**Comment by PhilipFaure** [comment]
Hi @RossPitman - I did not explain properly, the part which takes the longest is copying and finding the text strings from the scripts into the translate.json file. Most of the time people wrap text with the translate function, and when it isn't it's only a few, and quick to add. But copying and pasting the text string into the json file and seeing if it already exists or not, takes quite long. Basically, one has to copy the text for each and then each time try find/search it in the json, cause I wouldn't know if someone changed it (even just a little bit from the previous text).

Therefore, I was hoping to check all the scripts for text missing the translate function (manually), and then after, extract the text between the `translate$t( ... )` brackets (regardless of whether there is a `paste0` function inside the `translate()$t(...)` function) for all scripts and pasting it to a dataframe to then anti-join to a dataframe with the translations text to see which one's are missing. Then the missing one's can be copied and pasted all at once.

**Comment by PhilipFaure** [comment]
All scripts are checked Thanks @kacoster for going through all the SECR scripts and adding missing text, much appreciated! Thanks All, for the quick assistance, very, very much appreciated!

Closing issue.

**Comment by RossPitman** [comment]
Jeez guys (@kacoster @PhilipFaure ), sorry, I didn't mean for the work to be completed over the weekend. Please feel free to take a day off sometime during the week/month to compensate. Thanks for the huge effort though! Impressed!
