### ISSUE TITLE
MAIN-35 ⁃ Data Processing/Bulk Data Exporter - User not able to export some databases (but I can)

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#203]
Forum [post](https://pantheraids.org/forum.html?p=post%2Fbulk-data-export-disconnect-10468020%3Fpid%3D1321666237):
Jo is able to export some data, such as S3044_2018, but not others, such as S3034_2019. She says IDS crashes. However, I am able to export the ones she is not able to (i.e. S3034_2019).
All these exports are using server-based databases, version 2.28.923. 

Thoughts? Could this be a permissions issue?

She also reports having missing log files a lot (including when she tries to complete these exports); these issues might be linked somehow? Perhaps the folders aren't "sharing" in Docker as they should? User is on a mac, so Docker Desktop.

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-35) by [Unito](https://www.unito.io)

**Comment by RossPitman** [comment]
It may be a permissions issue, will have to investigate. Re log files – remember that IDS doesn't write to log files unless the log file is opened. It will disappear if not opened. Not idea how to get around this.

**Comment by Shannon-Dubay** [comment]
Update: Jo repoerts that she wasn't able to export S5_2017, but she was able to export same survey but different year (S5_2014), which is obviously all under the same hub and site.

**Comment by Shannon-Dubay** [comment]
Update: When she encounters this issue, IDS crashes completely (crashes before having the window to download data).
She is currently running alpha 4.32.955, and upon her last attempt kept her log open so that the file remained. See attached file. See latest forum post ([here](https://pantheraids.org/forum.html?p=post%2Fbulk-data-export-disconnect-10468020%3Fpid%3D1321739802)) for log file.

**Comment by Shannon-Dubay** [comment]
Joleen has updated her original forum [post](https://pantheraids.org/forum.html?p=post%2Fbulk-data-export-disconnect-10468020%3Fpid%3D1321791358) to include that she can't export S25_2016 data either. She needs the Camera active exports to manually run analyses.
