### ISSUE TITLE
Data Processing/Process Images - in "Archive Data" tab, the "Browse to external directory" should disappear if not using it

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#208]
When "Archive Images in External Directory?" is set to "No", the "Browse to external directory" setting should not be shown... as many other modules do.
![Screenshot 2020-12-08 at 00 00 51](https://user-images.githubusercontent.com/48274721/101410766-7e738480-38e8-11eb-8f18-ac78bbc5b377.png)

┆Issue is synchronized with this [Jira Task](https://pantheradatascience.atlassian.net/browse/MNTNNC-9) by [Unito](https://www.unito.io/learn-more)

**Comment by PhilipFaure** [comment]
Done

<img width="1182" alt="Screenshot 2021-01-19 at 09 44 08" src="https://user-images.githubusercontent.com/24668143/104993003-925beb80-5a3b-11eb-8c41-928976941fb4.png">
<img width="1177" alt="Screenshot 2021-01-19 at 09 44 02" src="https://user-images.githubusercontent.com/24668143/104993008-9425af00-5a3b-11eb-9c75-2e827578da93.png">

Closing issue.
