### ISSUE TITLE
MAIN-33 ⁃ Data Explorer/Descriptive Stats/Report tab - report not downloading

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#209]
Marike has reported via the [forum](https://pantheraids.org/forum.html?p=post%2Ffailing-to-download-individual-capture-locations-11319591%3Fpid%3D1321908205) that she gets a "Failed - Server problem" error in her downloads bar when attempting to download the report. She has only included "Individual capture locations" in the tabs of what to include the report. She claims to have strong internet connection for the time being. 
v.4.32.955, alpha
Her log file is attached to her forum post, which includes interesting error messages.

Upon testing myself, I was able to successfully download and open a report for S17_2020 (the database she is trying to use) while on the southernafricahub schema, and the same version as her. My log file does not contain any of the errors hers mentions. Excerpts from her log file are below- any idea why she would have these and not me?:

Error in names(out) <- c("id", "attribute", "value", "userinput", "datetimeinput") : 
  'names' attribute [5] must be the same length as the vector [4]
Error in UseMethod("drop_na_") : 
  no applicable method for 'drop_na_' applied to an object of class "try-error"
Warning: Error in UseMethod: no applicable method for 'drop_na_' applied to an object of class "try-error"
  [No stack trace available]

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-33) by [Unito](https://www.unito.io/learn-more)

**Comment by Shannon-Dubay** [comment]
also, just to mention, the text that accompanies the individual capture locations is still the latin filler, which isn't good if she's trying to export a report for the Welgevonden (S17) managers (I know they like to be updated often and thoroughly)

**Comment by RossPitman** [comment]
We won't be working on any reporting within IDS until we find a staffing solution.
