### ISSUE TITLE
Data Explorer/Maps

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#21]
When making a query on captures of one species, you can barely see the purple circle below the Station. Maybe instead of adding a purple circle the Station globe can change color???

![image](https://user-images.githubusercontent.com/44848642/55415912-22f5ce80-552b-11e9-9530-e8032f504467.png)

**Comment by RossPitman** [comment]
Would it not be useful to simply have the ability to toggle the blue markers?

**Comment by rsalom** [comment]
Do you mean turn them off? If so, yes I think that is useful. But what if you are interested in seeing the stations where they were not detected. Could you have an empty circle for those stations?

**Comment by Shannon-Dubay** [comment]
Just something to be aware of if you are working within the Data Explorer module, @PhilipFaure ... not even sure if this is still relevent, can you please confirm Phil? Thanks!

**Comment by PhilipFaure** [comment]
Currently the map explorer does not show empty circles. It only shows circles for trapping effort, relative capture index, & n captures. The user is able to toggle all of these layers, including the blue markers for where stations are located. So the user is able to see where species were captured and where they weren't. The user is also able to enlarge the circle markers if they are too small and can't be seen behind the blue markers.

**Comment by PhilipFaure** [comment]
Closing issue.
