### ISSUE TITLE
Data Processing/Recognition - Change name of grpd dtbss

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#212]
Back in 2020, we realized that teams may put multiple species through Reco, so the recognition and grouped databases needed to be better distinguished. We first attempted a system in which the database files had a suffix of the date and time, but this wasn't helpful because each edit made resulted in a unique file. 
In the end we changed the naming format to include the species name instead of the date/time. See closed GH Issue #134 for more details including Phil's naming format. This format has been working very well. 

However, the grouping databases still have the date/time suffix, and need to be switched to the same format as the recognition databases have. See Marikes post on the forum about it [here](https://pantheraids.org/forum.html?p=post%2Fmultiple-grpddtbss-files-in-the-database-folder-in-docker-11349196%3Fpid%3D1322149126), including a screenshot of all the grouped database files on her computer.

**Comment by PhilipFaure** [comment]
Done. PantheraIDS will now rename grpd_dtbs.Rdata files as grpd_dtbs_<species name>.Rdata instead of using the datetime  

[Click to view code changes.](https://github.com/pantheracorp/PantheraIDS_v2/commit/d45aceda28193cb6ac5cdff907bba691c1e313f1)

Closing Issue.
