### ISSUE TITLE
MAIN-31 ⁃ Hub selection keeps resetting and dropping server connectivity

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#214]
This is a weird one. I cannot recreate the issue, but I have seen it happen to Hannah and Lauren's IDS sessions. Both using the latest version of IDS (v.4.32.1026).

They successfully sign into the server and select their regional hub, and the connectivity icon at the top right of IDS turns green. All seems well. But, they only remain connected to the server for about 30 seconds or 1 minute (haven't timed it) before a quick status popup shows in the bottom right of IDS (its too fast to see what it says), then the hub selection changes from their hub to no hub. The connectivity icon at the top remains green throughout the entire time. They are unable to continue with any work that requires server connectivity, and the result is a lot of red thumbs down error messages in their modules.

However, if they simply re-select their hub, they can carry on with their tasks right where they left off. 

At first I assumed it was the result of unstable internet, I got suspicious when both Hannah and Lauren experienced it. That being said, I don't think either of their internets are amazing quality.

┆Issue is synchronized with this [Jira Bug](https://pantheradatascience.atlassian.net/browse/MAIN-31) by [Unito](https://www.unito.io/learn-more)

**Comment by RossPitman** [comment]
Sounds like an issue related to the server connection feature. @kacoster can you please look into this at some point?

**Comment by Shannon-Dubay** [comment]
This is the section that changes from their hub to no hub selected (forgot to attach to original post): 
<img width="222" alt="Screenshot 2021-01-06 at 15 29 35" src="https://user-images.githubusercontent.com/48274721/103776376-09ef4b00-5038-11eb-89b9-75c86f8a588f.png">

**Comment by kacoster** [comment]
I have been trying to recreate and follow this issue with no luck. Could this be only experienced on non-admin users? @RossPitman any possibility of having non-admin credentials to use for this?

**Comment by Shannon-Dubay** [comment]
Yes, I have been using IDS quite a lot and have not experienced this once- I only saw it when TeamViewer-ing into Hannah's computer.

________________________________

**Comment by Shannon-Dubay** [comment]
Posts on the forum regarding this issue: 
Emma and Joleen [here](https://pantheraids.org/forum.html?p=post%2Fserver-disconnection-11268320%3Fpid%3D1322237494)
Lauren and Hannah [here](https://pantheraids.org/forum.html?p=post%2Fgetting-kicked-off-of-server-11360359%3Fpid%3D1322245556)
