### ISSUE TITLE
View of image cut off

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#23]
In the identification->manual identification module, the images that appear under the primary and secondary spaces are cut off on the right hand side (at least for my screen, on the orange laptop). This is still the case when collapsing the left hand menu column. The only way to see the entire image is to open it in a new tab. When in a new tab, you can see the image actually has more to it than you can see on the manual identification screen- important to know for those maybe working on a smaller laptop in the field.

**Comment by RossPitman** [comment]
This isn't something we can fix at the moment, and depends on the users screen resolution. IDS attempts to auto-size the image to fit, which means some parts get cut off.
