### ISSUE TITLE
HPg_DtPrcssng_ProcessImages_SurveyDetails

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#25]
When clicking on "Click for Help" new page in web browser opens but says "Not Found".

Feel there is a broken link in IDS script itself for that tab, let me know, happy to correct !

**Comment by RossPitman** [comment]
You've fixed this now I take it.

**Comment by JoleenBroadfield** [comment]
Correct !
