### ISSUE TITLE
HPg_DtPrcssng_Export_BulkDataExport

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#27]
When clicking on "Click for Help" a new page opens in web browser, though it's a new IDS Login page.

Also feel it's a broken link in IDS script for that tab, let me know if I can amend myself

**Comment by RossPitman** [comment]
Working working on this I take it.

**Comment by JoleenBroadfield** [comment]
Correct !
