### ISSUE TITLE
IDS_nomenclature "identification.csv"

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#28]
The same word, "Identification.(csv)" is use for 2 differents csv : 

- csv generated from identifying individuals (Reco module + user manual input), name mentioned in DataAnalysis_SCR_Manual.
- csv generated from analysis (SCR), name mentioned in DataProcessing_Identification_Merge Identification.

The later csv is automatically called "...._complete_ids.csv" when generated by IDS, I suggest the second csv to be called "CompleteID".

P.S: Regarding the title above automatically given "...._complete_ids.csv", to avoid confusion, should it perhaps be called ".....complete_id.csv" ?

**Comment by RossPitman** [comment]
Yes please go ahead and change these if you're comfortable? Then close once complete.
