### ISSUE TITLE
Data Processing/Camera Trapping/Classifications/Classsify: Species in wrong project

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#3]
I see several species that are included in the wrong project: 
-Leopard Program has: Brocket (already inlcuded in Jaguar Project as Deer_Red_brocket), Armadillo ((already inlcuded in Jaguar Project as Armadillo_Nine_banded), Ocelot, Cacomistle, Coati_white_nosed, Margay_oncilla (already included in Jaguar Project as Margay), Opposum_common, Opposum_small, Peccary (already included in Jaguar Project as Peccary_collared and Peccary_white-lipped), Rabbit_tapeti, Raccoon_common, Tamandua_Northern, Tapir_Baird, Tayra.

All of the above are included in the Jaguar Project already with the same name, with the exception of the ones indicated above.

**Comment by RossPitman** [comment]
I'm looking into standardising these further. 

@JoleenBroadfield – should we be considering a more standardised, internationally accepted, taxa format? I'm not sure which way we should go here, or whether it'll make life easier.

**Comment by RossPitman** [comment]
Implemented.
