### ISSUE TITLE
F2 shortcut not working on certain computers

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#30]
The F2 shortcut used to apply edits to an image when in the classifications module does not work on my laptop anymore (using beta IDS v.1.13.773 with Docker toolbox on Windows Home). However, it does currently seem to work on the leopard_pc (using alpha IDS v.1.13.771 with Docker Desktop on Windows Pro).

**Comment by Shannon-Dubay** [comment]
Update: F2 shortcut worked on Lauren's laptop (beta IDS v. 1.13.775 with Docker toolbox on Windows Home) this morning. She updated to beta IDS v. 1.13.776, and now F2 shortcut not working.

**Comment by RossPitman** [comment]
Is this part of the Classification module?

**Comment by RossPitman** [comment]
I've reviewed the code and can't see why this would be happening? I suspect it might be a docker issue. Let's monitor it for now.

**Comment by Shannon-Dubay** [comment]
Another change that occurs with it is once the F2 shortcut stops working, the text for the blue 'Apply' button changes from "Apply [F2]" to simply "Apply".

**Comment by RossPitman** [comment]
OK I think I know what the issue is. Will try get to it today.

**Comment by RossPitman** [comment]
Fixed. Will push a new version to Docker Hub soon.
