### ISSUE TITLE
Species names to be changed/added

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#31]
In the species list on IDS the following changes should be made:
Goat_Domestic should be Domestic_Goat
Sheep_Domestic should be Domestic_Sheep
Donkey_Domestic should be Domestic_Donkey
Thanks!

**Comment by Shannon-Dubay** [comment]
Also "Bat_Eared_Fox" should be removed (the correct "Fox_Bat_eared" is already on the list)

**Comment by Shannon-Dubay** [comment]
Technically "Hare_Jamesons_Red_Rock" should be changed to "Rabbit_Jamesons_Red_Rock"

**Comment by Shannon-Dubay** [comment]
Need to add: Baboon_Yellow, Hartebeest_Lichtenstein's, Genet_Miombo for the Zim/Zam sites
And at the moment we have "Grysbok" in our species list, which should be broken down into Grysbok_Sharpe's and Grysbok_Cape.

**Comment by RossPitman** [comment]
Done.

**Comment by RossPitman** [comment]
Feel free to open this again when more species are need etc.
