### ISSUE TITLE
Data Processing/Identification/Recognition - Assign new individual list won't refresh

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#32]
When assigning a new name to a group then save, then load the next group and have to assign also a new name, the naming option doesn't refresh between the 2 actions if both individuals are same gender. 
Note : list do refresh if user selects other gender and re-select initial gender

**Comment by Shannon-Dubay** [comment]
FYI- This is still an issue that I am noticing now on version 1.13.791

**Comment by RossPitman** [comment]
@Shannon-Dubay – When we're both next in the office, please can you show me an example of this not working. I need to see which data sets are used and how it's triggered. I thought I'd applied a sufficient fix for this, but I guess not. I won't work on this until we've done this. Thanks

**Comment by Shannon-Dubay** [comment]
From Gareth Mann on the forum:
When using the 'Assign new individual' function in Reco, it seems to sometimes assign the same numerical identifier to consecutive individuals. For example I had three different groups assigned the name 'Leopard_African_Female_3036_6', when they should have been  females 6,7 and 8. I picked up on this when reviewing the groups, but found that the error kept repeating until I changed the sex - this caused the number to increase to the next one available. I could then change the sex back to female to generate a unique ID for that individual. The same thing happened with male ID numbers as well.

**Comment by Shannon-Dubay** [comment]
This is still an issue-
Naming new individual within the grouping section of reco does not change the number of the newly named individual if you don’t change the sex of the individual. @RossPitman, I can show you an example on Wednesday if you would like.

**Comment by RossPitman** [comment]
Fixed.
