### ISSUE TITLE
IDS Crashing when loading many images consecutively

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#33]
IDS crashes when in reco loading many pages of comparison images repeatedly, even when keeping number of pages relatively low per batch and deselecting between each batch of pages. Feels as though its a memory issue, potentially need a memory dump for each time "de-select" is clicked?

**Comment by RossPitman** [comment]
This is a Docker/SlickR issue. We are looking to fix this by implementing a new image viewer using Viewer.js. Closing for now, but feel free to re-open.
