### ISSUE TITLE
DataProcessing/Data Export - doesn't export to the selected species

### ISSUE THREAD

**Issue by JoleenBroadfield** [pantheracorp/PantheraIDS_Issues#34]
When exporting data (cloud dtbs), using IDS1.13.791, with a selection of species in species tab, the output includes all species and not only the selection of species indicated in species tab. 
FYI tested selecting "Export Unselected", the output is the same as when selecting "Export Selected".

**Comment by RossPitman** [comment]
The spcs_obsrvtn_tbl now only contains the specified species.
