### ISSUE TITLE
Data Processing/Process images: fix popup

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#37]
There are loads of quotation marks in the following popup when processing data, which makes it very hard to read. Obviously not a priority, but will be good to clean this up.

![Capture](https://user-images.githubusercontent.com/48274721/63679973-e042d480-c7f2-11e9-8040-a9a772ca932c.PNG)

**Comment by RossPitman** [comment]
Fixed.
