### ISSUE TITLE
Identifications/Manual Identifications- Button not working

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#41]
Per @JoleenBroadfield via the forum:
It seems the "Match Secondary Image to Primary Individual" don't apply the primary image information to the secondary image (both images were clicked). 
P.S : nor the secondary image information to the primary image, checked in case.

**Comment by RossPitman** [comment]
This issue has been fixed. It will be available in version 1.14.820
