### ISSUE TITLE
Data Processing/Bulk Data Exporter: S14_20160703_20160820 not exporting

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#44]
S14_20160703_20160820 data export only creates trigger and species CSV, but none of the others.
Same result when trying to export on Ross' computer. 
Log says the following: 
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Not Found (HTTP 404).

**Comment by RossPitman** [comment]
Fixed.
