### ISSUE TITLE
dtbs: S27_2018 needs classifications updated on server

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#46]
The classifications on the server are straight from the machine classifier (high number of subthreshold/unclassified, etc.); Shannon has a local dtbs with the correct and verified classifications. Need to use the local dtbs shared on teams, update the timestamp to a recent date/time, then update the classifications on the server with the classifications from the local dtbs.

**Comment by RossPitman** [comment]
Done.
