### ISSUE TITLE
Dtbss having incorrect names

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#47]
It appears that the fix from 20 Sept for the Reference Images having Individual, Gender, and Position as NAs did not fix all the Reference Images. The code was supposed to update the Individual, Gender, and Position information to the most recent information just before being changed to NAs. However, it appears that the code did not work properly for images which historically had a different name to the one it does now (perhaps an ID was updated recently, or individuals were consolidated); images which had multiple names historically had their information updated to its original information, not the most current information. 
Attached is a spreadsheet outlining the issues found in 8 images of S3. It is safe to assume that this has impacted all surveys, all years (not just S3). 
[ForRoss_S3.xlsx](https://github.com/pantheracorp/PantheraIDS_Issues/files/3779417/ForRoss_S3.xlsx)

**Comment by Shannon-Dubay** [comment]
This could also be the cause of the following problem (if not, I will open another Issue in GitHub for it):

Naming issue in S5_2017: seems to be old naming format of: “Leopard_[Sex]_[SiteNumber]_[IndividualNumber]” without the “African” 
- 16 images
- All Position = Left (this is incorrect, about half are right side images)
- All Reference = Yes (this is correct, they are all reference images)
Female 19, Female 31, Female 32, Female 41, Female 59, Female 61, Female 64, Female 65, Female 66, Male 30, Male 4, Male 43, Male 63, Unknown 68

**Comment by RossPitman** [comment]
Regarding point 2 – I found all the old named individuals, but they aren't all reference images. Just FYI
