### ISSUE TITLE
Data Processing/Reco: able to load different sites without error message

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#48]
Able to load dtbs.Rdata and rcgn_dtbs.Rdata files from different sites into reco without any error/warning message- need a check here so that this doesnt happen?

**Comment by RossPitman** [comment]
What is the error/warning message?

**Comment by Shannon-Dubay** [comment]
There is none, thats the concern

**Comment by RossPitman** [comment]
Oh sorry I totally missed that there wasn't a message. Sorry

**Comment by PhilipFaure** [comment]
Closing issue. shinyAlerts have been implemented which will pop up when the user's databases are not from the same survey site.
