### ISSUE TITLE
Data Processing / Manual Identification: Remove Tag

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#49]
When clicking "remove tag" in Manual Identification module (for primary image, not tested for secondary image side), the popup gives a check mark and says "Tagged- Reference Image successfully tagged". It should say "Untagged- Reference Image successfully untagged"
(have checked, and the untagging process does behave as it should, it just has the wrong words in the popup)

**Comment by RossPitman** [comment]
Done.
