### ISSUE TITLE
Data Processing / Bulk Image Export missing exporters

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#50]
Bulk Image Export only has the option to export by identified Individuals... the general bulk image exporter that used to be above the identified individuals is gone?

**Comment by RossPitman** [comment]
This section has disappeared from PantheraIDS' code too, I'll need to chat to Philip to see if it might have been remove whilst applying translations, and then see how best to get it back.

**Comment by PhilipFaure** [comment]
All fixed up, during ui migration I didn't render on the server side...

**Comment by RossPitman** [comment]
Thanks!
