### ISSUE TITLE
Data Processing / Export Independent Captures 

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#51]
The independent captures exports do not have any temporal threshold applied !!! 
This is true for recent exports as well as exports from much earlier in the year (for example, Tembe (S6) in mid-July).

**Comment by RossPitman** [comment]
Please can you provide more info on which site you tried, from computer or server, and then send me the exports (both CSVs) via Teams please? I tried it now on my end with S45_2018 from server, and the exports seem correct (at first quick glance).

**Comment by Shannon-Dubay** [comment]
Humble apologies- it appears that both Gareth and myself have been looking at the wrong files! We were looking at the "SX_XXXX_XXXX_All_independent_records_export_full" spreadsheets accidentally. 
On that note, could we possibly only call the independent sheet "Independent_records_export" and perhaps call the "full" spreadsheet "full_records_export" seeing as how they are not in fact independent? If we are both making this mistake it seems likely that other users will too. Thanks and sorry for the confusion!

**Comment by RossPitman** [comment]
Cool, so lets decide on nomenclature and get Philip to update IDS accordingly.
