### ISSUE TITLE
Data Processing / Manual Identification: Unable to make edits

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#52]
When attempting to change IDs for S3 in Manual Identification I get the following:
-Red thumbs down in IDS with the following message: Failed to push edits to Redshift 
-the following in the log: 
Error in .local(conn, statement, ...) :   execute JDBC update query failed in dbSendUpdate ([Amazon](500310) Invalid operation: Load into table 'cmr_indvdl_obsrvtn_tbl' failed.  Check 'stl_load_errors' system table for details.;)

**Comment by RossPitman** [comment]
This was an issue with the recent translations. Translation were being applied to an area of IDS that shouldn't have been translated. I've reverted the code and tested the edit feature. All working again as of version 1.14.818
