### ISSUE TITLE
Data Processing / Recognition / Merge Identifications

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#56]
Gareth can't merge the identifications in his reco grouping dtbs to his regular dtbs. He is working from a local dtbs, and is trying to use the last step in reco ("Merge Identifications" panel). I am attaching his log here.

[shiny-server-shiny-20191127-075438-46115.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/3905387/shiny-server-shiny-20191127-075438-46115.log)

**Comment by Shannon-Dubay** [comment]
This is still very much an issue, which hasn't been resolved for 2 months and has stalled work on many surveys for Gareth and Lauren... this needs to be prioritized. @RossPitman @pantheracorp

**Comment by RossPitman** [comment]
@Shannon-Dubay – do you have the database file and csv file that Gareth was using so I can replicate this error?

**Comment by RossPitman** [comment]
@Shannon-Dubay – do you have the database file and csv file that Gareth was using so I can replicate this error?

**Comment by Shannon-Dubay** [comment]
@RossPitman he was not using a csv, he completed the IDs using reco in IDS, so he has a grouping dtbs that he is trying to merge with his regular dtbs. I have them both in an email- I will forward these onto you now. (not sure if you want them uploaded here for security reasons?)

**Comment by RossPitman** [comment]
Perfect. Yes, sorry I meant grouped database. Please email the files to me when you get a chance. Thanks

**Comment by RossPitman** [comment]
Ahh no worries, I see the email has just come through. Thanks

**Comment by RossPitman** [comment]
Working on this at the moment. Seems a lot more problematic than first thought, hence the delay in getting to it.

**Comment by PhilipFaure** [comment]
Merging of grouping database and regular database fixed. Closing issue
