### ISSUE TITLE
Missing Position, Sex, and Reference data for 10 surveys

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#58]
Matt alerted me to the fact that there are 10 surveys he has come across that have leopard individuals that have no position, gender, or reference information (NA). They are all varying years, varying sites. One example he showed me was S15_2015, Male 404 (19 images total, only 1 of which has information in the "Position", "Gender", and "Reference" columns), and Male 34 (18 images total, only 2 have information).
"S11_20000101_20170429" 
"S13_20130618_20130806" 
"S15_20150907_20151130"
"S15_20160903_20161025" 
"S15_20170828_20171023"
"S16_20140703_20140825"
"S2_20170203_20170819" 
"S4_20140629_20140812" 
"S4_20170724_20170914"
"S7_20171130_20180118"

Attached is a spreadsheet that Matt created with the csv data exports with the flagged observations that show a named leopard but unidentified sex or position.

[Observations with Unidentified sex or position.xlsx](https://github.com/pantheracorp/PantheraIDS_Issues/files/3959536/Observations.with.Unidentified.sex.or.position.xlsx)

**Comment by Shannon-Dubay** [comment]
Checked S15_2017, S15_2015, and S13_2013 and it appears that this issues has been resolved somewhere along the way.

**Comment by PhilipFaure** [comment]
@Shannon-Dubay, can we send this information to Lauren and close the issue?
