### ISSUE TITLE
Data Processing/Process images: Dropbox folder

### ISSUE THREAD

**Issue by rsalom** [pantheracorp/PantheraIDS_Issues#6]
I tried to process the images out of a Dropbox folder in my computer´s hard drive (not from the web application) and it wouldn´t process the images. When I changed the file to C:Documents folder it worked.

**Comment by RossPitman** [comment]
No idea why this is the case. Perhaps Dropbox creates an alias folder, which looks like a real folder but isn't. Best to always try process images from your own folder.
