### ISSUE TITLE
Manual Identification / Metadata not loading

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#60]
when looking at the Manual Identifications module the metadata isn't loading (in the "Primary Metadata" box). haven't tested the secondary but I suspect thats not working either.

**Comment by Shannon-Dubay** [comment]
Update- actually, I'm unable to apply any edits to the images. When clicking "Apply" in the "Edit Primary Image" panel, nothing happens (no little popup in the bottom right that says its working, and no green confirmation box at the top that shows the edits were applied).

**Comment by RossPitman** [comment]
Is this related to local databases, server databases, or both?

**Comment by RossPitman** [comment]
On initial inspection, it looks as if some old test code was left in IDS accidentally. This appears to be when Valentine used the Manual Identification module to test his viewer package. I've replaced this code with the correct code. Still working on the other components.

**Comment by RossPitman** [comment]
On further inspection, and after testing the Manual Identification module by trying to apply and save edits, the original error seems to have been resolved. This all stemmed from the above viewer code. Note though that I've only tested this with a local database, and only tested the primary component. More to follow.

**Comment by RossPitman** [comment]
I can confirm this works for the secondary component too.

**Comment by RossPitman** [comment]
Beta version (v.2.17.837) pushed to Docker Hub for server-side testing. Over to you @Shannon-Dubay.

**Comment by Shannon-Dubay** [comment]
Can confirm that the metadata, the edit image, and the batch rename all work in the beta version .837. Success!!!

**Comment by Shannon-Dubay** [comment]
OK, well.... the primary side works perfectly... but the secondary side doesn't. The metadata loads, but the edit image doesn't do anything.

**Comment by RossPitman** [comment]
Noted. The secondary panel was deactivated. It was only activated once we were happy with the code used in the primary panel.

**Comment by RossPitman** [comment]
Fixed and closed.
