### ISSUE TITLE
Machine Classifier Performance Metrics

### ISSUE THREAD

**Issue by RossPitman** [pantheracorp/PantheraIDS_Issues#62]
The UI of the Machine Classifier Performance tabBox requires modification. This tabBox should fit within the "Evaluate" Tab, within the first tabBox, rather than sitting on its own. It current renders, and remains rendered, even if the user hasn't asked for it.

**Comment by RossPitman** [comment]
Bump

**Comment by PhilipFaure** [comment]
All done! Closing issue
