### ISSUE TITLE
Analyses/SCR/ML

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#63]
From Lucy: I have noticed that within the analysis A section of SCR under Data Analyses and then Camera Trapping there seems to be a problem with the maximum likelihood function. It works perfectly for some sites, but for others it returns message saying that an error has been encountered, and the log file says that the error is because mixture models fail when the first detector is not used on the first day (the bayesian analysis still runs without error). This seems to be a problem coming from within secr itself, not IDS. I have spoken to Philip and there are ways around it by manipulating files outside of IDS to make the first detector active on the first day, but thought I would post it here as well in case there is a more long term solution. This was noticed in v.2.16.834. Thanks so much!
See log file here: https://www.pantheraids.org/forum.html?p=post%2Ferror-with-ml-scr-10414719%3Fpid%3D1310635869

**Comment by Shannon-Dubay** [comment]
From Marine on the same forum post as mentioned above:
"I definitely got the same issue with my data and IDS. It is indeed because mixture models want the first camera trap to be used on the first day (having a 1 instead of a 0 in the matrix). Is there a way to fix that within IDS in the future?"

@PhilipFaure when you manage this please close. Thanks!

**Comment by PhilipFaure** [comment]
This has been fixed. Closing Issue.
