### ISSUE TITLE
Database queried multiple times when pulling multiple datasets from redshift

### ISSUE THREAD

**Issue by PhilipFaure** [pantheracorp/PantheraIDS_Issues#65]
For example, in Manual Identification, when a user pulls data from the server to work on individuals from multiple sites, the database is queried with each survey site added (i.e. each click). Would speed up computation time if we add a actionButton to start query only once all sites have been selected. If no rejections to the idea, could start working on this next week.

**Comment by RossPitman** [comment]
Yep, go for it. Regarding format, please add the action button underneath the Select Survey dropdown, make it width 12, and the button text should read "Request Data". The action button will need to be dynamic, so that it only shows when "From Server" is chosen.

**Comment by RossPitman** [comment]
@PhilipFaure  – is this done?

**Comment by PhilipFaure** [comment]
Done. Closing issue
