### ISSUE TITLE
Data Processing / Recognition / Grouping

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#71]
The grouping database needs to save as soon as its created. At the moment it only saves after you manually click “Save” the first time. This means if you want to create a copy of the new and un-touched/un-worked on grouped database, you have to remember to click “Save” before you make any edits. Instead, this should be automatic, like any other output from any other module.

**Comment by RossPitman** [comment]
Nice idea!

**Comment by Shannon-Dubay** [comment]
This issue is confirmed fixed in v.2.21.876, and has been sorted for some time now. Closing issue.
