### ISSUE TITLE
Data Processing / Classify / Image Viewer

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#72]
From Joleen via the forum:
When using the new Image Viewer, the "Next Batch" feature render unexpected results : 
- incorrect count of batches (Batch number 11 while there are only a total of 4 batches for example, examples attached)
- when busy with a specific batch, for example Batch 1, and then click "Next Batch", it will jump to the Batch 5 for example (often the last batch in the count of batches / or if there is only a total of 2 batches, then it will render a blank page -> in that case, it is possible to view Batch 2 by clicking "Previous Batch")

See forum post here: https://www.pantheraids.org/forum.html?p=post%2Fnext-batch-slightly-temperamental-10427411%3Fpid%3D1310748524

**Comment by RossPitman** [comment]
@kacoster – are you aware of this behaviour? Is it still an issue?

**Comment by kacoster** [comment]
@RossPitman - Yes I recall fixing this issue. I will monitor it and close the issue.

**Comment by RossPitman** [comment]
Thanks
