### ISSUE TITLE
Data Analyses / SCR Files

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#73]
From Lauren via the forum:
When generating SCR files for surveys from the server, it does not work unless you manually create a folder with the survey name (eg: S4_20140629_2014_0812) in the database folder in ids_volume. These folders will already be created when working locally, however if I am wanting to generate these files for historical surveys, it becomes time consuming to have to manually create the folders first per survey per year instead of having the folders automatically generate when trying to produce the files. 
This is working from the lion PC running Windows Home, IDS latest V2.17.844)

**Comment by Shannon-Dubay** [comment]
Similarly, I have had the same experience with Recognition. If you are running recognition on a computer that hasn't had any previous work completed on it for that survey (and therefore doesn't have the survey folder already created), you will run Reco and only after it creates all the comparison images (sometimes many hours!) does it throw an error message and fails to create the recognition database because the survey folder doesn't already exist. This is a cumbersome and convoluted problem; one many users would not know how to fix. 
It would be best if the code said something like "Find the survey folder in the 'databases' folder, if you can't, then create a survey folder"

**Comment by Shannon-Dubay** [comment]
@PhilipFaure just to follow up from our conversation the other day about this, it seems I have already logged it in Github

**Comment by PhilipFaure** [comment]
Issue addressed in v2.18.859 - Closing
