### ISSUE TITLE
Reco issues with saving databases

### ISSUE THREAD

**Issue by pantheracorp** [pantheracorp/PantheraIDS_Issues#74]
From Lauren:
So Shannon and I have come across an issue when merging the IDs from the grouping dtbs at the end of Reco. My understanding is that the dtbs_test_idntfctns_mrg database is the final one created after hitting ‘merge’ at the end of grouping, and includes all the IDs. 

[I know this because Timbavati (S18_2019) ran smoothly and no IDs were edited using the Manual Identification function after Recognition... therefore when looking at Timbavati in both Manual Identification and the Observation Table, the normal dtbs.Rdata does not contain IDs and the dtbs_test_idntfctns_mrg.Rdata contains all the IDs.]

Storme has been working on Hwanwge (S3031_2019) and this is where we came across the issue with the dtbs. It is a very small site and we only got two IDs out of it- Male 1 and Male 2. We created the dtbs_test_idntfctns_mrg.Rdata file by merging the IDs from the grpd dtbs to the normal dtbs at the end of Reco, and the two IDs saved during grouping were correct (Male 1 and Male 2). However, because it was such a small site, we checked the ‘unidentified’ individuals in Manual Identification afterward just to see if we could find any more individuals to manually ID, which we did. After loading in the dtbs_test_idntfctns_mrg.Rdata and renaming a lot of the individuals in ‘unidentified’, we noticed two things:

	
 The IDs created using Manual Identification (the rename primary image section) saved onto the dtbs.Rdata file and not the dtbs_test_idntfctns_mrg.Rdata file.
	 The names in the dtbs.Rdata file did not contain the site number, so instead of ‘Leopard_African_Male_3031_5’ the ID was saved as ‘Leopard_African_Male_NA_5’. I can change this manually using the 'Batch Rename' tool within Manual Identification for the purpose of my analyses, but just wanted to bring that to your attention. 

The resulting issue is that some IDs are saved on the dtbs.Rdata and some are saved on dtbs_test_idntfctns_mrg.Rdata, depending on if you saved IDs during the grouping stage or if you manually identified individuals in Manual Identification. My concern is that these IDs obviously have to correspond with the identifications csv when running the analyses. 

I have attached both databases for Hwanwge and Timbavati for your reference. Let me know if there is anything else you need! Thanks Ross.

**Comment by Shannon-Dubay** [comment]
This has been fixed in the latest update (v.2.21.876). Closing issue.
