### ISSUE TITLE
Site Management - Site/Hub Corrections

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#77]
From Jo via forum:
- It seems sites in China and Mongolia fall under a "SouthAsia" hub instead of a "EastAsia" hub
- I believe it is Niokolo Koba and not Niokola Koba
- Murghab (site in Tajikistan) is saved under the centralamericahub
- Would it be possible to add a "Country" column, at present users can only narrow to regional hub, an option to filter to country would be helpful

From Roberto Salom-Perez : change centralamericahub to mesoamericahub (more accurate as the former doesn't include Mexico)

**Comment by RossPitman** [comment]
Niokolo Koba done.

**Comment by RossPitman** [comment]
Where is the country information going to be used? IDS already stores the country's ISO code, so we know the country, but it depends what this is needed for?

**Comment by RossPitman** [comment]
Changing the name of a hub is a tonne of work. Not really worth it given our workload.

**Comment by Shannon-Dubay** [comment]
Jo was suggesting we add a 'Country' column to the table in the Site Management module... at the moment it only has Hub, and she thinks it would be beneficial to have something that is a bit more specific. If its not too much work, I agree with her

**Comment by RossPitman** [comment]
For now we won't be adding a country field. It's going to be a bit of work.

**Comment by Shannon-Dubay** [comment]
OK I will put the request of a country column in the site management module as a feature request for potential attention at a later stage

**Comment by RossPitman** [comment]
Cool, thanks Shannon!

**Comment by RossPitman** [comment]
Murghab fixed on next sync.

**Comment by RossPitman** [comment]
Roberto's request = currently denied. That's a huge amount of work.

**Comment by RossPitman** [comment]
Should those China and Mongolia sites not be coded as Central Asia?

**Comment by RossPitman** [comment]
In fact, they're currently coded as Central Asia.

**Comment by RossPitman** [comment]
Closing for now. Feel free to re-open if I've missed something.

**Comment by Shannon-Dubay** [comment]
The boundaries of different regions in continents is interesting. The following seems to be the general idea when it comes to regions of asia- therefore China would be considered East Asia. When assigning hubs to the species in the species list, I assigned any species in western china to 'centralasia' after looking at current IDS sites and their assigned hubs for that area.  https://www.mapsofworld.com/asia/maps/asia-region-map.jpg

**Comment by Shannon-Dubay** [comment]
Mexico is another sneaky one. Currently, we have been been putting any sites in Mexico into central america hub, but it is actually considered north america. However, in keeping with our current data I put any species found in Mexico under 'centralamerica'

**Comment by Shannon-Dubay** [comment]
> Murghab fixed on next sync.

Hi @RossPitman - I know you said Murghab was fixed upon the next sync, but it has been 9 days now and its still incorrect. I thought there was a sync that happened recently (I am seeing other things that were waiting to be fixed on a sync that are fixed)? If not, my apologies for jumping the gun!

**Comment by Shannon-Dubay** [comment]
Checked again today and still not correct.
