### ISSUE TITLE
Data Processing / Process - Processing Popups

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#79]
The popups (which are very important during the processing to check whether your images are being processed correctly) disappear if the newly implemented security lockout popup comes up, and there's no way to get back to the processing popup message. Can this be fixed at all? Its important- thanks!

**Comment by RossPitman** [comment]
Not sure about this.

**Comment by RossPitman** [comment]
Completed. The existing modal will prevent the security lockout modal from rendering. We have to do this for each specific modal, and currently it's implemented to the successful archive modal, since this is the modal that'll typically take a long time. Any others you feel we need to focus on?

**Comment by Shannon-Dubay** [comment]
Thats awesome! The only modules would be modules that give important popups, and I think that the process module is really it.
