### ISSUE TITLE
Data Processing / Process - Incorrect wording on Processing Popup

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#80]
![Capture](https://user-images.githubusercontent.com/48274721/75347407-58c14580-58a9-11ea-8050-cf165e4fb778.PNG)

Here is the popup that comes up when you click "Restructure Images" at the top of the Process module. I don't believe the wording of the second paragraph is correct (or even makes sense). Please advise... I'm not sure what it is even referring to when it says "but rather in the format described within the step-by-step camera trapping guidelines".

**Comment by RossPitman** [comment]
So we had a original step-by-step guideline that instructed people to manually restructure their images. This was back in the day...when folks had to manually do things (shock-horror). We will just remove that second paragraph altogether. @kacoster , this one is for you.
