### ISSUE TITLE
Data Processing / CameraAct or Timeshift error popup

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#81]
Sometimes the attached image comes up when there is an error with the camera active sheet or the timeshift sheet, however the popup is not accurate (doesn't specify the actual error occurring) and misleads the user. Most recently, I got this 'cameras need to be prefixed with "CAM"' error message, but they all were correct. When looking at the csv through a text editor, I realised the sheet had extra empty columns/rows (shown in the text editor as a column/row of commas). When I fixed this by deleting those columns/rows in excel, IDS took the sheet perfectly with no error. Long story short, it seems as though this "CAM" prefix error comes up for many different errors, and should be changed as to not frustrate/confuse/mislead the user... so that they can actually have a shot at fixing the real error.
![CAM_Prefix_Error_Incorrect](https://user-images.githubusercontent.com/48274721/75760561-26e42f00-5d40-11ea-96e3-ec0013f0d0b4.PNG)

**Comment by PhilipFaure** [comment]
Closing Issue. Error messages should now be more informative.
Edits made to loading of cameras active and timeshift:
- Colnames are autocorrected for common spelling mistakes
- Spaces are removed (e.g. CAM 12345 ~ CAM12345, etc.)
- Empty columns at the end are removed
- The user is now able to load in spreadsheets separated by semicolons/commas
