### ISSUE TITLE
Data Processing/Machine Classifier/Merge

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#82]
When using the Central Africa Machine classifier, the machine seems to create the predictions file per normal, but the predictions csv doesn't merge correctly with the dtbs. It gives the green thumbs up, and doesn't produce an error in the log (produced line 395). 
But when I go to load the dtbs into the Tables module, the species table is still empty, and the log produces the last 3 lines in the attached screenshot. Note: When merging the predictions csv to the dtbs, I am keeping the "Overwrite existing predictions" to no. Not sure if this has anything to do with it? Is this the first site to be classified by the Central Africa classifier, perhaps its something to do with that?
Please let me know if you would like the predictions csv and dtbs to look at and I'll send it seperately (don't want to upload it here)
![image](https://user-images.githubusercontent.com/48274721/76158926-bcf2cd80-6123-11ea-932e-83167af79684.png)

**Comment by Shannon-Dubay** [comment]
UPDATE: When setting "Overwrite existing classifications" to "Yes", the predictions seem to merge with the dtbs correctly.

**Comment by RossPitman** [comment]
Hey @Shannon-Dubay – can you please provide me with the predictions csv and dtbs file? Thanks

**Comment by Shannon-Dubay** [comment]
Hi, I will send them in an email now (not sure if we should be posting them here?) I believe this issue applies to more than just the Central Africa classifier.

**Comment by RossPitman** [comment]
Fixed and closed. Please let me know if the issue persists (happy to reopen this issue if needed).

**Comment by Shannon-Dubay** [comment]
@RossPitman I see the wording has changed for the setting where users specify if their dtbs is a complete dtbs (and needs all the predictions merged) or if it is an increment with some classifications already (and therefore should not overwrite the existing classifications). I don't think "Actions" is very clear. 
I propose it be called something like "Database processed/classified incrementally?" with "No" being the default but "Yes" being an option. This way, for people not processing and classifying incrementally they keep to No, and the script runs like usual. If they click "yes", then the script skips any previously written classifications. (Note: if it is the first increment, the user will select "Yes", but there will be no previous classifications yet because it is the first increment, but this shouldn't be a problem for the merging, right?)
Or, if you want to keep "Actions" the options should be clearer- perhaps something like ".Rdtbs file has no existing classifications yet" and ".Rdtbs file has existing classifications". I know its long, but its the clearest and the truest (and the most fool-proof, which is really what were going for). In this situation, I a user classifying incrementally would select the first option if this is their first increment and the second for any increment thereafter.
