### ISSUE TITLE
Data Analyses/Bayesian

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#83]
From Lauren via the forum: 

I am trying to run the Bayesian Analysis for a local survey (Timbavati- S18_2019) but when I click 'run' nothing happens. I have tried on two different computers:

Lion PC (Windows Home)- SCR files are generated but when I click 'run' nothing happens. This PC is running Latest IDS, V2.18.853. Log file is attached.

Leopard PC (Windows Pro)- Most of the SCR files are produced except an error message appears this time saying "Problem generating detection history" and when clicking 'run', nothing happens. This PC is running Latest_Beta, V2.18.853. Log file is attached.

Couple things to note: This is only happening with S18_2019, the other surveys I tried all worked perfectly, whether on the server or local. I also think this may be related to the issue from last week that was fixed by Phillip (I think this was S18_2017 form the server) but I thought this was resolved so I am not sure why this one isn't working. Would appreciate any ideas! Thanks so much.

(See forum post for log files: https://www.pantheraids.org/forum.html?p=post%2Fbayesian-analysis-problem-10444705%3Fpid%3D1310941967

**Comment by RossPitman** [comment]
This sounds like an issue with the data, specifically in how the secr package handles data with missing values or NA.

**Comment by RossPitman** [comment]
I see on the forum this has been resolved.
