### ISSUE TITLE
Data Processing / Manual Identification

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#84]
From Joleen via the forum:
When loading a dtbs (from server) and filtering, the module renders "0 images processed", while images are classified under the species selected. Using "Primary Identification" panel only.
Mentioned to @PhilipFaure the sites loaded.

From Chantae on the forum:
It seems as if we are having similar issues as Joleen with the manual identification. After the database has be uploaded no images appears, so we are basically stuck at this point. We completed all classifications already. Kindly advise on how to move forward so we may further identify the cats. I've attached a screenshot.

See the forum post for uploaded log files and screenshots: https://www.pantheraids.org/forum.html?p=post%2Fmodule-not-reading-the-dtbs-10441396%3Fpid%3D1310941970

**Comment by RossPitman** [comment]
Repaired and closed.
