### ISSUE TITLE
Data Processing/Manual Identification - Site not incorporated in rename of individuals

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#85]
From Lauren via the forum (see her post here: http://www.pantheraids.org/forum.html?p=post%2Fnaming-issue-10472138%3Fpid%3D1311113483)

When editing the name of an individual (whether in the primary or secondary image tab), the survey site number is not included in the name but rather is replaced by 'NA'. For example, if I wanted to rename an individual to 'Leopard_African_Female_7_102' in the Edit Primary/Secondary Image function, the ID would rename to 'Leopard_African_Female_NA_102'. The omission of the study site number (for this example, S7 as Phinda) doesn't seem to have an affect on the generation of SCR files for the analysis, but I guess it just means the naming is not uniform.

I think this may just be due to the fact that in the Edit Primary/Secondary Image function, there is no little tab to stipulate which study site it is, unlike in the Batch Rename function where there is a little tab with a dropdown list of all our registered study sites that you select from when batch renaming. I don't know, just a suggestion to look into maybe?

PS: I did try to batch rename my now incorrectly named individuals in order to get the 'NA' to be the study site number, but for some reason it doesn't change anything.

**Comment by RossPitman** [comment]
IDS should be pulling the site name from the database, but it seems to be reverting to NA. @PhilipFaure, when you get a free slot, please have a look into this. Should be fairly simple to address.

**Comment by PhilipFaure** [comment]
I can't recreate this problem at all. Been trying since this morning. Also looked through the code and can't find anywhere where it takes the wrong SiteID or can't find it.. Tried by using a single survey, multiple surveys, and switching between different study sites for both local and server based data. Lauren also told me it's been working for her on server and local since the last updates.

**Comment by RossPitman** [comment]
Cool, close it out then if you're happy.
