### ISSUE TITLE
Data Processing/Manual Identification - Unnamed individuals "Unidentified" vs "Leopard_African_Unknown_NA"

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#86]
This has to do with the "name" that unnamed images get- for instance the leopard image of only a tail, or too blurry to ID. It seems as though there is some dependency in how these are named. 

From Lauren via the forum: 
In some instances the 'unidentified' category of images that could not be identified is named 'Unidentified' and in others it is called 'Leopard_African_Unknown_NA'. I believe the latter is what we are hoping for it to be. For the few I have checked, it seems as though local databases save it as 'Unidentified' and when working from the server it is named 'Leopard_African_Unknown_NA'. Not sure if that is important but the discrepancy could potentially cause confusion.

**Comment by RossPitman** [comment]
This depends on the database, and when it was processed. We used to only save leopard IDs when we were sure of the identification. In the case above for some sites, where poor leopard images are classed as "Unidentified", this is when the user didn't feeling strongly enough to assign any individual label. We've changed this process going forwards, whereby those IDs would be classed as Leopard_African_Unknown_NA. The historical data that still has "Unidentified" will need to be manually changed (and that's up to the leopard CA team to do).

**Comment by Shannon-Dubay** [comment]
Lauren confirms that all the data she is currently working with is from 2019, so it's not a case of historical data being processed differently. Not sure if this is something we need to sort out, or if we can leave this. Theoretically all new data should be put onto the server, in which case the names will be in the correct format, but while they are still local dtbss the unidentifiable leopard images get named "Unidentified"

**Comment by Shannon-Dubay** [comment]
From Lauren on the forum: http://www.pantheraids.org/forum.html?p=post%2Fnaming-issue-10472138%3Fpid%3D1311527426

"A difference between the local and server-based databases still remains where the unidentified individuals are called 'Unidentified' for local; but 'Leopard_African_SiteNumber_Unknown_NA' for server-based databases."

Just to highlight- Lauren is working with only 2019 data, no historical surveys at the moment.

**Comment by RossPitman** [comment]
I'm not so sure that this is correct. Incidence when individuals are labeled "Species_Gender_Site_Code" are when someone has actually set it to NA. At least this is my understanding. The value of "Unidentified" is automatically given to individuals that haven't been identified at all. I don't think IDS automatically creates a "Species_Gender_Site_Code" for unidentified individuals. Looking on Data Explorer tables I can see some species have nothing (which IDS could class as Unidentified) and others have  "Species_Gender_Site_NA".

**Comment by RossPitman** [comment]
For now I don't see how we might want this to be, so sidelining it for now.
