### ISSUE TITLE
Data Processing/Machine Classifier - Efficiency Increase

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#87]
**Background:** Currently the machine classifier for Southern Africa has 2 parts- 1) an empty_vehicle_species model, which assigns all images with one of those three classifications, and 2) a species-only model, which assigns species classification as well as additional attributes (e.g. number of individuals, various behaviour information, etc.). This second model assigns classifications for all images, even the ones that the first model classified as empty or vehicle: this is because the classifier is shown to a directory and has no way of only running on certain images within that directory. 

**Fix:** In order to increase efficiency (which in turn will decrease processing time, processing power, and size of the csv output), we will create another directory that only includes images that the first model classified as species. This new directory will be located at ids_volume/data/images/SurveyFolder, so that within the Survey Folder is a folder called "images" with all the processed images (the way its always been), and an additional folder called something like "species_images". This additional directory will automatically be created as one of the last steps of running the first model. The images classified as species will be copied to this new directory. 
Then, when the user selects "Southern Africa" for the region and "Species" for the model, this combination automatically triggers IDS to look for the "species_images" folder within the directory they have already browsed to (currently, users browse to the _parent folder of the Survey Folder_ when running any models in the classifier). If, for some reason, the directory isn't there (perhaps they didn't run the first model, some whatever reason?), it will automatically revert to using the directory we have always used: ids_volume/data/images/SurveyFolder/images.

Something to consider:
-Many users get confused about where to browse to when running the classifier... browsing to the parent folder isn't something that most people expect/remember. Depending on how complicated it would be to apply, can we consider establishing an option identical to what we already have in the Manual Classification module, where the user specifies if they are using "external images"? If 'No' to  'External Images?', IDS knows where to look; if 'Yes', then the user has to browse. It appears that most people use the same computer to machine classify as they did to process, so images are probably readily available in a location that IDS can expect.

Thoughts and suggestions appreciated @RossPitman and @PhilipFaure :)

**Comment by Shannon-Dubay** [comment]
Update: Sasi (Thailand user) is experiencing the same when putting her data through the south east asia classifier. This region only has one model, therefore a fix as recommended above won't apply to her. 
Her computer has 8GB RAM, and she has 95,000 images in her data set. The machine classifier runs for about 3 hours, and gives her the green thumbs up when finished. But when she looks at her predictions csv she only has roughly 10,000 rows, and 85,000 images are "Unclassified" when looking at the species in the Classification module, after merging the predictions csv with her dtbs.
The following is the end of her log file:

Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Corrupt JPEG data: premature end of data segment
Killed
Warning in system2(command = py_lctn, args = args, stdout = TRUE) :
  running command ''/anaconda3/envs/tensorflow1.12.0/bin/python' '/srv/shiny-server/custom/machine_classifier/main_prediction/predict.py' -image_dir '//ids_volume/data/images/S3017_20190115_20190619/images' -results_file '/ids_volume/data/predictions/S3017_20190115_20190619_species_2020.04.15_01.22.csv' -model_path '/srv/shiny-server/data/models/south_east_asia/species/model.hdf5' -pre_processing_json '/srv/shiny-server/data/models/south_east_asia/species/image_processing.json' -class_mapping_json '/srv/shiny-server/data/models/south_east_asia/species/label_mappings.json'' had status 137

**Comment by RossPitman** [comment]
Not much we can do for Sasi. Her computer is bombing out due to lack of sufficient memory. She should try on a more powerful computer.

**Comment by RossPitman** [comment]
The machine classifier module now subsets images from the southern africa classifier, as mentioned above. Also, the UI has been updated, as requested, re "external images?". Fixed and closed.

**Comment by Shannon-Dubay** [comment]
Problem with the new southern africa classifier:
Not using the "species_images" when running the second model, so its still trying to classify everything
(by the way, the first model and the creation of the "species_images" folder is working as intended. it just appears that the second model doesn't use it)

**Comment by Shannon-Dubay** [comment]
Update, Dani's also didn't work:
Asked Dani for her predictions csv and it appears that her second model also didn't use the "species_images" directory. the second model classified all the images (even ones the first model classified to vehicle or blank) to species level. 
(For her though, this wasn't a problem because her data was already subsetted, making the amount of images manageable enough for the second model to complete each batch.)
