### ISSUE TITLE
Data Processing/Manual Identification - IDS Not Loading Correct Images

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#89]
It seems as though the module is not rendering the correct amount of images- could be limited to this specific survey, but not sure. No other users have reported this, but they may not realise it is happening:

From Jo via the Forum:
On S34, when filtering to SC spc, the number of images extracted doesn't match what is in the dtbs : 
- Cat_Leopard : display "0 images extracted" while there are actually 183 images in dtbs
- Cat_Marbled : display "0 images extracted" while there are actually 54 images in dtbs
- Cat_Asian_Golden : display "0 images extracted" while there are actually 46 images in dtbs
- Leopard_Indochinese_Clouded : display "2 images extracted" while there are actually 30 images in dtbs
Prior work on these databases : this dtbs gave me an issue last month, Ross had a look and fixed it (problem = position information was missing in the dtbs when loaded on server a while back, 2018?). I began IDing individuals, starting with Leopard_Indochinese_Leopard, and IDed 2 images (which is the number of images IDS can now load, see above). 
**Could it be that it the filtering is only looking at images that have an ID ?**

See original forum post here: http://www.pantheraids.org/forum.html?p=post%2Fids-crashes-10469260%3Fpid%3D1311172725

**Comment by RossPitman** [comment]
@kacoster is in the process of building a new image viewer with Manual Indentification module. We will revisit this issue once the viewer is built.

**Comment by RossPitman** [comment]
The reason why the 0 images are being extracted is because this dataset has missing fields for the position attribute. This is the same issue as previous datasets Jo is trying to work on, which weren't officially processed through IDS.

**Comment by RossPitman** [comment]
I'm looking at a fix for this.

**Comment by RossPitman** [comment]
Valentine has built the new image viewers for Manual Identification. A fix has been implemented for the second issue.
