### ISSUE TITLE
Data Processing/Process Images and Machine Classify - Assist Dani

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#90]
Dani (Wildlife ACT) has been stuck with her data for over a week now. I have tried to help her on multiple occasions and cannot figure out what the problem is. It seems to only apply to her data, as other users have successfully processed and machine classified their data.

Dani's classifier doesn't want to work. She is browsing to the correct folder and it appears she has all the correct files, images, and folders that are needed to machine classify. When attempting to run the machine, it runs for ~30 seconds before giving the Error popup. Nothing obvious is written into the log file.

While fighting to get the classifier going, Dani has come across a few minor issues with her processed data (a corrupt image, an incorrect date, etc.) but nothing that would explain why the classifier isn't working. When reprocessing to correct for these minor things, the database is created and all images are written into the images folder. She gets the Success popup (see below)
![image](https://user-images.githubusercontent.com/48274721/78877774-a9ec5980-7a51-11ea-8dcb-495a30011628.png)
However, when the processing has finished, IDS shows "0" for images archived in the green status bar (see below)
![image](https://user-images.githubusercontent.com/48274721/78877801-b40e5800-7a51-11ea-95c5-c41be25fd469.png)

Dani has checked that the number of processed images matches with the number of raw images. It appears the images are created correctly, however I suspect there is still something wrong with the images or database, which is impacting the machine classifier:

The following is from the log file from the IDs session in which she reprocessed her images (the actual file is too big to attach here)- in the log, every image is listed as a warning that it "cannot rename file". Then it gives a warning that it cannot create directory because there is "no such file or directory" as '/ids_volume/data/images/S4_20200124_20200316/images'. 
Directly after this, we tried to machine classify. 

Warning in file.rename(from = x$SourceFile, to = paste(x$Directory, x$FileName_New,  :
  cannot rename file '//ids_volume/data/images/Copied_Data_Database/CAM40774/Check2/C1625558_30309.JPG' to '//ids_volume/data/images/Copied_Data_Database/CAM40774/Check2/S4__Station30__Camera2__CAM40774__2020-03-16__07-05-58__3151__1.JPG', reason 'No such file or directory'
Warning in file.rename(from = x$SourceFile, to = paste(x$Directory, x$FileName_New,  :
  cannot rename file '//ids_volume/data/images/Copied_Data_Database/CAM40774/Check2/C1625561_30310.JPG' to '//ids_volume/data/images/Copied_Data_Database/CAM40774/Check2/S4__Station30__Camera2__CAM40774__2020-03-16__07-06-01__3152__1.JPG', reason 'No such file or directory'
Warning in file.rename(from = x$SourceFile, to = paste(x$Directory, x$FileName_New,  :
  cannot rename file '//ids_volume/data/images/Copied_Data_Database/CAM40774/Check2/C1625644_30311.JPG' to '//ids_volume/data/images/Copied_Data_Database/CAM40774/Check2/S4__Station30__Camera2__CAM40774__2020-03-16__07-07-24__3153__1.JPG', reason 'No such file or directory'
Warning in dir.create(new_dir) :
  cannot create dir '/ids_volume/data/images/S4_20200124_20200316/images', reason 'No such file or directory'
Warning in max(DateTimeInput) : no non-missing arguments, returning NA
2020-04-01 10:38:00.807550: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
WARNING:tensorflow:From /anaconda3/envs/tensorflow1.12.0/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:87: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
WARNING:tensorflow:From /anaconda3/envs/tensorflow1.12.0/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:87: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
Warning in eval(expr, env) : Credentials do not match
Warning in eval(expr, env) : Credentials do not match
Warning in max(DateTimeInput) : no non-missing arguments, returning NA
2020-04-01 11:38:22.926552: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
WARNING:tensorflow:From /anaconda3/envs/tensorflow1.12.0/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:87: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
WARNING:tensorflow:From /anaconda3/envs/tensorflow1.12.0/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:87: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
Warning in max(DateTimeInput) : no non-missing arguments, returning NA
Warning in max(DateTimeInput) : no non-missing arguments, returning NA
Parsed with column specification:
cols(
  .default = col_double(),
  Study = col_character(),
  Station = col_character(),
  CameraID = col_character(),
  Cameras = col_character()
)
See spec(...) for full column specifications.
Warning in dir.create(new_dir) :
  cannot create dir '/ids_volume/data/images/S4_20200124_20200316/images', reason 'No such file or directory'
Warning in max(DateTimeInput) : no non-missing arguments, returning NA
2020-04-01 14:04:49.546405: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
WARNING:tensorflow:From /anaconda3/envs/tensorflow1.12.0/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:87: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`
WARNING:tensorflow:From /anaconda3/envs/tensorflow1.12.0/lib/python3.5/site-packages/tensorflow/python/ops/init_ops.py:87: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with distribution=normal is deprecated and will be removed in a future version.
Instructions for updating:
`normal` is a deprecated alias for `truncated_normal`

**Comment by RossPitman** [comment]
This sounds strange. The fact that the infoBox says that 0 images were archived is worrying. Perhaps I missed it, but confirm that the images aren't actually archived?

**Comment by Shannon-Dubay** [comment]
The images appear to be processed normally. The correct number of images appear in the ids_volume/data/images/SurveyFolder/images location, and the file names are in the correct format.

**Comment by RossPitman** [comment]
OK thanks, that's interesting. I need to have a think about this...

**Comment by Shannon-Dubay** [comment]
Hi Ross, this really really needs attention ASAP. Can you please assist us somehow? Both myself and @PhilipFaure have tried to troubleshoot but we are completely stumped. Dani has been waiting for 4 weeks now, and I am completely stumped
