### ISSUE TITLE
Data Processing/Timeshift Calculator - Crashing when Calculating

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#91]
From Barbara on the forum (see post here: http://www.pantheraids.org/forum.html?p=post%2Fautomatic-disconnection-from-server-10471387%3Fpid%3D1311242508)

I get disconnected and the gray screen shows after trying to calculate the time shift. I've already tried many times and I noticed something weird: it seems that when I only change something like the year, the calculator gives me the time shift, but when I try to calculate the real one (with day, month, year, time) as soon as I click for getting the time shift, I gets disconnected.
Here is the timeshift in question:
![image](https://user-images.githubusercontent.com/48274721/79358797-fc41e480-7f41-11ea-8f28-ea749bc83768.png)

I personally tried to recreate her issue, and found the same, using alpha, .860 version. It doesn't crash every time though, just for some date/time combinations which I can't seem to find a pattern for. This was recorded in the log after crashing:
Warning: Error in translate()$t: unused argument ("than your second date-time.")
  102: paste0
   72: observeEventHandler
    1: runApp

**Comment by PhilipFaure** [comment]
- fixed translate() function
 - Fix if clause to determine whether date 1 is smaller/larger than date 2 before calculation.

![Screenshot 2020-04-15 at 19 58 31 (2)](https://user-images.githubusercontent.com/24668143/79371684-0d482100-7f55-11ea-81f6-5a536846ba93.png)

Closing Issue.
