### ISSUE TITLE
Data Analyses/ML - Unknown Individuals

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#92]
From Gareth on the forum, see original post here: http://www.pantheraids.org/forum.html?p=post%2Funknown-sex-individuals-excluded-from-ml-analysis-10488537%3Fpid%3D1311242145

It seems that when data input files are being prepared for analysis, individuals of 'unknown' sex are being included in the Bayesian input data, and excluded from the ML input files - see the attached files for an example. The Bayesian AC file has 32 individuals, of which 7 are unknown sex, the ML AC file only has 25 individuals all of which are classified as male or female.

Can we get the unknown individuals included in these input files, with sex coded as NA? This will probably cause an error with some ML models (if you specify sex as a grouping variable then I think that all individuals HAVE to be either male or female), but if you specify sex as a hcov variable you can have unknown individuals in the model. Otherwise we risk underestimating population density by quite a lot at sites where we get large numbers of individuals that we can't confidently sex.

**Comment by Shannon-Dubay** [comment]
@Shannon-Dubay test

**Comment by RossPitman** [comment]
Completed.
