### ISSUE TITLE
Data Processing / Manual Identification - "Individual" dropdown populates incorrect species

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#95]
From Jo via the forum (http://www.pantheraids.org/forum.html?p=post%2Fids-crashes-10469260%3Fpid%3D1311302752):

After specifying the species to view, the "individual" dropdown populates with the wrong species Jo gives a screenshot in her post as an example.

Ross mentioned this is an old, known issue.

**Comment by Shannon-Dubay** [comment]
Jo has been asking about this again on the [forum](https://pantheraids.org/forum.html?p=post%2F10469260%3Fpid%3D1314121632), here is a screenshot she provided:


![image](https://user-images.githubusercontent.com/48274721/92905244-cab34380-f423-11ea-8d72-0ebea4032aaa.png)

**Comment by RossPitman** [comment]
Completed.
