### ISSUE TITLE
Data Explorer / Map - Species Selection not working properly

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#96]
From Daniela on the forum- see the post for log files: http://www.pantheraids.org/forum.html?p=post%2Fdata-explorer-map-10491218%3Fpid%3D1311269446

I can select species for the map, but when I do the third selection, I can´t erase or choose a new species to display on the map. I have the latest version (v.2.19.860). Today I try again and it start working great, but 30 min later it didn´t allowed me to erase and add new species.

Note from Phil: I've tried with some databases I have on my computer but could not recreate the problem, I can select more than three species, and if I click to highlight one of the species I can remove them.
Asked for dtbs to be sent- potentially a dtbs specific problem?

**Comment by PhilipFaure** [comment]
I recently also experienced the same problem. It's an issue with having the selectInput within the map. This also creates a problem when you select a lot of images on a small screen, then the dropdown can show the species at the bottom as it does not display beyond the map.

Will fix this up by moving the selectInput outside the map ASAP

**Comment by PhilipFaure** [comment]
Resolved. Closing issue.
