### ISSUE TITLE
Data Explorer / Maps - Incorrect displaying of MCPs with multiple surveys

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#97]
From Jo via the forum: http://www.pantheraids.org/forum.html?p=post%2Fbroader-approach-in-data-exploreranalysis-modules-10503125%3Fpid%3D1311358278

"At the moment, if some modules allow to query multiple surveys at a time and then filter to a species level, the output remain difficult to use. For example the Map module, MCPs include space between surveys. "

See forum post for screenshot of example. 

Phil response: initially the maps module was developed to visualise single surveys at a time - thus it's calculating the MCP for all locations.

**Comment by RossPitman** [comment]
This feature/issue will be addressed holistically within a new IDS module. More soon.

**Comment by PhilipFaure** [comment]
Done. Closing Issue.

<img width="1423" alt="Screenshot 2020-09-18 at 11 24 30" src="https://user-images.githubusercontent.com/24668143/93582599-01003e00-f9a3-11ea-8735-0e3189b0b817.png">
