### ISSUE TITLE
Data Processing/Process Images- Incremental Processing, Images don't process fully

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#98]
When testing the incremental processing, stumbled upon this issue of the images not being completely processed. My apologies, this was some time ago (I believe beginning of March?) and I forgot to record it on Github. At the moment we do not have anyone that has/is trying to process incrementally, but I know there has been some interest in Central/West Africa and definitely interest by Dani (Wildlife ACT) and Marike.

(note: I can provide the sample data I used for testing, should you want to recreate the error)

Basically, the images just don't complete. After processing the second increment, I am left with an images folder (Docker/ids_volume/data/images/merged/SurveyFolder/images) that contains all the images from my first increment processed, but also a seemingly temporary folder named "new", which contains some of the images from the newest increment (note- not _all_ images from the newest increment). See screenshot: 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/48274721/80959881-069c2380-8e08-11ea-9504-ccc3f7ef49d2.png)

However, this didn't happen all the time. When I went to re-try, it worked fine. When I tried a third time on another increment, it happened. I am not sure what the limiting factor is. My log (which is now lost somewhere in the millions of log files on my computer) didn't have anything out of the ordinary in it. Because it was just a test dataset, the increments I was working with were very small- not many images, so I doubt its a memory issue, but who knows...

**Comment by RossPitman** [comment]
@Shannon-Dubay – can you please look further into this to try figure out the pattern/issue. Given you've already started to figure it out, it's be quickest if you could keep going. Once you've got more info, and hopefully a pattern, we can work to fix it.

**Comment by Shannon-Dubay** [comment]
Spent over a day exploring this, looking for any patterns. Unfortunately I found very little. 
I started over from the beginning. I had 6 cameras, 2 per station, in my dataset. First increment had a total of 421 raw images, second was 1718 raw images. First increment went fine, second increment had only some images processed- some were missing. The clearest pattern I could find was that both cameras from station 1 were completely processed, both cameras from station 2 were partially processed, both cameras from station 3 had all images missing. No pattern on why some images were processed while others were missing in the station 2 cameras.

Notes from my processing testing:

- Created first increment fine: all 421 raw images were processed 
    - IDS reported 421 images ready for processing in the popup after clicking "Scan Metadata"
    - IDS reported 421 images processed in the "Success- 421 images archived" green box that shows above the "Archive" panel 
    - there are 421 processed images in \Docker\ids_volume\data\images\S16_20181009_20181018\images
    - Log shows this interesting line: _Warning in dir.create(new_dir) :
  cannot create dir '/ids_volume/data/images/S16_20181009_20181018/images', reason 'No such file or directory'_ (which I don't understand, because that directory was there when IDS finished, with all images inside correctly)
[thirdtest_increment1_shiny-server-shiny-20200612-122035-35485.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/4772296/thirdtest_increment1_shiny-server-shiny-20200612-122035-35485.log)


- Second increment not fine: 421 images from increment 1 were included, but only **742 of the 1718** images from increment 2 were processed (missing 976 images)
    - IDS reported **1718** images ready for processing in the popup after clicking "Scan Metadata" 
![image](https://user-images.githubusercontent.com/48274721/84566084-c026d680-ad6e-11ea-9cff-6ad07797882d.png)
    - IDS reported **1163** images processed in the "Success- 1163 images archived" green box (1163 = 421 increment1 images + **742** increment2 images) 
![image](https://user-images.githubusercontent.com/48274721/84566097-d765c400-ad6e-11ea-8a15-44c89b10ef0c.png)
    - there are 421 increment1 processed images in \Docker\ids_volume\data\images\merged\S16_20181009_20181109\images, and **742** increment2 processed images in \Docker\ids_volume\data\images\merged\S16_20181009_20181109\images\new. (there should be 1718)
    - Log shows the following line for all 1718 increment2 images: _Warning in file.rename(from = paste0(nw_dir, nw_trggr_tbl$FileName), to = paste0(fnl_dir,  :
  cannot rename file '/ids_volume/data/images/merged/S16_20181009_20181109/images/new/J2726195_501.JPG' to '/ids_volume/data/images/merged/S16_20181009_20181109/images/S16__Station2__Camera2__CAM51522__2018-10-27__07-16-35__635__1.JPG', reason 'No such file or directory'_ (which is partially true- they were not moved out of the "new" folder and into the regular "images" folder, but they were renamed. However, the log has this line for all 1718 increment2 images, including the 976 increment2 images that are missing)
[thirdtest_increment2_shiny-server-shiny-20200612-172800-46243.log](https://github.com/pantheracorp/PantheraIDS_Issues/files/4774443/thirdtest_increment2_shiny-server-shiny-20200612-172800-46243.log)



Notes on the missing 976 images:

- Breakdown of the missing processed images (out of the 6 cameras included in this test dataset, 2 camera's (Station 1) had all their images processed correctly, 2 cameras (Station 2) had only some, 2 cameras (Station 3) had no images processed):
![IMG_9933](https://user-images.githubusercontent.com/48274721/84566788-41cd3300-ad74-11ea-8ea5-003ebd7803aa.jpg)
    - When reprocessing (tried two trials) the same exact result was produced.
- When exploring the cameras that had some images processed some not (CAM63761, CAM51522):
    - Raw, original: Nothing concerning with the raw images, CA and TS correct
    - "Copied_data" folder: all images included, restructured and renamed correctly
    - Processed images for partially processed cameras:
        - CAM51522: 372 out of 917 images there. It appears that when sorting by date/time, just the middle chuck of the images were processed, with the 545 missing images being situated before and after the processed chunk. The 372 processed images are temporally sequential and situated in the middle of the batch of 917 (207 images come temporally before the 372, and 338 images after; with the line between processed and missing images not falling along day breaks- for instance, the first image of the camera that was processed was 7AM 23 Oct, while there were many images from earlier that day that were not processed) 
        - CAM63761: 6 out of 171 images there. It appears that when sorting by date/time just the first 6 images were processed. The 165 missing images all come after these 6. Again the break between processed and missing is not along a day break.

**Comment by Shannon-Dubay** [comment]
Update: when using the same exact dataset on my mac, I get the same lines reported in the log file, however after processing the second increment, I only have the 421 increment1 images processed, ALL of the new images are not there. As with the windows machine, I can see them be created, but as a last step of IDS working, they are deleted.

**Comment by RossPitman** [comment]
Jeez, headache. Thanks, Shannon. This is some great investigative work! Since on Windows you can see the files being created, and then get removed, I suspect we've got a renaming issue, which may be overwriting images (and hence deleting them). The fact that a different result happens with a mac is worrying. Will you be able to provide me with ths exact data set so I can reproduce the issues you've found, and then hopefully develop fixes? Thank you

**Comment by Shannon-Dubay** [comment]
Thanks. Sending the data now via wetransfer

**Comment by Shannon-Dubay** [comment]
Please have a quick read over #129 before finishing this, as they can be completed at the same time, and have some oerlap

**Comment by RossPitman** [comment]
OK so we seem to have fixed this. I'm going to push the next beta version, please can you test it out on your end using this same dataset (preferably on Windows if possible)? After processing both incremental datasets that you provided to me, I got a total of 2139 images, and 2139 records in the database, so all looking good. It turns out I had used the wrong function during the image copy/renaming process. Once you've tested, please let me know on here. Thanks!

**Comment by Shannon-Dubay** [comment]
This is what I get after processing my second increment:
![image](https://user-images.githubusercontent.com/48274721/85864618-0d6e6380-b7c5-11ea-82eb-11b2906686c3.png)
The second increment leaves my "images" folder with only the 421 images from the first increment as well as "existing" and "new" folders . The "existing" folder includes 50 images from my first increment, which are already located where they should be within the "images" folder. The "new" folder includes only 742 of the 1718 images. I am still missing 976 images, just as before.
Just as before, IDS reported 1718 images ready for processing in the popup after clicking "Scan Metadata" (which is the correct number of increment two images).
Now, when finished with processing, IDS says 1213 images processed in the "Success- 1213 images archived" green box (1213 = 421 increment1 images in the "images" folder + 742 increment2 images in the "images/new" folder+ 50 duplicated increment1 images in the "images/existing" folder)
![image](https://user-images.githubusercontent.com/48274721/85865489-3fcc9080-b7c6-11ea-81ad-fb1cc653f485.png)

**Comment by RossPitman** [comment]
You shouldn't have any "new" or "existing" folders on your pc with the newest version. It's defintely working on my end on mac. When you get a chance please can you try it on your mac.

**Comment by Shannon-Dubay** [comment]
And the plot thickens. On the mac, I don't have the "new" or "existing" folders, but I don't have all my images either- I only have the 421 images from the first increment and IDS shows "421 Images Archived" in the green success box. On my mac, I can also see the files being renamed and the folders being created/deleted. While it is working, in the "ids_volume/images/SurveyFolder/images directory I can see the temporary "existing" folder be created, and it has 421 images in it (correct), and I can also see the temporary "new" folder be created, with the correct amount of new images in it (1718)... but then at the last step when the images need to be taken out of the "new" and "existing" folders, the "new" images don't seem to be processed correctly, because they can't be found when IDS finishes. Its almost like they fail to move out of the "new" folder, then the folder is deleted and they are deleted with it.

**Comment by Shannon-Dubay** [comment]
just following up on this. is there anything else I can do?

**Comment by Shannon-Dubay** [comment]
Might be able to complete issue #159 with this issue.

**Comment by RossPitman** [comment]
OK so I managed to reproduce the error you're seeing. I originally couldn't reproduce it, so that's promising.

**Comment by RossPitman** [comment]
Finally fixed this. Closed.
